/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthenticatedStudentManagementIndexRouteImport } from './routes/_authenticated/student-management/index'
import { Route as AuthenticatedStudentManagementEnrollmentG1IndexRouteImport } from './routes/_authenticated/student-management/enrollment/g1/index'
import { Route as AuthenticatedStudentManagementEnrollmentG1Enrollment_idIndexRouteImport } from './routes/_authenticated/student-management/enrollment/g1/$enrollment_id/index'
import { Route as AuthenticatedStudentManagementEnrollmentG1Enrollment_idInterviewRouteImport } from './routes/_authenticated/student-management/enrollment/g1/$enrollment_id/interview'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentManagementIndexRoute =
  AuthenticatedStudentManagementIndexRouteImport.update({
    id: '/student-management/',
    path: '/student-management/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentManagementEnrollmentG1IndexRoute =
  AuthenticatedStudentManagementEnrollmentG1IndexRouteImport.update({
    id: '/student-management/enrollment/g1/',
    path: '/student-management/enrollment/g1/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentManagementEnrollmentG1Enrollment_idIndexRoute =
  AuthenticatedStudentManagementEnrollmentG1Enrollment_idIndexRouteImport.update(
    {
      id: '/student-management/enrollment/g1/$enrollment_id/',
      path: '/student-management/enrollment/g1/$enrollment_id/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedStudentManagementEnrollmentG1Enrollment_idInterviewRoute =
  AuthenticatedStudentManagementEnrollmentG1Enrollment_idInterviewRouteImport.update(
    {
      id: '/student-management/enrollment/g1/$enrollment_id/interview',
      path: '/student-management/enrollment/g1/$enrollment_id/interview',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/student-management/': typeof AuthenticatedStudentManagementIndexRoute
  '/student-management/enrollment/g1/': typeof AuthenticatedStudentManagementEnrollmentG1IndexRoute
  '/student-management/enrollment/g1/$enrollment_id/interview': typeof AuthenticatedStudentManagementEnrollmentG1Enrollment_idInterviewRoute
  '/student-management/enrollment/g1/$enrollment_id/': typeof AuthenticatedStudentManagementEnrollmentG1Enrollment_idIndexRoute
}
export interface FileRoutesByTo {
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof AuthenticatedIndexRoute
  '/student-management': typeof AuthenticatedStudentManagementIndexRoute
  '/student-management/enrollment/g1': typeof AuthenticatedStudentManagementEnrollmentG1IndexRoute
  '/student-management/enrollment/g1/$enrollment_id/interview': typeof AuthenticatedStudentManagementEnrollmentG1Enrollment_idInterviewRoute
  '/student-management/enrollment/g1/$enrollment_id': typeof AuthenticatedStudentManagementEnrollmentG1Enrollment_idIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/student-management/': typeof AuthenticatedStudentManagementIndexRoute
  '/_authenticated/student-management/enrollment/g1/': typeof AuthenticatedStudentManagementEnrollmentG1IndexRoute
  '/_authenticated/student-management/enrollment/g1/$enrollment_id/interview': typeof AuthenticatedStudentManagementEnrollmentG1Enrollment_idInterviewRoute
  '/_authenticated/student-management/enrollment/g1/$enrollment_id/': typeof AuthenticatedStudentManagementEnrollmentG1Enrollment_idIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/student-management/'
    | '/student-management/enrollment/g1/'
    | '/student-management/enrollment/g1/$enrollment_id/interview'
    | '/student-management/enrollment/g1/$enrollment_id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/student-management'
    | '/student-management/enrollment/g1'
    | '/student-management/enrollment/g1/$enrollment_id/interview'
    | '/student-management/enrollment/g1/$enrollment_id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_authenticated/'
    | '/_authenticated/student-management/'
    | '/_authenticated/student-management/enrollment/g1/'
    | '/_authenticated/student-management/enrollment/g1/$enrollment_id/interview'
    | '/_authenticated/student-management/enrollment/g1/$enrollment_id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student-management/': {
      id: '/_authenticated/student-management/'
      path: '/student-management'
      fullPath: '/student-management/'
      preLoaderRoute: typeof AuthenticatedStudentManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student-management/enrollment/g1/': {
      id: '/_authenticated/student-management/enrollment/g1/'
      path: '/student-management/enrollment/g1'
      fullPath: '/student-management/enrollment/g1/'
      preLoaderRoute: typeof AuthenticatedStudentManagementEnrollmentG1IndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student-management/enrollment/g1/$enrollment_id/': {
      id: '/_authenticated/student-management/enrollment/g1/$enrollment_id/'
      path: '/student-management/enrollment/g1/$enrollment_id'
      fullPath: '/student-management/enrollment/g1/$enrollment_id/'
      preLoaderRoute: typeof AuthenticatedStudentManagementEnrollmentG1Enrollment_idIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student-management/enrollment/g1/$enrollment_id/interview': {
      id: '/_authenticated/student-management/enrollment/g1/$enrollment_id/interview'
      path: '/student-management/enrollment/g1/$enrollment_id/interview'
      fullPath: '/student-management/enrollment/g1/$enrollment_id/interview'
      preLoaderRoute: typeof AuthenticatedStudentManagementEnrollmentG1Enrollment_idInterviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedStudentManagementIndexRoute: typeof AuthenticatedStudentManagementIndexRoute
  AuthenticatedStudentManagementEnrollmentG1IndexRoute: typeof AuthenticatedStudentManagementEnrollmentG1IndexRoute
  AuthenticatedStudentManagementEnrollmentG1Enrollment_idInterviewRoute: typeof AuthenticatedStudentManagementEnrollmentG1Enrollment_idInterviewRoute
  AuthenticatedStudentManagementEnrollmentG1Enrollment_idIndexRoute: typeof AuthenticatedStudentManagementEnrollmentG1Enrollment_idIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedStudentManagementIndexRoute:
    AuthenticatedStudentManagementIndexRoute,
  AuthenticatedStudentManagementEnrollmentG1IndexRoute:
    AuthenticatedStudentManagementEnrollmentG1IndexRoute,
  AuthenticatedStudentManagementEnrollmentG1Enrollment_idInterviewRoute:
    AuthenticatedStudentManagementEnrollmentG1Enrollment_idInterviewRoute,
  AuthenticatedStudentManagementEnrollmentG1Enrollment_idIndexRoute:
    AuthenticatedStudentManagementEnrollmentG1Enrollment_idIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
