// This file is auto-generated by @hey-api/openapi-ts

export const AddressEntrySchema = {
  type: "object",
  required: [
    "address_type",
    "is_primary",
    "residence_type",
    "workspace_address_id",
  ],
  properties: {
    address_type: {
      type: "string",
    },
    is_primary: {
      type: "boolean",
    },
    residence_type: {
      type: "string",
    },
    workspace_address_id: {
      type: "string",
      format: "uuid",
    },
  },
} as const

export const AddressEntryResponseSchema = {
  type: "object",
  required: [
    "address_type",
    "is_primary",
    "residence_type",
    "workspace_address_id",
  ],
  properties: {
    address_type: {
      type: "string",
    },
    is_primary: {
      type: "boolean",
    },
    residence_type: {
      type: "string",
    },
    workspace_address_id: {
      type: "string",
      format: "uuid",
    },
  },
} as const

export const ApplicationStatusSchema = {
  type: "string",
  enum: [
    "Draft",
    "Submitted",
    "DocsPending",
    "UnderVerification",
    "Verified",
    "Marked",
    "Shortlisted",
    "Appealed",
    "Finalized",
    "Admitted",
    "Rejected",
    "Withdrawn",
  ],
} as const

export const AuthResponseSchema = {
  title: "AuthResponse",
  type: "object",
  required: ["access_token", "expires_at", "refresh_token"],
  properties: {
    access_token: {
      type: "string",
    },
    expires_at: {
      type: "integer",
      format: "int64",
    },
    refresh_token: {
      type: "string",
    },
  },
} as const

export const BatchStatusSchema = {
  type: "string",
  enum: ["Open", "Closed", "Archived"],
} as const

export const CounterResponseSchema = {
  title: "CounterResponse",
  type: "object",
  required: ["name", "value"],
  properties: {
    name: {
      type: "string",
    },
    value: {
      type: "integer",
      format: "int32",
    },
  },
} as const

export const CreateBatchBodySchema = {
  title: "CreateBatchBody",
  type: "object",
  required: ["enrollment_type", "year"],
  properties: {
    alumni_weight: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
    enrollment_type: {
      $ref: "#/components/schemas/EnrollmentType",
    },
    govt_weight: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
    proximity_weight: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
    sibling_weight: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
    special_weight: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
    staff_weight: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
    student_allocation: {
      type: "integer",
      format: "int32",
      nullable: true,
    },
    year: {
      type: "integer",
      format: "int16",
    },
  },
} as const

export const CreateGuardianBodySchema = {
  title: "CreateGuardianBody",
  type: "object",
  required: [
    "contact_phone",
    "full_name",
    "is_govt_employee",
    "is_past_pupil",
    "is_school_staff",
    "nic_number",
    "relationship_type",
  ],
  properties: {
    contact_email: {
      type: "string",
      nullable: true,
    },
    contact_phone: {
      type: "string",
    },
    employee_id: {
      type: "string",
      nullable: true,
    },
    full_name: {
      type: "string",
    },
    govt_service_years: {
      type: "integer",
      format: "int32",
      nullable: true,
    },
    income_level: {
      allOf: [
        {
          $ref: "#/components/schemas/IncomeLevel",
        },
      ],
      nullable: true,
    },
    is_govt_employee: {
      type: "boolean",
    },
    is_past_pupil: {
      type: "boolean",
    },
    is_school_staff: {
      type: "boolean",
    },
    nic_number: {
      type: "string",
    },
    occupation: {
      type: "string",
      nullable: true,
    },
    past_pupil_highest_grade: {
      type: "string",
      nullable: true,
    },
    past_pupil_left_reason: {
      type: "string",
      nullable: true,
    },
    past_pupil_school_id: {
      type: "string",
      format: "uuid",
      nullable: true,
    },
    past_pupil_student_id: {
      type: "string",
      nullable: true,
    },
    past_pupil_year_left: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
    relationship_type: {
      type: "string",
    },
    staff_school_id: {
      type: "string",
      format: "uuid",
      nullable: true,
    },
    staff_type: {
      allOf: [
        {
          $ref: "#/components/schemas/StaffType",
        },
      ],
      nullable: true,
    },
    workplace_address: {
      type: "string",
      nullable: true,
    },
    workplace_name: {
      type: "string",
      nullable: true,
    },
  },
} as const

export const CreatePastPupilDetailBodySchema = {
  title: "CreatePastPupilDetailBody",
  type: "object",
  required: ["guardian_id", "school_id"],
  properties: {
    guardian_id: {
      type: "string",
      format: "uuid",
    },
    highest_grade: {
      type: "string",
      nullable: true,
    },
    left_reason: {
      type: "string",
      nullable: true,
    },
    school_id: {
      type: "string",
      format: "uuid",
    },
    student_id: {
      type: "string",
      nullable: true,
    },
    verification_method: {
      type: "string",
      nullable: true,
    },
    year_left: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
  },
} as const

export const CreateSiblingRequestSchema = {
  title: "CreateSiblingRequest",
  type: "object",
  required: [
    "date_of_birth",
    "full_name",
    "gender",
    "medium_of_instruction",
    "name_with_initials",
    "nationality",
  ],
  properties: {
    birth_certificate_number: {
      type: "string",
      nullable: true,
    },
    current_grade: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
    date_of_birth: {
      type: "string",
      format: "date",
    },
    email: {
      type: "string",
      nullable: true,
    },
    full_name: {
      type: "string",
    },
    gender: {
      $ref: "#/components/schemas/Gender",
    },
    medium_of_instruction: {
      $ref: "#/components/schemas/MediumOfInstruction",
    },
    name_with_initials: {
      type: "string",
    },
    nationality: {
      $ref: "#/components/schemas/Nationality",
    },
    nic: {
      type: "string",
      nullable: true,
    },
    passport_number: {
      type: "string",
      nullable: true,
    },
    phone: {
      type: "string",
      nullable: true,
    },
    religion: {
      allOf: [
        {
          $ref: "#/components/schemas/Religion",
        },
      ],
      nullable: true,
    },
    school_id: {
      type: "string",
      format: "uuid",
      nullable: true,
    },
  },
} as const

export const CreateSiblingResponseSchema = {
  title: "CreateSiblingResponse",
  type: "object",
  required: ["created", "duplicates"],
  properties: {
    created: {
      type: "boolean",
    },
    duplicates: {
      type: "array",
      items: {
        $ref: "#/components/schemas/StudentDuplicate",
      },
    },
    student_id: {
      type: "string",
      format: "uuid",
      nullable: true,
    },
  },
} as const

export const CreateStaffDetailBodySchema = {
  title: "CreateStaffDetailBody",
  type: "object",
  required: ["guardian_id", "school_id"],
  properties: {
    designation: {
      type: "string",
      nullable: true,
    },
    employee_id: {
      type: "string",
      nullable: true,
    },
    guardian_id: {
      type: "string",
      format: "uuid",
    },
    school_id: {
      type: "string",
      format: "uuid",
    },
    staff_type: {
      allOf: [
        {
          $ref: "#/components/schemas/StaffType",
        },
      ],
      nullable: true,
    },
  },
} as const

export const CreateWorkspaceAddressBodySchema = {
  title: "CreateWorkspaceAddressBody",
  type: "object",
  required: ["city", "country", "name", "street_1"],
  properties: {
    building: {
      type: "string",
      nullable: true,
    },
    city: {
      type: "string",
    },
    country: {
      type: "string",
    },
    name: {
      type: "string",
    },
    postal_code: {
      type: "string",
      nullable: true,
    },
    state: {
      type: "string",
      nullable: true,
    },
    street_1: {
      type: "string",
    },
    street_2: {
      type: "string",
      nullable: true,
    },
  },
} as const

export const DocumentEntrySchema = {
  type: "object",
  required: ["doc_type", "file_key", "file_url"],
  properties: {
    content_type: {
      type: "string",
      nullable: true,
    },
    doc_type: {
      type: "string",
    },
    file_key: {
      type: "string",
    },
    file_name: {
      type: "string",
      nullable: true,
    },
    file_size: {
      type: "integer",
      format: "int64",
      nullable: true,
    },
    file_url: {
      type: "string",
    },
  },
} as const

export const EnrollmentBatchSchema = {
  title: "EnrollmentBatch",
  type: "object",
  required: ["batch_code", "batch_name", "enrollment_type", "year"],
  properties: {
    alumni_weight: {
      default: 6,
      type: "integer",
      format: "int16",
    },
    batch_code: {
      description: 'Machine-readable code (e.g., "G1-2026")',
      type: "string",
    },
    batch_name: {
      description: 'Human-readable name (e.g., "Grade 1 Admission 2026")',
      type: "string",
    },
    created_at: {
      default: "2026-07-20T13:35:28.241084600Z",
      type: "string",
      format: "date-time",
    },
    created_by: {
      default: null,
      type: "string",
      format: "uuid",
      nullable: true,
    },
    enrollment_type: {
      $ref: "#/components/schemas/EnrollmentType",
    },
    govt_weight: {
      default: 4,
      type: "integer",
      format: "int16",
    },
    id: {
      default: "9f82c66f-aaf1-4aca-9c26-52199d7c77a6",
      type: "string",
      format: "uuid",
    },
    proximity_weight: {
      default: 50,
      type: "integer",
      format: "int16",
    },
    sibling_weight: {
      default: 14,
      type: "integer",
      format: "int16",
    },
    special_weight: {
      default: 1,
      type: "integer",
      format: "int16",
    },
    staff_weight: {
      default: 25,
      type: "integer",
      format: "int16",
    },
    status: {
      default: "Open",
      allOf: [
        {
          $ref: "#/components/schemas/BatchStatus",
        },
      ],
    },
    student_allocation: {
      default: 200,
      type: "integer",
      format: "int32",
    },
    year: {
      type: "integer",
      format: "int16",
    },
  },
} as const

export const EnrollmentStatusSchema = {
  type: "string",
  enum: [
    "Draft",
    "Pending",
    "ProvisionallyApproved",
    "Approved",
    "Rejected",
    "Withdrawn",
    "Removed",
  ],
} as const

export const EnrollmentTypeSchema = {
  type: "string",
  enum: ["G1"],
} as const

export const G1ApplicationSchema = {
  title: "G1Application",
  type: "object",
  required: [
    "batch_id",
    "date_of_birth",
    "full_name",
    "gender",
    "medium_of_instruction",
    "name_with_initials",
    "nationality",
  ],
  properties: {
    age_eligibility_verified: {
      default: false,
      type: "boolean",
    },
    alternative_age_certificate: {
      default: false,
      type: "boolean",
    },
    alternative_age_certificate_ref: {
      default: null,
      type: "string",
      nullable: true,
    },
    applied_year: {
      default: 0,
      type: "integer",
      format: "int16",
    },
    batch_id: {
      type: "string",
      format: "uuid",
    },
    birth_certificate_number: {
      default: null,
      type: "string",
      nullable: true,
    },
    birth_certificate_verified: {
      default: false,
      type: "boolean",
    },
    category: {
      default: null,
      allOf: [
        {
          $ref: "#/components/schemas/G1Category",
        },
      ],
      nullable: true,
    },
    category_verified: {
      default: false,
      type: "boolean",
    },
    created_at: {
      default: "2026-07-20T13:35:28.238199900Z",
      type: "string",
      format: "date-time",
    },
    created_by: {
      default: null,
      type: "string",
      format: "uuid",
      nullable: true,
    },
    date_of_birth: {
      type: "string",
      format: "date",
    },
    enrollment_status: {
      default: "Draft",
      allOf: [
        {
          $ref: "#/components/schemas/EnrollmentStatus",
        },
      ],
    },
    finalized_at: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
    full_name: {
      type: "string",
    },
    gender: {
      $ref: "#/components/schemas/Gender",
    },
    guardian_id: {
      default: null,
      type: "string",
      format: "uuid",
      nullable: true,
    },
    id: {
      default: "73803039-12dd-458c-bd22-56bdd82390eb",
      type: "string",
      format: "uuid",
    },
    interview_completed: {
      default: false,
      type: "boolean",
    },
    interview_date: {
      default: null,
      type: "string",
      format: "date",
      nullable: true,
    },
    ip_address: {
      type: "string",
      nullable: true,
    },
    list_category: {
      type: "string",
      nullable: true,
    },
    medium_of_instruction: {
      $ref: "#/components/schemas/MediumOfInstruction",
    },
    name_with_initials: {
      type: "string",
    },
    nationality: {
      $ref: "#/components/schemas/Nationality",
    },
    overseas_arrival_date: {
      default: null,
      type: "string",
      format: "date",
      nullable: true,
    },
    rank_number: {
      type: "integer",
      format: "int32",
      nullable: true,
    },
    reference_no: {
      default: "TMP-5da55c13-b9f6-4056-bbb4-3ca597ce0bf1",
      type: "string",
    },
    rejection_reason: {
      default: null,
      type: "string",
      nullable: true,
    },
    religion: {
      default: null,
      allOf: [
        {
          $ref: "#/components/schemas/Religion",
        },
      ],
      nullable: true,
    },
    residence_verified: {
      default: false,
      type: "boolean",
    },
    school_id: {
      default: null,
      type: "string",
      format: "uuid",
      nullable: true,
    },
    status: {
      default: "Draft",
      allOf: [
        {
          $ref: "#/components/schemas/ApplicationStatus",
        },
      ],
    },
    student_id: {
      default: null,
      type: "string",
      format: "uuid",
      nullable: true,
    },
    submission_method: {
      default: null,
      type: "string",
      nullable: true,
    },
    submitted_at: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
    total_marks: {
      type: "string",
      pattern: "^-?[0-9]+(\\.[0-9]+)?$",
      nullable: true,
    },
    updated_at: {
      default: "2026-07-20T13:35:28.238203Z",
      type: "string",
      format: "date-time",
    },
    updated_by: {
      default: null,
      type: "string",
      format: "uuid",
      nullable: true,
    },
    user_agent: {
      type: "string",
      nullable: true,
    },
    verified_at: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
    verified_by: {
      type: "string",
      format: "uuid",
      nullable: true,
    },
    wizard_step: {
      default: null,
      type: "integer",
      format: "int16",
      nullable: true,
    },
  },
} as const

export const G1CategorySchema = {
  type: "string",
  enum: [
    "CloseResident",
    "PastPupilChild",
    "Sibling",
    "MOEOrUGCStaffChild",
    "GovernmentTransferOfficerChild",
    "OverseasArrival",
    "ArmedForcesReserved",
  ],
} as const

export const GenderSchema = {
  type: "string",
  enum: ["Male", "Female"],
} as const

export const GenerateListsRequestSchema = {
  title: "GenerateListsRequest",
  type: "object",
  required: ["batch_id"],
  properties: {
    batch_id: {
      type: "string",
      format: "uuid",
    },
  },
} as const

export const GenerateListsResponseSchema = {
  title: "GenerateListsResponse",
  type: "object",
  required: ["batch_id", "schools", "total_generated"],
  properties: {
    batch_id: {
      type: "string",
      format: "uuid",
    },
    schools: {
      type: "array",
      items: {
        $ref: "#/components/schemas/SchoolListSummary",
      },
    },
    total_generated: {
      type: "integer",
      format: "uint",
      minimum: 0,
    },
  },
} as const

export const GetApplicationGuardiansResponseSchema = {
  title: "GetApplicationGuardiansResponse",
  type: "object",
  required: ["guardian_ids"],
  properties: {
    guardian_ids: {
      type: "array",
      items: {
        type: "string",
        format: "uuid",
      },
    },
  },
} as const

export const GetApplicationSiblingsResponseSchema = {
  title: "GetApplicationSiblingsResponse",
  type: "object",
  required: ["sibling_ids"],
  properties: {
    sibling_ids: {
      type: "array",
      items: {
        type: "string",
        format: "uuid",
      },
    },
  },
} as const

export const GetApplicationWorkspaceAddressesResponseSchema = {
  title: "GetApplicationWorkspaceAddressesResponse",
  type: "object",
  required: ["addresses"],
  properties: {
    addresses: {
      type: "array",
      items: {
        $ref: "#/components/schemas/AddressEntryResponse",
      },
    },
  },
} as const

export const GetDocumentsResponseSchema = {
  title: "GetDocumentsResponse",
  type: "object",
  required: ["documents"],
  properties: {
    documents: {
      type: "array",
      items: {
        $ref: "#/components/schemas/DocumentEntry",
      },
    },
  },
} as const

export const GuardianSchema = {
  title: "Guardian",
  type: "object",
  required: [
    "full_name",
    "id",
    "is_govt_employee",
    "is_past_pupil",
    "is_school_staff",
    "nic_number",
    "past_pupil_verified",
    "relationship_type",
  ],
  properties: {
    address_id: {
      default: null,
      type: "string",
      format: "uuid",
      nullable: true,
    },
    contact_email: {
      type: "string",
      nullable: true,
    },
    contact_phone: {
      default: "0",
      type: "string",
    },
    created_at: {
      default: "2026-07-20T13:35:28.242506500Z",
      type: "string",
      format: "date-time",
    },
    full_name: {
      type: "string",
    },
    govt_service_years: {
      type: "integer",
      format: "int32",
      nullable: true,
    },
    id: {
      type: "string",
      format: "uuid",
    },
    income_level: {
      allOf: [
        {
          $ref: "#/components/schemas/IncomeLevel",
        },
      ],
      nullable: true,
    },
    is_govt_employee: {
      type: "boolean",
    },
    is_past_pupil: {
      type: "boolean",
    },
    is_school_staff: {
      type: "boolean",
    },
    nic_number: {
      type: "string",
    },
    occupation: {
      type: "string",
      nullable: true,
    },
    past_pupil_verified: {
      type: "boolean",
    },
    relationship_type: {
      type: "string",
    },
    workplace_address: {
      type: "string",
      nullable: true,
    },
    workplace_name: {
      type: "string",
      nullable: true,
    },
  },
} as const

export const IncomeLevelSchema = {
  type: "string",
  enum: [
    "below_25000",
    "25000_50000",
    "50000_100000",
    "100000_200000",
    "200000_500000",
    "above_500000",
  ],
} as const

export const LoginRequestSchema = {
  title: "LoginRequest",
  type: "object",
  required: ["email", "password"],
  properties: {
    email: {
      type: "string",
    },
    password: {
      type: "string",
    },
  },
} as const

export const MediumOfInstructionSchema = {
  type: "string",
  enum: ["Sinhala", "Tamil"],
} as const

export const MessageResponseSchema = {
  title: "MessageResponse",
  type: "object",
  required: ["message"],
  properties: {
    message: {
      type: "string",
    },
  },
} as const

export const ModelSchema = {
  title: "Model",
  type: "object",
  required: ["guardian_id", "id", "school_id", "verified"],
  properties: {
    created_at: {
      default: "2026-07-20T13:35:28.242985100Z",
      type: "string",
      format: "date-time",
    },
    guardian_id: {
      type: "string",
      format: "uuid",
    },
    highest_grade: {
      type: "string",
      nullable: true,
    },
    id: {
      type: "string",
      format: "uuid",
    },
    left_reason: {
      type: "string",
      nullable: true,
    },
    school_id: {
      type: "string",
      format: "uuid",
    },
    student_id: {
      type: "string",
      nullable: true,
    },
    verification_method: {
      type: "string",
      nullable: true,
    },
    verified: {
      type: "boolean",
    },
    year_left: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
  },
} as const

export const NationalitySchema = {
  type: "string",
  enum: ["SriLankan", "DualCitizen", "Other"],
} as const

export const PaginatedApplicationsResponseSchema = {
  title: "PaginatedApplicationsResponse",
  type: "object",
  required: ["items", "total"],
  properties: {
    items: {
      type: "array",
      items: {
        $ref: "#/components/schemas/G1Application",
      },
    },
    total: {
      type: "integer",
      format: "int32",
    },
  },
} as const

export const PresignedUploadRequestSchema = {
  title: "PresignedUploadRequest",
  type: "object",
  required: ["content_type", "file_name", "file_size"],
  properties: {
    content_type: {
      type: "string",
    },
    file_name: {
      type: "string",
    },
    file_size: {
      type: "integer",
      format: "int64",
    },
  },
} as const

export const PresignedUploadResponseSchema = {
  title: "PresignedUploadResponse",
  type: "object",
  required: [
    "content_type",
    "file_name",
    "file_size",
    "key",
    "public_url",
    "url",
  ],
  properties: {
    content_type: {
      type: "string",
    },
    file_name: {
      type: "string",
    },
    file_size: {
      type: "integer",
      format: "int64",
    },
    key: {
      type: "string",
    },
    public_url: {
      type: "string",
    },
    url: {
      type: "string",
    },
  },
} as const

export const RefreshRequestSchema = {
  title: "RefreshRequest",
  type: "object",
  required: ["refresh_token"],
  properties: {
    refresh_token: {
      type: "string",
    },
  },
} as const

export const RegisterRequestSchema = {
  title: "RegisterRequest",
  type: "object",
  required: ["email", "password"],
  properties: {
    email: {
      type: "string",
    },
    password: {
      type: "string",
    },
  },
} as const

export const ReligionSchema = {
  type: "string",
  enum: [
    "Buddhism",
    "Hinduism",
    "Islam",
    "Christianity",
    "Catholicism",
    "Other",
  ],
} as const

export const SaveDocumentEntrySchema = {
  type: "object",
  required: ["doc_type", "file_key", "file_url"],
  properties: {
    content_type: {
      type: "string",
      nullable: true,
    },
    doc_type: {
      type: "string",
    },
    file_key: {
      type: "string",
    },
    file_size: {
      type: "integer",
      format: "int64",
      nullable: true,
    },
    file_url: {
      type: "string",
    },
  },
} as const

export const SaveDocumentsRequestSchema = {
  title: "SaveDocumentsRequest",
  type: "object",
  required: ["documents"],
  properties: {
    documents: {
      type: "array",
      items: {
        $ref: "#/components/schemas/SaveDocumentEntry",
      },
    },
  },
} as const

export const SaveDocumentsResponseSchema = {
  title: "SaveDocumentsResponse",
  type: "object",
  required: ["count"],
  properties: {
    count: {
      type: "integer",
      format: "uint",
      minimum: 0,
    },
  },
} as const

export const SaveGuardiansRequestSchema = {
  title: "SaveGuardiansRequest",
  type: "object",
  required: ["guardian_ids"],
  properties: {
    guardian_ids: {
      type: "array",
      items: {
        type: "string",
        format: "uuid",
      },
    },
  },
} as const

export const SaveGuardiansResponseSchema = {
  title: "SaveGuardiansResponse",
  type: "object",
  required: ["count"],
  properties: {
    count: {
      type: "integer",
      format: "uint",
      minimum: 0,
    },
  },
} as const

export const SaveSiblingsRequestSchema = {
  title: "SaveSiblingsRequest",
  type: "object",
  required: ["student_ids"],
  properties: {
    student_ids: {
      type: "array",
      items: {
        type: "string",
        format: "uuid",
      },
    },
  },
} as const

export const SaveSiblingsResponseSchema = {
  title: "SaveSiblingsResponse",
  type: "object",
  required: ["count"],
  properties: {
    count: {
      type: "integer",
      format: "uint",
      minimum: 0,
    },
  },
} as const

export const SaveStepRequestSchema = {
  title: "SaveStepRequest",
  type: "object",
  required: ["wizard_step"],
  properties: {
    wizard_step: {
      type: "integer",
      format: "int16",
    },
  },
} as const

export const SaveStepResponseSchema = {
  title: "SaveStepResponse",
  type: "object",
  required: ["wizard_step"],
  properties: {
    wizard_step: {
      type: "integer",
      format: "int16",
    },
  },
} as const

export const SaveWorkspaceAddressesRequestSchema = {
  title: "SaveWorkspaceAddressesRequest",
  type: "object",
  required: ["addresses"],
  properties: {
    addresses: {
      type: "array",
      items: {
        $ref: "#/components/schemas/AddressEntry",
      },
    },
  },
} as const

export const SaveWorkspaceAddressesResponseSchema = {
  title: "SaveWorkspaceAddressesResponse",
  type: "object",
  required: ["count"],
  properties: {
    count: {
      type: "integer",
      format: "uint",
      minimum: 0,
    },
  },
} as const

export const SchoolListSummarySchema = {
  type: "object",
  required: [
    "main_list_count",
    "school_id",
    "school_name",
    "waiting_list_count",
  ],
  properties: {
    main_list_count: {
      type: "integer",
      format: "uint",
      minimum: 0,
    },
    school_id: {
      type: "string",
      format: "uuid",
    },
    school_name: {
      type: "string",
    },
    waiting_list_count: {
      type: "integer",
      format: "uint",
      minimum: 0,
    },
  },
} as const

export const SchoolSummarySchema = {
  title: "SchoolSummary",
  type: "object",
  required: ["id", "name_si"],
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    name_en: {
      type: "string",
      nullable: true,
    },
    name_si: {
      type: "string",
    },
  },
} as const

export const StaffDetailSchema = {
  title: "StaffDetail",
  type: "object",
  required: ["guardian_id", "id", "is_current", "school_id"],
  properties: {
    created_at: {
      default: "2026-07-20T13:35:28.243748500Z",
      type: "string",
      format: "date-time",
    },
    designation: {
      type: "string",
      nullable: true,
    },
    distance_from_residence_km: {
      type: "string",
      pattern: "^-?[0-9]+(\\.[0-9]+)?$",
      nullable: true,
    },
    employee_id: {
      type: "string",
      nullable: true,
    },
    employment_type: {
      allOf: [
        {
          $ref: "#/components/schemas/StaffEmploymentType",
        },
      ],
      nullable: true,
    },
    guardian_id: {
      type: "string",
      format: "uuid",
    },
    id: {
      type: "string",
      format: "uuid",
    },
    is_current: {
      type: "boolean",
    },
    school_id: {
      type: "string",
      format: "uuid",
    },
    service_end_date: {
      type: "string",
      format: "date",
      nullable: true,
    },
    service_start_date: {
      type: "string",
      format: "date",
      nullable: true,
    },
    staff_type: {
      allOf: [
        {
          $ref: "#/components/schemas/StaffType",
        },
      ],
      nullable: true,
    },
    verification_doc: {
      type: "string",
      nullable: true,
    },
  },
} as const

export const StaffEmploymentTypeSchema = {
  type: "string",
  enum: ["Permanent", "Temporary", "Contract"],
} as const

export const StaffTypeSchema = {
  type: "string",
  enum: ["Teacher", "Admin", "Worker"],
} as const

export const StudentSchema = {
  title: "Student",
  type: "object",
  required: [
    "created_at",
    "date_of_birth",
    "full_name",
    "gender",
    "id",
    "medium_of_instruction",
    "name_with_initials",
    "nationality",
    "status",
    "updated_at",
  ],
  properties: {
    admission_date: {
      type: "string",
      format: "date",
      nullable: true,
    },
    admission_number: {
      type: "string",
      nullable: true,
    },
    birth_certificate_number: {
      type: "string",
      nullable: true,
    },
    created_at: {
      type: "string",
      format: "date-time",
    },
    created_by: {
      type: "string",
      format: "uuid",
      nullable: true,
    },
    current_grade: {
      description: "Integer representing the grade (e.g., 1 for Grade 1)",
      type: "integer",
      format: "int16",
      nullable: true,
    },
    date_of_birth: {
      description: "Format: YYYY-MM-DD",
      type: "string",
      format: "date",
    },
    email: {
      type: "string",
      nullable: true,
    },
    full_name: {
      type: "string",
    },
    gender: {
      $ref: "#/components/schemas/Gender",
    },
    id: {
      type: "string",
      format: "uuid",
    },
    medium_of_instruction: {
      $ref: "#/components/schemas/MediumOfInstruction",
    },
    name_with_initials: {
      type: "string",
    },
    nationality: {
      $ref: "#/components/schemas/Nationality",
    },
    nic: {
      type: "string",
      nullable: true,
    },
    passport_number: {
      type: "string",
      nullable: true,
    },
    phone: {
      description: "E.164 format recommended",
      type: "string",
      nullable: true,
    },
    religion: {
      allOf: [
        {
          $ref: "#/components/schemas/Religion",
        },
      ],
      nullable: true,
    },
    status: {
      $ref: "#/components/schemas/StudentStatus",
    },
    updated_at: {
      type: "string",
      format: "date-time",
    },
    updated_by: {
      type: "string",
      format: "uuid",
      nullable: true,
    },
  },
} as const

export const StudentDuplicateSchema = {
  type: "object",
  required: [
    "date_of_birth",
    "full_name",
    "gender",
    "id",
    "medium_of_instruction",
    "name_with_initials",
    "nationality",
  ],
  properties: {
    birth_certificate_number: {
      type: "string",
      nullable: true,
    },
    current_grade: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
    date_of_birth: {
      type: "string",
      format: "date",
    },
    full_name: {
      type: "string",
    },
    gender: {
      $ref: "#/components/schemas/Gender",
    },
    id: {
      type: "string",
      format: "uuid",
    },
    medium_of_instruction: {
      $ref: "#/components/schemas/MediumOfInstruction",
    },
    name_with_initials: {
      type: "string",
    },
    nationality: {
      $ref: "#/components/schemas/Nationality",
    },
    nic: {
      type: "string",
      nullable: true,
    },
  },
} as const

export const StudentStatusSchema = {
  type: "string",
  enum: ["Active", "Graduated", "Removed"],
} as const

export const UpdateBatchBodySchema = {
  title: "UpdateBatchBody",
  type: "object",
  properties: {
    alumni_weight: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
    govt_weight: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
    proximity_weight: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
    sibling_weight: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
    special_weight: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
    staff_weight: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
    status: {
      allOf: [
        {
          $ref: "#/components/schemas/BatchStatus",
        },
      ],
      nullable: true,
    },
    student_allocation: {
      type: "integer",
      format: "int32",
      nullable: true,
    },
  },
} as const

export const UpdateGuardianBodySchema = {
  title: "UpdateGuardianBody",
  type: "object",
  required: [
    "contact_phone",
    "full_name",
    "is_govt_employee",
    "is_past_pupil",
    "is_school_staff",
    "nic_number",
    "relationship_type",
  ],
  properties: {
    address_id: {
      type: "string",
      format: "uuid",
      nullable: true,
    },
    contact_email: {
      type: "string",
      nullable: true,
    },
    contact_phone: {
      type: "string",
    },
    employee_id: {
      type: "string",
      nullable: true,
    },
    full_name: {
      type: "string",
    },
    govt_service_years: {
      type: "integer",
      format: "int32",
      nullable: true,
    },
    income_level: {
      allOf: [
        {
          $ref: "#/components/schemas/IncomeLevel",
        },
      ],
      nullable: true,
    },
    is_govt_employee: {
      type: "boolean",
    },
    is_past_pupil: {
      type: "boolean",
    },
    is_school_staff: {
      type: "boolean",
    },
    nic_number: {
      type: "string",
    },
    occupation: {
      type: "string",
      nullable: true,
    },
    past_pupil_highest_grade: {
      type: "string",
      nullable: true,
    },
    past_pupil_left_reason: {
      type: "string",
      nullable: true,
    },
    past_pupil_school_id: {
      type: "string",
      format: "uuid",
      nullable: true,
    },
    past_pupil_student_id: {
      type: "string",
      nullable: true,
    },
    past_pupil_year_left: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
    relationship_type: {
      type: "string",
    },
    staff_school_id: {
      type: "string",
      format: "uuid",
      nullable: true,
    },
    staff_type: {
      allOf: [
        {
          $ref: "#/components/schemas/StaffType",
        },
      ],
      nullable: true,
    },
    workplace_address: {
      type: "string",
      nullable: true,
    },
    workplace_name: {
      type: "string",
      nullable: true,
    },
  },
} as const

export const UpdateStudentRequestSchema = {
  title: "UpdateStudentRequest",
  type: "object",
  required: [
    "date_of_birth",
    "full_name",
    "gender",
    "medium_of_instruction",
    "name_with_initials",
    "nationality",
  ],
  properties: {
    birth_certificate_number: {
      type: "string",
      nullable: true,
    },
    current_grade: {
      type: "integer",
      format: "int16",
      nullable: true,
    },
    date_of_birth: {
      type: "string",
      format: "date",
    },
    email: {
      type: "string",
      nullable: true,
    },
    full_name: {
      type: "string",
    },
    gender: {
      $ref: "#/components/schemas/Gender",
    },
    medium_of_instruction: {
      $ref: "#/components/schemas/MediumOfInstruction",
    },
    name_with_initials: {
      type: "string",
    },
    nationality: {
      $ref: "#/components/schemas/Nationality",
    },
    nic: {
      type: "string",
      nullable: true,
    },
    passport_number: {
      type: "string",
      nullable: true,
    },
    phone: {
      type: "string",
      nullable: true,
    },
    religion: {
      allOf: [
        {
          $ref: "#/components/schemas/Religion",
        },
      ],
      nullable: true,
    },
  },
} as const

export const UploadFormSchema = {
  title: "UploadForm",
  type: "object",
} as const

export const UploadResponseSchema = {
  title: "UploadResponse",
  type: "object",
  required: ["file_name", "key", "size", "url"],
  properties: {
    file_name: {
      type: "string",
    },
    key: {
      type: "string",
    },
    size: {
      type: "integer",
      format: "uint",
      minimum: 0,
    },
    url: {
      type: "string",
    },
  },
} as const

export const UserResponseSchema = {
  title: "UserResponse",
  type: "object",
  required: ["email", "id"],
  properties: {
    email: {
      type: "string",
    },
    id: {
      type: "string",
    },
  },
} as const

export const WorkspaceAddressSchema = {
  title: "WorkspaceAddress",
  type: "object",
  required: ["city", "country", "full_address", "id", "name", "street_1"],
  properties: {
    building: {
      type: "string",
      nullable: true,
    },
    city: {
      type: "string",
    },
    country: {
      type: "string",
    },
    created_at: {
      default: "2026-07-20T13:35:28.245069400Z",
      type: "string",
      format: "date-time",
    },
    full_address: {
      type: "string",
    },
    id: {
      type: "string",
      format: "uuid",
    },
    name: {
      type: "string",
    },
    postal_code: {
      type: "string",
      nullable: true,
    },
    state: {
      type: "string",
      nullable: true,
    },
    street_1: {
      type: "string",
    },
    street_2: {
      type: "string",
      nullable: true,
    },
  },
} as const
