// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateBatchData, CreateBatchErrors, CreateBatchResponses, CreateEnrollmentData, CreateEnrollmentErrors, CreateEnrollmentResponses, DeleteBatchData, DeleteBatchErrors, DeleteBatchResponses, DeleteEnrollmentData, DeleteEnrollmentErrors, DeleteEnrollmentResponses, GetBatchData, GetBatchErrors, GetBatchResponses, GetCounterData, GetCounterErrors, GetCounterResponses, GetEnrollmentData, GetEnrollmentErrors, GetEnrollmentResponses, GetSecureCounterData, GetSecureCounterErrors, GetSecureCounterResponses, IncrementCounterData, IncrementCounterErrors, IncrementCounterResponses, IncrementSecureCounterData, IncrementSecureCounterErrors, IncrementSecureCounterResponses, ListBatchesData, ListBatchesErrors, ListBatchesResponses, ListEnrollmentsData, ListEnrollmentsErrors, ListEnrollmentsResponses, LoginData, LoginErrors, LoginResponses, LogoutAllData, LogoutAllErrors, LogoutAllResponses, LogoutData, LogoutErrors, LogoutResponses, MeData, MeErrors, MeResponses, RefreshData, RefreshErrors, RefreshResponses, RegisterData, RegisterErrors, RegisterResponses, UpdateBatchData, UpdateBatchErrors, UpdateBatchResponses, UpdateEnrollmentData, UpdateEnrollmentErrors, UpdateEnrollmentResponses, UploadFileData, UploadFileErrors, UploadFileResponses } from './types.gen';
import { vCreateBatchBody2, vCreateBatchResponse, vCreateEnrollmentBody, vCreateEnrollmentResponse, vDeleteBatchPath, vDeleteBatchResponse, vDeleteEnrollmentPath, vDeleteEnrollmentResponse, vGetBatchPath, vGetBatchResponse, vGetCounterPath, vGetCounterResponse, vGetEnrollmentPath, vGetEnrollmentResponse, vGetSecureCounterPath, vGetSecureCounterResponse, vIncrementCounterPath, vIncrementCounterResponse, vIncrementSecureCounterPath, vIncrementSecureCounterResponse, vListBatchesResponse, vListEnrollmentsQuery, vListEnrollmentsResponse, vLoginBody, vLoginResponse, vLogoutAllResponse, vLogoutBody, vLogoutResponse, vMeResponse, vRefreshBody, vRefreshResponse, vRegisterBody, vRegisterResponse, vUpdateBatchBody2, vUpdateBatchPath, vUpdateBatchResponse, vUpdateEnrollmentBody, vUpdateEnrollmentPath, vUpdateEnrollmentResponse, vUploadFileBody, vUploadFileResponse } from './valibot.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getCounter = <ThrowOnError extends boolean = false>(options: Options<GetCounterData, ThrowOnError>): RequestResult<GetCounterResponses, GetCounterErrors, ThrowOnError> => (options.client ?? client).get<GetCounterResponses, GetCounterErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: vGetCounterPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vGetCounterResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/counter/{name}',
    ...options
});

export const incrementCounter = <ThrowOnError extends boolean = false>(options: Options<IncrementCounterData, ThrowOnError>): RequestResult<IncrementCounterResponses, IncrementCounterErrors, ThrowOnError> => (options.client ?? client).post<IncrementCounterResponses, IncrementCounterErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: vIncrementCounterPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vIncrementCounterResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/counter/{name}/increment',
    ...options
});

export const getSecureCounter = <ThrowOnError extends boolean = false>(options: Options<GetSecureCounterData, ThrowOnError>): RequestResult<GetSecureCounterResponses, GetSecureCounterErrors, ThrowOnError> => (options.client ?? client).get<GetSecureCounterResponses, GetSecureCounterErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: vGetSecureCounterPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vGetSecureCounterResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/counter/secure/{name}',
    ...options
});

export const incrementSecureCounter = <ThrowOnError extends boolean = false>(options: Options<IncrementSecureCounterData, ThrowOnError>): RequestResult<IncrementSecureCounterResponses, IncrementSecureCounterErrors, ThrowOnError> => (options.client ?? client).post<IncrementSecureCounterResponses, IncrementSecureCounterErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: vIncrementSecureCounterPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vIncrementSecureCounterResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/counter/secure/{name}/increment',
    ...options
});

export const listEnrollments = <ThrowOnError extends boolean = false>(options?: Options<ListEnrollmentsData, ThrowOnError>): RequestResult<ListEnrollmentsResponses, ListEnrollmentsErrors, ThrowOnError> => (options?.client ?? client).get<ListEnrollmentsResponses, ListEnrollmentsErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: v.optional(v.never()),
        query: v.optional(vListEnrollmentsQuery)
    }), data),
    responseValidator: async (data) => await v.parseAsync(vListEnrollmentsResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/g1-enrollments',
    ...options
});

export const createEnrollment = <ThrowOnError extends boolean = false>(options: Options<CreateEnrollmentData, ThrowOnError>): RequestResult<CreateEnrollmentResponses, CreateEnrollmentErrors, ThrowOnError> => (options.client ?? client).post<CreateEnrollmentResponses, CreateEnrollmentErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vCreateEnrollmentBody,
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vCreateEnrollmentResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/g1-enrollments',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteEnrollment = <ThrowOnError extends boolean = false>(options: Options<DeleteEnrollmentData, ThrowOnError>): RequestResult<DeleteEnrollmentResponses, DeleteEnrollmentErrors, ThrowOnError> => (options.client ?? client).delete<DeleteEnrollmentResponses, DeleteEnrollmentErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: vDeleteEnrollmentPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vDeleteEnrollmentResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/g1-enrollments/{id}',
    ...options
});

export const getEnrollment = <ThrowOnError extends boolean = false>(options: Options<GetEnrollmentData, ThrowOnError>): RequestResult<GetEnrollmentResponses, GetEnrollmentErrors, ThrowOnError> => (options.client ?? client).get<GetEnrollmentResponses, GetEnrollmentErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: vGetEnrollmentPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vGetEnrollmentResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/g1-enrollments/{id}',
    ...options
});

export const updateEnrollment = <ThrowOnError extends boolean = false>(options: Options<UpdateEnrollmentData, ThrowOnError>): RequestResult<UpdateEnrollmentResponses, UpdateEnrollmentErrors, ThrowOnError> => (options.client ?? client).put<UpdateEnrollmentResponses, UpdateEnrollmentErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vUpdateEnrollmentBody,
        path: vUpdateEnrollmentPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vUpdateEnrollmentResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/g1-enrollments/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const listBatches = <ThrowOnError extends boolean = false>(options?: Options<ListBatchesData, ThrowOnError>): RequestResult<ListBatchesResponses, ListBatchesErrors, ThrowOnError> => (options?.client ?? client).get<ListBatchesResponses, ListBatchesErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vListBatchesResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/enrollment-batches',
    ...options
});

export const createBatch = <ThrowOnError extends boolean = false>(options: Options<CreateBatchData, ThrowOnError>): RequestResult<CreateBatchResponses, CreateBatchErrors, ThrowOnError> => (options.client ?? client).post<CreateBatchResponses, CreateBatchErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vCreateBatchBody2,
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vCreateBatchResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/enrollment-batches',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteBatch = <ThrowOnError extends boolean = false>(options: Options<DeleteBatchData, ThrowOnError>): RequestResult<DeleteBatchResponses, DeleteBatchErrors, ThrowOnError> => (options.client ?? client).delete<DeleteBatchResponses, DeleteBatchErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: vDeleteBatchPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vDeleteBatchResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/enrollment-batches/{id}',
    ...options
});

export const getBatch = <ThrowOnError extends boolean = false>(options: Options<GetBatchData, ThrowOnError>): RequestResult<GetBatchResponses, GetBatchErrors, ThrowOnError> => (options.client ?? client).get<GetBatchResponses, GetBatchErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: vGetBatchPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vGetBatchResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/enrollment-batches/{id}',
    ...options
});

export const updateBatch = <ThrowOnError extends boolean = false>(options: Options<UpdateBatchData, ThrowOnError>): RequestResult<UpdateBatchResponses, UpdateBatchErrors, ThrowOnError> => (options.client ?? client).put<UpdateBatchResponses, UpdateBatchErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vUpdateBatchBody2,
        path: vUpdateBatchPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vUpdateBatchResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/enrollment-batches/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const uploadFile = <ThrowOnError extends boolean = false>(options: Options<UploadFileData, ThrowOnError>): RequestResult<UploadFileResponses, UploadFileErrors, ThrowOnError> => (options.client ?? client).post<UploadFileResponses, UploadFileErrors, ThrowOnError>({
    ...formDataBodySerializer,
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vUploadFileBody,
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vUploadFileResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/uploads',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, RegisterErrors, ThrowOnError> => (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vRegisterBody,
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vRegisterResponse, data),
    url: '/api/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vLoginBody,
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vLoginResponse, data),
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const refresh = <ThrowOnError extends boolean = false>(options: Options<RefreshData, ThrowOnError>): RequestResult<RefreshResponses, RefreshErrors, ThrowOnError> => (options.client ?? client).post<RefreshResponses, RefreshErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vRefreshBody,
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vRefreshResponse, data),
    url: '/api/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const logout = <ThrowOnError extends boolean = false>(options: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, LogoutErrors, ThrowOnError> => (options.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vLogoutBody,
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vLogoutResponse, data),
    url: '/api/auth/logout',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const logoutAll = <ThrowOnError extends boolean = false>(options?: Options<LogoutAllData, ThrowOnError>): RequestResult<LogoutAllResponses, LogoutAllErrors, ThrowOnError> => (options?.client ?? client).post<LogoutAllResponses, LogoutAllErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vLogoutAllResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/logout-all',
    ...options
});

export const me = <ThrowOnError extends boolean = false>(options?: Options<MeData, ThrowOnError>): RequestResult<MeResponses, MeErrors, ThrowOnError> => (options?.client ?? client).get<MeResponses, MeErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vMeResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/me',
    ...options
});
