// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { CalculateMarksData, CalculateMarksErrors, CalculateMarksResponses, CreateApplicationData, CreateApplicationErrors, CreateApplicationResponses, CreateBatchData, CreateBatchErrors, CreateBatchResponses, DeleteApplicationData, DeleteApplicationErrors, DeleteApplicationResponses, DeleteBatchData, DeleteBatchErrors, DeleteBatchResponses, GenerateAdmissionListsData, GenerateAdmissionListsErrors, GenerateAdmissionListsResponses, GetApplicationData, GetApplicationErrors, GetApplicationResponses, GetBatchData, GetBatchErrors, GetBatchResponses, GetCounterData, GetCounterErrors, GetCounterResponses, GetSecureCounterData, GetSecureCounterErrors, GetSecureCounterResponses, IncrementCounterData, IncrementCounterErrors, IncrementCounterResponses, IncrementSecureCounterData, IncrementSecureCounterErrors, IncrementSecureCounterResponses, ListApplicationsData, ListApplicationsErrors, ListApplicationsResponses, ListBatchesData, ListBatchesErrors, ListBatchesResponses, LoginData, LoginErrors, LoginResponses, LogoutAllData, LogoutAllErrors, LogoutAllResponses, LogoutData, LogoutErrors, LogoutResponses, MeData, MeErrors, MeResponses, RefreshData, RefreshErrors, RefreshResponses, RegisterData, RegisterErrors, RegisterResponses, SubmitApplicationData, SubmitApplicationErrors, SubmitApplicationResponses, UpdateApplicationData, UpdateApplicationErrors, UpdateApplicationResponses, UpdateBatchData, UpdateBatchErrors, UpdateBatchResponses, UploadFileData, UploadFileErrors, UploadFileResponses } from './types.gen';
import { vCalculateMarksPath, vCalculateMarksResponse, vCreateApplicationBody, vCreateApplicationResponse, vCreateBatchBody2, vCreateBatchResponse, vDeleteApplicationPath, vDeleteApplicationResponse, vDeleteBatchPath, vDeleteBatchResponse, vGenerateAdmissionListsBody, vGenerateAdmissionListsResponse, vGetApplicationPath, vGetApplicationResponse, vGetBatchPath, vGetBatchResponse, vGetCounterPath, vGetCounterResponse, vGetSecureCounterPath, vGetSecureCounterResponse, vIncrementCounterPath, vIncrementCounterResponse, vIncrementSecureCounterPath, vIncrementSecureCounterResponse, vListApplicationsQuery, vListApplicationsResponse, vListBatchesResponse, vLoginBody, vLoginResponse, vLogoutAllResponse, vLogoutBody, vLogoutResponse, vMeResponse, vRefreshBody, vRefreshResponse, vRegisterBody, vRegisterResponse, vSubmitApplicationPath, vSubmitApplicationResponse, vUpdateApplicationBody, vUpdateApplicationPath, vUpdateApplicationResponse, vUpdateBatchBody2, vUpdateBatchPath, vUpdateBatchResponse, vUploadFileBody, vUploadFileResponse } from './valibot.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getCounter = <ThrowOnError extends boolean = false>(options: Options<GetCounterData, ThrowOnError>): RequestResult<GetCounterResponses, GetCounterErrors, ThrowOnError> => (options.client ?? client).get<GetCounterResponses, GetCounterErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: vGetCounterPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vGetCounterResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/counter/{name}',
    ...options
});

export const incrementCounter = <ThrowOnError extends boolean = false>(options: Options<IncrementCounterData, ThrowOnError>): RequestResult<IncrementCounterResponses, IncrementCounterErrors, ThrowOnError> => (options.client ?? client).post<IncrementCounterResponses, IncrementCounterErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: vIncrementCounterPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vIncrementCounterResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/counter/{name}/increment',
    ...options
});

export const getSecureCounter = <ThrowOnError extends boolean = false>(options: Options<GetSecureCounterData, ThrowOnError>): RequestResult<GetSecureCounterResponses, GetSecureCounterErrors, ThrowOnError> => (options.client ?? client).get<GetSecureCounterResponses, GetSecureCounterErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: vGetSecureCounterPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vGetSecureCounterResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/counter/secure/{name}',
    ...options
});

export const incrementSecureCounter = <ThrowOnError extends boolean = false>(options: Options<IncrementSecureCounterData, ThrowOnError>): RequestResult<IncrementSecureCounterResponses, IncrementSecureCounterErrors, ThrowOnError> => (options.client ?? client).post<IncrementSecureCounterResponses, IncrementSecureCounterErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: vIncrementSecureCounterPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vIncrementSecureCounterResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/counter/secure/{name}/increment',
    ...options
});

export const listApplications = <ThrowOnError extends boolean = false>(options?: Options<ListApplicationsData, ThrowOnError>): RequestResult<ListApplicationsResponses, ListApplicationsErrors, ThrowOnError> => (options?.client ?? client).get<ListApplicationsResponses, ListApplicationsErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: v.optional(v.never()),
        query: v.optional(vListApplicationsQuery)
    }), data),
    responseValidator: async (data) => await v.parseAsync(vListApplicationsResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/g1-applications',
    ...options
});

export const createApplication = <ThrowOnError extends boolean = false>(options: Options<CreateApplicationData, ThrowOnError>): RequestResult<CreateApplicationResponses, CreateApplicationErrors, ThrowOnError> => (options.client ?? client).post<CreateApplicationResponses, CreateApplicationErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vCreateApplicationBody,
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vCreateApplicationResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/g1-applications',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteApplication = <ThrowOnError extends boolean = false>(options: Options<DeleteApplicationData, ThrowOnError>): RequestResult<DeleteApplicationResponses, DeleteApplicationErrors, ThrowOnError> => (options.client ?? client).delete<DeleteApplicationResponses, DeleteApplicationErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: vDeleteApplicationPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vDeleteApplicationResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/g1-applications/{id}',
    ...options
});

export const getApplication = <ThrowOnError extends boolean = false>(options: Options<GetApplicationData, ThrowOnError>): RequestResult<GetApplicationResponses, GetApplicationErrors, ThrowOnError> => (options.client ?? client).get<GetApplicationResponses, GetApplicationErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: vGetApplicationPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vGetApplicationResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/g1-applications/{id}',
    ...options
});

export const updateApplication = <ThrowOnError extends boolean = false>(options: Options<UpdateApplicationData, ThrowOnError>): RequestResult<UpdateApplicationResponses, UpdateApplicationErrors, ThrowOnError> => (options.client ?? client).put<UpdateApplicationResponses, UpdateApplicationErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vUpdateApplicationBody,
        path: vUpdateApplicationPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vUpdateApplicationResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/g1-applications/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const submitApplication = <ThrowOnError extends boolean = false>(options: Options<SubmitApplicationData, ThrowOnError>): RequestResult<SubmitApplicationResponses, SubmitApplicationErrors, ThrowOnError> => (options.client ?? client).post<SubmitApplicationResponses, SubmitApplicationErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: vSubmitApplicationPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vSubmitApplicationResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/g1-applications/{id}/submit',
    ...options
});

export const calculateMarks = <ThrowOnError extends boolean = false>(options: Options<CalculateMarksData, ThrowOnError>): RequestResult<CalculateMarksResponses, CalculateMarksErrors, ThrowOnError> => (options.client ?? client).post<CalculateMarksResponses, CalculateMarksErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: vCalculateMarksPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vCalculateMarksResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/g1-applications/{id}/calculate-marks',
    ...options
});

export const generateAdmissionLists = <ThrowOnError extends boolean = false>(options: Options<GenerateAdmissionListsData, ThrowOnError>): RequestResult<GenerateAdmissionListsResponses, GenerateAdmissionListsErrors, ThrowOnError> => (options.client ?? client).post<GenerateAdmissionListsResponses, GenerateAdmissionListsErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vGenerateAdmissionListsBody,
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vGenerateAdmissionListsResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/g1-applications/generate-lists',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const listBatches = <ThrowOnError extends boolean = false>(options?: Options<ListBatchesData, ThrowOnError>): RequestResult<ListBatchesResponses, ListBatchesErrors, ThrowOnError> => (options?.client ?? client).get<ListBatchesResponses, ListBatchesErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vListBatchesResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/enrollment-batches',
    ...options
});

export const createBatch = <ThrowOnError extends boolean = false>(options: Options<CreateBatchData, ThrowOnError>): RequestResult<CreateBatchResponses, CreateBatchErrors, ThrowOnError> => (options.client ?? client).post<CreateBatchResponses, CreateBatchErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vCreateBatchBody2,
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vCreateBatchResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/enrollment-batches',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteBatch = <ThrowOnError extends boolean = false>(options: Options<DeleteBatchData, ThrowOnError>): RequestResult<DeleteBatchResponses, DeleteBatchErrors, ThrowOnError> => (options.client ?? client).delete<DeleteBatchResponses, DeleteBatchErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: vDeleteBatchPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vDeleteBatchResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/enrollment-batches/{id}',
    ...options
});

export const getBatch = <ThrowOnError extends boolean = false>(options: Options<GetBatchData, ThrowOnError>): RequestResult<GetBatchResponses, GetBatchErrors, ThrowOnError> => (options.client ?? client).get<GetBatchResponses, GetBatchErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: vGetBatchPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vGetBatchResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/enrollment-batches/{id}',
    ...options
});

export const updateBatch = <ThrowOnError extends boolean = false>(options: Options<UpdateBatchData, ThrowOnError>): RequestResult<UpdateBatchResponses, UpdateBatchErrors, ThrowOnError> => (options.client ?? client).put<UpdateBatchResponses, UpdateBatchErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vUpdateBatchBody2,
        path: vUpdateBatchPath,
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vUpdateBatchResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/enrollment-batches/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const uploadFile = <ThrowOnError extends boolean = false>(options: Options<UploadFileData, ThrowOnError>): RequestResult<UploadFileResponses, UploadFileErrors, ThrowOnError> => (options.client ?? client).post<UploadFileResponses, UploadFileErrors, ThrowOnError>({
    ...formDataBodySerializer,
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vUploadFileBody,
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vUploadFileResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/uploads',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, RegisterErrors, ThrowOnError> => (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vRegisterBody,
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vRegisterResponse, data),
    url: '/api/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vLoginBody,
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vLoginResponse, data),
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const refresh = <ThrowOnError extends boolean = false>(options: Options<RefreshData, ThrowOnError>): RequestResult<RefreshResponses, RefreshErrors, ThrowOnError> => (options.client ?? client).post<RefreshResponses, RefreshErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vRefreshBody,
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vRefreshResponse, data),
    url: '/api/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const logout = <ThrowOnError extends boolean = false>(options: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, LogoutErrors, ThrowOnError> => (options.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: vLogoutBody,
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vLogoutResponse, data),
    url: '/api/auth/logout',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const logoutAll = <ThrowOnError extends boolean = false>(options?: Options<LogoutAllData, ThrowOnError>): RequestResult<LogoutAllResponses, LogoutAllErrors, ThrowOnError> => (options?.client ?? client).post<LogoutAllResponses, LogoutAllErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vLogoutAllResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/logout-all',
    ...options
});

export const me = <ThrowOnError extends boolean = false>(options?: Options<MeData, ThrowOnError>): RequestResult<MeResponses, MeErrors, ThrowOnError> => (options?.client ?? client).get<MeResponses, MeErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(v.object({
        body: v.optional(v.never()),
        path: v.optional(v.never()),
        query: v.optional(v.never())
    }), data),
    responseValidator: async (data) => await v.parseAsync(vMeResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/me',
    ...options
});
