// This file is auto-generated by @hey-api/openapi-ts

import type { LoginResponse, RefreshResponse, RegisterResponse } from './types.gen';

export const registerResponseTransformer = async (data: any): Promise<RegisterResponse> => {
    data.expires_at = BigInt(data.expires_at.toString());
    return data;
};

const authResponseSchemaResponseTransformer = (data: any) => {
    data.expires_at = BigInt(data.expires_at.toString());
    return data;
};

export const loginResponseTransformer = async (data: any): Promise<LoginResponse> => {
    data = authResponseSchemaResponseTransformer(data);
    return data;
};

export const refreshResponseTransformer = async (data: any): Promise<RefreshResponse> => {
    data = authResponseSchemaResponseTransformer(data);
    return data;
};
