// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * Address
 */
export type Address = {
    address_line_1: string;
    address_line_2?: string | null;
    city: string;
    created_at?: string;
    distance_to_school_km?: string | null;
    district: string;
    gs_division: string;
    id: string;
    latitude?: string | null;
    longitude?: string | null;
    ownership_proof?: string | null;
    postal_code?: string | null;
    province: string;
    residence_type?: ResidenceType | null;
    verified_by_map: boolean;
};

export type AddressEntry = {
    address_id: string;
    address_type: string;
    is_primary: boolean;
    residence_type: string;
};

export type AddressEntryResponse = {
    address_id: string;
    address_type: string;
    is_primary: boolean;
    residence_type: string;
};

export type ApplicationListCategory = 'Main' | 'Waiting' | 'NotSelected';

export type ApplicationWithChild = {
    age_eligibility_verified: boolean;
    alternative_age_certificate: boolean;
    alternative_age_certificate_ref?: string | null;
    batch_id: string;
    birth_certificate_verified: boolean;
    category?: G1Category | null;
    category_verified: boolean;
    child_birth_certificate_number?: string | null;
    child_date_of_birth?: string | null;
    child_full_name?: string | null;
    child_gender?: Gender | null;
    child_id: string;
    child_medium_of_instruction?: MediumOfInstruction | null;
    child_name_with_initials?: string | null;
    child_nationality?: Nationality | null;
    child_religion?: Religion | null;
    created_at: string;
    created_by?: string | null;
    deleted_at?: string | null;
    enrollment_status: EnrollmentStatus;
    finalized_at?: string | null;
    guardian_id: string;
    id: string;
    interview_completed: boolean;
    interview_date?: string | null;
    ip_address?: string | null;
    list_category?: ApplicationListCategory | null;
    overseas_arrival_date?: string | null;
    promoted_at?: string | null;
    rank_number?: number | null;
    reference_no: string;
    rejection_reason?: string | null;
    residence_verified: boolean;
    school_id?: string | null;
    submission_method?: string | null;
    submitted_at?: string | null;
    total_marks?: string | null;
    updated_at: string;
    updated_by?: string | null;
    user_agent?: string | null;
    verified_at?: string | null;
    verified_by?: string | null;
    waiting_position?: number | null;
    wizard_step?: number | null;
};

/**
 * AuthResponse
 */
export type AuthResponse = {
    access_token: string;
    expires_at: bigint;
    refresh_token: string;
};

export type BatchStatus = 'Open' | 'Closed' | 'ListsPublished' | 'AppealsPeriod' | 'Archived';

/**
 * Blacklist
 */
export type Blacklist = {
    application_id?: string | null;
    blacklisted_at?: string;
    blacklisted_by?: string | null;
    evidence_url?: string | null;
    expires_at?: string;
    guardian_id: string;
    id?: string;
    reason: string;
    status?: string;
};

/**
 * Child
 */
export type Child = {
    birth_certificate_number?: string | null;
    created_at?: string;
    date_of_birth: string;
    disability_status?: boolean;
    disability_type?: string | null;
    full_name: string;
    gender: Gender;
    id: string;
    medium_of_instruction: MediumOfInstruction;
    name_with_initials: string;
    name_with_initials_en?: string | null;
    nationality: Nationality;
    /**
     * National Identity Card number (for older children)
     */
    nic?: string | null;
    /**
     * Passport number (for overseas arrivals)
     */
    passport_number?: string | null;
    photo_url?: string | null;
    religion?: Religion | null;
    student_id?: string | null;
};

/**
 * CounterResponse
 */
export type CounterResponse = {
    name: string;
    value: number;
};

/**
 * CreateAddressBody
 */
export type CreateAddressBody = {
    address_line_1: string;
    address_line_2?: string | null;
    city: string;
    distance_to_school_km?: number | null;
    district: string;
    gs_division: string;
    latitude?: number | null;
    longitude?: number | null;
    ownership_proof?: string | null;
    postal_code?: string | null;
    province: string;
    residence_type?: string | null;
    verified_by_map?: boolean | null;
};

/**
 * CreateApplicationBody
 */
export type CreateApplicationBody = {
    batch_id: string;
    child_id?: string | null;
    preferred_school_ids?: Array<string> | null;
    school_id?: string | null;
};

/**
 * CreateBatchBody
 */
export type CreateBatchBody = {
    alumni_percentage?: number | null;
    buddhism_percentage?: number | null;
    catholicism_percentage?: number | null;
    enrollment_type: EnrollmentType;
    govt_percentage?: number | null;
    hinduism_percentage?: number | null;
    islam_percentage?: number | null;
    proximity_percentage?: number | null;
    sibling_percentage?: number | null;
    special_percentage?: number | null;
    staff_percentage?: number | null;
    student_allocation?: number | null;
    year: number;
};

/**
 * CreateChildBody
 */
export type CreateChildBody = {
    birth_certificate_number?: string | null;
    date_of_birth: string;
    disability_status?: boolean | null;
    disability_type?: string | null;
    full_name: string;
    gender: Gender;
    medium_of_instruction: MediumOfInstruction;
    name_with_initials: string;
    nationality: Nationality;
    /**
     * National Identity Card number (for older children)
     */
    nic?: string | null;
    /**
     * Passport number (for overseas arrivals)
     */
    passport_number?: string | null;
    photo_url?: string | null;
    religion?: Religion | null;
};

/**
 * CreateGuardianBody
 */
export type CreateGuardianBody = {
    contact_email?: string | null;
    contact_phone: string;
    employee_id?: string | null;
    full_name: string;
    govt_service_years?: number | null;
    income_level?: IncomeLevel | null;
    is_govt_employee: boolean;
    is_past_pupil: boolean;
    is_school_staff: boolean;
    nic_number: string;
    occupation?: string | null;
    past_pupil_highest_grade?: string | null;
    past_pupil_left_reason?: string | null;
    past_pupil_school_id?: string | null;
    past_pupil_student_id?: string | null;
    past_pupil_year_left?: number | null;
    relationship_type: string;
    staff_school_id?: string | null;
    staff_type?: StaffType | null;
    workplace_address?: string | null;
    workplace_name?: string | null;
};

/**
 * CreatePastPupilDetailBody
 */
export type CreatePastPupilDetailBody = {
    guardian_id: string;
    highest_grade?: string | null;
    left_reason?: string | null;
    school_id: string;
    student_id?: string | null;
    verification_method?: string | null;
    year_left?: number | null;
};

/**
 * CreateSiblingRequest
 */
export type CreateSiblingRequest = {
    birth_certificate_number?: string | null;
    current_grade?: number | null;
    date_of_birth: string;
    email?: string | null;
    full_name: string;
    gender: Gender;
    medium_of_instruction: MediumOfInstruction;
    name_with_initials: string;
    nationality: Nationality;
    nic?: string | null;
    passport_number?: string | null;
    phone?: string | null;
    religion?: Religion | null;
    school_id?: string | null;
};

/**
 * CreateSiblingResponse
 */
export type CreateSiblingResponse = {
    created: boolean;
    duplicates: Array<StudentDuplicate>;
    student_id?: string | null;
};

/**
 * CreateStaffDetailBody
 */
export type CreateStaffDetailBody = {
    designation?: string | null;
    employee_id?: string | null;
    guardian_id: string;
    school_id: string;
    staff_type?: StaffType | null;
};

/**
 * CreateWorkspaceAddressBody
 */
export type CreateWorkspaceAddressBody = {
    building?: string | null;
    city: string;
    country: string;
    name: string;
    postal_code?: string | null;
    state?: string | null;
    street_1: string;
    street_2?: string | null;
};

/**
 * District
 */
export type District = {
    id: string;
    name_en: string;
    name_si: string;
    province: string;
};

export type DocumentEntry = {
    content_type?: string | null;
    doc_type: string;
    file_key: string;
    file_name?: string | null;
    file_size?: bigint | null;
    file_url: string;
};

export type ElectoralDistrict = 'Colombo' | 'Gampaha' | 'Kalutara' | 'Kandy' | 'Matale' | 'NuwaraEliya' | 'Galle' | 'Matara' | 'Hambantota' | 'Jaffna' | 'Vanni' | 'Batticaloa' | 'Ampara' | 'Trincomalee' | 'Kurunegala' | 'Puttalam' | 'Anuradhapura' | 'Polonnaruwa' | 'Badulla' | 'Monaragala' | 'Ratnapura' | 'Kegalle';

/**
 * EnrollmentBatch
 */
export type EnrollmentBatch = {
    alumni_percentage?: number;
    appeal_deadline_at?: string | null;
    /**
     * Machine-readable code (e.g., "G1-2026")
     */
    batch_code: string;
    /**
     * Human-readable name (e.g., "Grade 1 Admission 2026")
     */
    batch_name: string;
    buddhism_percentage?: number;
    catholicism_percentage?: number;
    closed_at?: string;
    created_at?: string;
    created_by?: string | null;
    enrollment_type: EnrollmentType;
    finalized_at?: string | null;
    govt_percentage?: number;
    hinduism_percentage?: number;
    id?: string;
    islam_percentage?: number;
    list_published_at?: string | null;
    opened_at?: string;
    proximity_percentage?: number;
    sibling_percentage?: number;
    special_percentage?: number;
    staff_percentage?: number;
    status?: BatchStatus;
    student_allocation?: number;
    waiting_list_size?: number;
    year: number;
};

export type EnrollmentStatus = 'Draft' | 'Pending' | 'Completed' | 'PendingApproval' | 'Approved' | 'Admitted' | 'Rejected' | 'Withdrawn';

export type EnrollmentType = 'G1';

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    error: string;
};

/**
 * G1Application
 */
export type G1Application = {
    age_eligibility_verified: boolean;
    alternative_age_certificate: boolean;
    alternative_age_certificate_ref?: string | null;
    batch_id: string;
    birth_certificate_verified: boolean;
    category?: G1Category | null;
    category_verified: boolean;
    child_id?: string;
    closer_school_exists?: boolean | null;
    created_at?: string;
    created_by?: string | null;
    declaration_agreed: boolean;
    declaration_signed_at?: string | null;
    deleted_at?: string | null;
    electoral_year?: number | null;
    enrollment_status?: EnrollmentStatus;
    finalized_at?: string | null;
    gn_name?: string | null;
    gn_number?: string | null;
    guardian_id?: string;
    household_head_name?: string | null;
    id?: string;
    interview_completed: boolean;
    interview_date?: string | null;
    ip_address?: string | null;
    list_category?: ApplicationListCategory | null;
    overseas_arrival_date?: string | null;
    polling_area?: string | null;
    polling_district?: ElectoralDistrict | null;
    polling_division?: string | null;
    preferred_school_ids?: unknown;
    promoted_at?: string | null;
    rank_number?: number | null;
    reference_no?: string;
    rejection_reason?: string | null;
    residence_verified: boolean;
    school_id?: string | null;
    submission_method?: string | null;
    submitted_at?: string | null;
    total_marks?: string | null;
    updated_at?: string;
    updated_by?: string | null;
    user_agent?: string | null;
    verified_at?: string | null;
    verified_by?: string | null;
    village_street?: string | null;
    voter_names?: unknown;
    waiting_position?: number | null;
    wizard_step?: number | null;
};

export type G1Category = 'CloseResident' | 'PastPupilChild' | 'Sibling' | 'MOEOrUGCStaffChild' | 'GovernmentTransferOfficerChild' | 'OverseasArrival' | 'ArmedForcesReserved' | 'SpecialNeeds' | 'LowIncome';

export type Gender = 'Male' | 'Female';

/**
 * GetApplicationAddressesResponse
 */
export type GetApplicationAddressesResponse = {
    addresses: Array<AddressEntryResponse>;
};

/**
 * GetApplicationGuardiansResponse
 */
export type GetApplicationGuardiansResponse = {
    guardian_ids: Array<string>;
};

/**
 * GetApplicationSiblingsResponse
 */
export type GetApplicationSiblingsResponse = {
    sibling_ids: Array<string>;
};

/**
 * GetDocumentsResponse
 */
export type GetDocumentsResponse = {
    documents: Array<DocumentEntry>;
};

/**
 * GnDivisionEntry
 */
export type GnDivisionEntry = {
    id: string;
    lat: number;
    lon: number;
    name_en: string;
    name_local: string;
    parent_id: string;
    parent_name_en: string;
    parent_name_local: string;
    postal_code: string;
    slug: string;
};

/**
 * Guardian
 */
export type Guardian = {
    address_id?: string | null;
    contact_email?: string | null;
    contact_phone: string;
    created_at?: string;
    full_name: string;
    govt_service_years?: number | null;
    id: string;
    income_level?: IncomeLevel | null;
    is_govt_employee: boolean;
    is_past_pupil: boolean;
    is_school_staff: boolean;
    is_sri_lankan_citizen?: boolean | null;
    nic_number: string;
    occupation?: string | null;
    past_pupil_verified: boolean;
    relationship_type: string;
    workplace_address?: string | null;
    workplace_name?: string | null;
};

export type IncomeLevel = 'below_25000' | '25000_50000' | '50000_100000' | '100000_200000' | '200000_500000' | 'above_500000';

/**
 * LoginRequest
 */
export type LoginRequest = {
    email: string;
    password: string;
};

export type MediumOfInstruction = 'Sinhala' | 'Tamil';

/**
 * MessageResponse
 */
export type MessageResponse = {
    message: string;
};

/**
 * Model
 */
export type Model = {
    created_at?: string;
    guardian_id: string;
    highest_grade?: string | null;
    id: string;
    left_reason?: string | null;
    school_id: string;
    student_id?: string | null;
    verification_method?: string | null;
    verified: boolean;
    year_left?: number | null;
};

export type Nationality = 'SriLankan' | 'DualCitizen' | 'Other';

/**
 * PaginatedApplicationsResponse
 */
export type PaginatedApplicationsResponse = {
    items: Array<ApplicationWithChild>;
    total: number;
};

/**
 * PollingDivisionEntry
 */
export type PollingDivisionEntry = {
    district: string;
    label: string;
    si: string;
    value: string;
};

/**
 * PresignedUploadRequest
 */
export type PresignedUploadRequest = {
    content_type: string;
    file_name: string;
    file_size: bigint;
};

/**
 * PresignedUploadResponse
 */
export type PresignedUploadResponse = {
    content_type: string;
    file_name: string;
    file_size: bigint;
    key: string;
    public_url: string;
    url: string;
};

/**
 * RefreshRequest
 */
export type RefreshRequest = {
    refresh_token: string;
};

/**
 * RegisterRequest
 */
export type RegisterRequest = {
    email: string;
    password: string;
};

export type Religion = 'Buddhism' | 'Hinduism' | 'Islam' | 'Christianity' | 'Catholicism' | 'Other';

export type ResidenceType = 'Owned' | 'Rented' | 'Relative' | 'Other';

/**
 * SaveAddressesRequest
 */
export type SaveAddressesRequest = {
    addresses: Array<AddressEntry>;
};

/**
 * SaveAddressesResponse
 */
export type SaveAddressesResponse = {
    count: number;
};

export type SaveDocumentEntry = {
    content_type?: string | null;
    doc_type: string;
    file_key: string;
    file_size?: bigint | null;
    file_url: string;
};

/**
 * SaveDocumentsRequest
 */
export type SaveDocumentsRequest = {
    documents: Array<SaveDocumentEntry>;
};

/**
 * SaveDocumentsResponse
 */
export type SaveDocumentsResponse = {
    count: number;
};

/**
 * SaveGuardiansRequest
 */
export type SaveGuardiansRequest = {
    guardian_ids: Array<string>;
};

/**
 * SaveGuardiansResponse
 */
export type SaveGuardiansResponse = {
    count: number;
};

/**
 * SaveSiblingsRequest
 */
export type SaveSiblingsRequest = {
    student_ids: Array<string>;
};

/**
 * SaveSiblingsResponse
 */
export type SaveSiblingsResponse = {
    count: number;
};

/**
 * SaveStepRequest
 */
export type SaveStepRequest = {
    wizard_step: number;
};

/**
 * SaveStepResponse
 */
export type SaveStepResponse = {
    wizard_step: number;
};

/**
 * SchoolSummary
 */
export type SchoolSummary = {
    district_id?: string | null;
    id: string;
    name_en?: string | null;
    name_si: string;
};

/**
 * StaffDetail
 */
export type StaffDetail = {
    created_at?: string;
    designation?: string | null;
    distance_from_residence_km?: string | null;
    employee_id?: string | null;
    employment_type?: StaffEmploymentType | null;
    guardian_id: string;
    id: string;
    is_current: boolean;
    school_id: string;
    service_end_date?: string | null;
    service_start_date?: string | null;
    staff_type?: StaffType | null;
    verification_doc?: string | null;
};

export type StaffEmploymentType = 'Permanent' | 'Temporary' | 'Contract';

export type StaffType = 'Teacher' | 'Admin' | 'Worker';

/**
 * Student
 */
export type Student = {
    admission_date?: string | null;
    admission_number?: string | null;
    birth_certificate_number?: string | null;
    child_id: string;
    created_at: string;
    created_by?: string | null;
    /**
     * Integer representing the grade (e.g., 1 for Grade 1)
     */
    current_grade?: number | null;
    /**
     * Format: YYYY-MM-DD
     */
    date_of_birth: string;
    email?: string | null;
    full_name: string;
    gender: Gender;
    id: string;
    medium_of_instruction: MediumOfInstruction;
    name_with_initials: string;
    nationality: Nationality;
    nic?: string | null;
    passport_number?: string | null;
    /**
     * E.164 format recommended
     */
    phone?: string | null;
    religion?: Religion | null;
    status: StudentStatus;
    updated_at: string;
    updated_by?: string | null;
};

export type StudentDuplicate = {
    birth_certificate_number?: string | null;
    current_grade?: number | null;
    date_of_birth: string;
    full_name: string;
    gender: Gender;
    id: string;
    medium_of_instruction: MediumOfInstruction;
    name_with_initials: string;
    nationality: Nationality;
    nic?: string | null;
};

export type StudentStatus = 'Active' | 'Graduated' | 'Removed';

/**
 * UpdateApplicationBody
 */
export type UpdateApplicationBody = {
    age_eligibility_verified?: boolean | null;
    alternative_age_certificate?: boolean | null;
    alternative_age_certificate_ref?: string | null;
    birth_certificate_verified?: boolean | null;
    category?: G1Category | null;
    category_verified?: boolean | null;
    child_id?: string | null;
    closer_school_exists?: boolean | null;
    declaration_agreed?: boolean | null;
    electoral_year?: number | null;
    gn_name?: string | null;
    gn_number?: string | null;
    guardian_id?: string | null;
    household_head_name?: string | null;
    interview_completed?: boolean | null;
    interview_date?: string | null;
    overseas_arrival_date?: string | null;
    polling_area?: string | null;
    polling_district?: ElectoralDistrict | null;
    polling_division?: string | null;
    preferred_school_ids?: unknown;
    rejection_reason?: string | null;
    residence_verified?: boolean | null;
    school_id?: string | null;
    submission_method?: string | null;
    village_street?: string | null;
    voter_names?: unknown;
    wizard_step?: number | null;
};

/**
 * UpdateBatchBody
 */
export type UpdateBatchBody = {
    alumni_percentage?: number | null;
    buddhism_percentage?: number | null;
    catholicism_percentage?: number | null;
    govt_percentage?: number | null;
    hinduism_percentage?: number | null;
    islam_percentage?: number | null;
    proximity_percentage?: number | null;
    sibling_percentage?: number | null;
    special_percentage?: number | null;
    staff_percentage?: number | null;
    status?: BatchStatus | null;
    student_allocation?: number | null;
};

/**
 * UpdateChildBody
 */
export type UpdateChildBody = {
    birth_certificate_number?: string | null;
    date_of_birth?: string | null;
    disability_status?: boolean | null;
    disability_type?: string | null;
    full_name?: string | null;
    gender?: Gender | null;
    medium_of_instruction?: MediumOfInstruction | null;
    name_with_initials?: string | null;
    nationality?: Nationality | null;
    /**
     * National Identity Card number (for older children)
     */
    nic?: string | null;
    /**
     * Passport number (for overseas arrivals)
     */
    passport_number?: string | null;
    photo_url?: string | null;
    religion?: Religion | null;
};

/**
 * UpdateGuardianBody
 */
export type UpdateGuardianBody = {
    address_id?: string | null;
    contact_email?: string | null;
    contact_phone: string;
    employee_id?: string | null;
    full_name: string;
    govt_service_years?: number | null;
    income_level?: IncomeLevel | null;
    is_govt_employee: boolean;
    is_past_pupil: boolean;
    is_school_staff: boolean;
    nic_number: string;
    occupation?: string | null;
    past_pupil_highest_grade?: string | null;
    past_pupil_left_reason?: string | null;
    past_pupil_school_id?: string | null;
    past_pupil_student_id?: string | null;
    past_pupil_year_left?: number | null;
    relationship_type: string;
    staff_school_id?: string | null;
    staff_type?: StaffType | null;
    workplace_address?: string | null;
    workplace_name?: string | null;
};

/**
 * UpdateStudentRequest
 */
export type UpdateStudentRequest = {
    birth_certificate_number?: string | null;
    current_grade?: number | null;
    date_of_birth: string;
    email?: string | null;
    full_name: string;
    gender: Gender;
    medium_of_instruction: MediumOfInstruction;
    name_with_initials: string;
    nationality: Nationality;
    nic?: string | null;
    passport_number?: string | null;
    phone?: string | null;
    religion?: Religion | null;
};

/**
 * UploadForm
 */
export type UploadForm = {
    [key: string]: unknown;
};

/**
 * UploadResponse
 */
export type UploadResponse = {
    file_name: string;
    key: string;
    size: number;
    url: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
    email: string;
    id: string;
    role: string;
};

/**
 * WorkspaceAddress
 */
export type WorkspaceAddress = {
    building?: string | null;
    city: string;
    country: string;
    created_at?: string;
    full_address: string;
    id: string;
    name: string;
    postal_code?: string | null;
    state?: string | null;
    street_1: string;
    street_2?: string | null;
};

export type ListBlacklistData = {
    body?: never;
    path?: never;
    query?: {
        guardian_ids?: Array<string> | null;
    };
    url: '/api/blacklist';
};

export type ListBlacklistErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ListBlacklistError = ListBlacklistErrors[keyof ListBlacklistErrors];

export type ListBlacklistResponses = {
    200: Array<Blacklist>;
};

export type ListBlacklistResponse = ListBlacklistResponses[keyof ListBlacklistResponses];

export type ListChildrenData = {
    body?: never;
    path?: never;
    query?: {
        birth_certificate_number?: string | null;
        full_name?: string | null;
        nic?: string | null;
        search?: string | null;
    };
    url: '/api/children';
};

export type ListChildrenErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ListChildrenError = ListChildrenErrors[keyof ListChildrenErrors];

export type ListChildrenResponses = {
    200: Array<Child>;
};

export type ListChildrenResponse = ListChildrenResponses[keyof ListChildrenResponses];

export type CreateChildData = {
    body: CreateChildBody;
    path?: never;
    query?: never;
    url: '/api/children';
};

export type CreateChildErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type CreateChildError = CreateChildErrors[keyof CreateChildErrors];

export type CreateChildResponses = {
    /**
     * Child
     */
    201: {
        birth_certificate_number?: string | null;
        created_at?: string;
        date_of_birth: string;
        disability_status?: boolean;
        disability_type?: string | null;
        full_name: string;
        gender: Gender;
        id: string;
        medium_of_instruction: MediumOfInstruction;
        name_with_initials: string;
        name_with_initials_en?: string | null;
        nationality: Nationality;
        /**
         * National Identity Card number (for older children)
         */
        nic?: string | null;
        /**
         * Passport number (for overseas arrivals)
         */
        passport_number?: string | null;
        photo_url?: string | null;
        religion?: Religion | null;
        student_id?: string | null;
    };
};

export type CreateChildResponse = CreateChildResponses[keyof CreateChildResponses];

export type GetChildData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/children/{id}';
};

export type GetChildErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetChildError = GetChildErrors[keyof GetChildErrors];

export type GetChildResponses = {
    200: Child;
};

export type GetChildResponse = GetChildResponses[keyof GetChildResponses];

export type UpdateChildData = {
    body: UpdateChildBody;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/children/{id}';
};

export type UpdateChildErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type UpdateChildError = UpdateChildErrors[keyof UpdateChildErrors];

export type UpdateChildResponses = {
    200: Child;
};

export type UpdateChildResponse = UpdateChildResponses[keyof UpdateChildResponses];

export type GetCounterData = {
    body?: never;
    path: {
        /**
         * String
         */
        name: string;
    };
    query?: never;
    url: '/api/counter/{name}';
};

export type GetCounterErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetCounterError = GetCounterErrors[keyof GetCounterErrors];

export type GetCounterResponses = {
    200: CounterResponse;
};

export type GetCounterResponse = GetCounterResponses[keyof GetCounterResponses];

export type IncrementCounterData = {
    body?: never;
    path: {
        /**
         * String
         */
        name: string;
    };
    query?: never;
    url: '/api/counter/{name}/increment';
};

export type IncrementCounterErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type IncrementCounterError = IncrementCounterErrors[keyof IncrementCounterErrors];

export type IncrementCounterResponses = {
    200: CounterResponse;
};

export type IncrementCounterResponse = IncrementCounterResponses[keyof IncrementCounterResponses];

export type GetSecureCounterData = {
    body?: never;
    path: {
        /**
         * String
         */
        name: string;
    };
    query?: never;
    url: '/api/counter/secure/{name}';
};

export type GetSecureCounterErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetSecureCounterError = GetSecureCounterErrors[keyof GetSecureCounterErrors];

export type GetSecureCounterResponses = {
    200: CounterResponse;
};

export type GetSecureCounterResponse = GetSecureCounterResponses[keyof GetSecureCounterResponses];

export type IncrementSecureCounterData = {
    body?: never;
    path: {
        /**
         * String
         */
        name: string;
    };
    query?: never;
    url: '/api/counter/secure/{name}/increment';
};

export type IncrementSecureCounterErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type IncrementSecureCounterError = IncrementSecureCounterErrors[keyof IncrementSecureCounterErrors];

export type IncrementSecureCounterResponses = {
    200: CounterResponse;
};

export type IncrementSecureCounterResponse = IncrementSecureCounterResponses[keyof IncrementSecureCounterResponses];

export type ListDistrictsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/districts';
};

export type ListDistrictsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ListDistrictsError = ListDistrictsErrors[keyof ListDistrictsErrors];

export type ListDistrictsResponses = {
    200: Array<District>;
};

export type ListDistrictsResponse = ListDistrictsResponses[keyof ListDistrictsResponses];

export type ListApplicationsData = {
    body?: never;
    path?: never;
    query?: {
        batch_id?: string | null;
        category?: string | null;
        enrollment_status?: string | null;
        page?: number | null;
        page_size?: number | null;
        sort_by?: string | null;
        sort_order?: string | null;
    };
    url: '/api/g1-applications';
};

export type ListApplicationsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ListApplicationsError = ListApplicationsErrors[keyof ListApplicationsErrors];

export type ListApplicationsResponses = {
    200: PaginatedApplicationsResponse;
};

export type ListApplicationsResponse = ListApplicationsResponses[keyof ListApplicationsResponses];

export type CreateApplicationData = {
    body: CreateApplicationBody;
    path?: never;
    query?: never;
    url: '/api/g1-applications';
};

export type CreateApplicationErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type CreateApplicationError = CreateApplicationErrors[keyof CreateApplicationErrors];

export type CreateApplicationResponses = {
    /**
     * G1Application
     */
    201: {
        age_eligibility_verified: boolean;
        alternative_age_certificate: boolean;
        alternative_age_certificate_ref?: string | null;
        batch_id: string;
        birth_certificate_verified: boolean;
        category?: G1Category | null;
        category_verified: boolean;
        child_id?: string;
        closer_school_exists?: boolean | null;
        created_at?: string;
        created_by?: string | null;
        declaration_agreed: boolean;
        declaration_signed_at?: string | null;
        deleted_at?: string | null;
        electoral_year?: number | null;
        enrollment_status?: EnrollmentStatus;
        finalized_at?: string | null;
        gn_name?: string | null;
        gn_number?: string | null;
        guardian_id?: string;
        household_head_name?: string | null;
        id?: string;
        interview_completed: boolean;
        interview_date?: string | null;
        ip_address?: string | null;
        list_category?: ApplicationListCategory | null;
        overseas_arrival_date?: string | null;
        polling_area?: string | null;
        polling_district?: ElectoralDistrict | null;
        polling_division?: string | null;
        preferred_school_ids?: unknown;
        promoted_at?: string | null;
        rank_number?: number | null;
        reference_no?: string;
        rejection_reason?: string | null;
        residence_verified: boolean;
        school_id?: string | null;
        submission_method?: string | null;
        submitted_at?: string | null;
        total_marks?: string | null;
        updated_at?: string;
        updated_by?: string | null;
        user_agent?: string | null;
        verified_at?: string | null;
        verified_by?: string | null;
        village_street?: string | null;
        voter_names?: unknown;
        waiting_position?: number | null;
        wizard_step?: number | null;
    };
};

export type CreateApplicationResponse = CreateApplicationResponses[keyof CreateApplicationResponses];

export type DeleteApplicationData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/g1-applications/{id}';
};

export type DeleteApplicationErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type DeleteApplicationError = DeleteApplicationErrors[keyof DeleteApplicationErrors];

export type DeleteApplicationResponses = {
    200: MessageResponse;
};

export type DeleteApplicationResponse = DeleteApplicationResponses[keyof DeleteApplicationResponses];

export type GetApplicationData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/g1-applications/{id}';
};

export type GetApplicationErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetApplicationError = GetApplicationErrors[keyof GetApplicationErrors];

export type GetApplicationResponses = {
    200: G1Application;
};

export type GetApplicationResponse = GetApplicationResponses[keyof GetApplicationResponses];

export type UpdateApplicationData = {
    body: UpdateApplicationBody;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/g1-applications/{id}';
};

export type UpdateApplicationErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type UpdateApplicationError = UpdateApplicationErrors[keyof UpdateApplicationErrors];

export type UpdateApplicationResponses = {
    200: G1Application;
};

export type UpdateApplicationResponse = UpdateApplicationResponses[keyof UpdateApplicationResponses];

export type SubmitApplicationData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/g1-applications/{id}/submit';
};

export type SubmitApplicationErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type SubmitApplicationError = SubmitApplicationErrors[keyof SubmitApplicationErrors];

export type SubmitApplicationResponses = {
    200: G1Application;
};

export type SubmitApplicationResponse = SubmitApplicationResponses[keyof SubmitApplicationResponses];

export type SaveWizardStepData = {
    body: SaveStepRequest;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/g1-applications/{id}/wizard-step';
};

export type SaveWizardStepErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type SaveWizardStepError = SaveWizardStepErrors[keyof SaveWizardStepErrors];

export type SaveWizardStepResponses = {
    200: SaveStepResponse;
};

export type SaveWizardStepResponse = SaveWizardStepResponses[keyof SaveWizardStepResponses];

export type GetApplicationGuardiansData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/g1-applications/{id}/guardians';
};

export type GetApplicationGuardiansErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetApplicationGuardiansError = GetApplicationGuardiansErrors[keyof GetApplicationGuardiansErrors];

export type GetApplicationGuardiansResponses = {
    200: GetApplicationGuardiansResponse;
};

export type GetApplicationGuardiansResponse2 = GetApplicationGuardiansResponses[keyof GetApplicationGuardiansResponses];

export type SaveGuardiansData = {
    body: SaveGuardiansRequest;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/g1-applications/{id}/guardians';
};

export type SaveGuardiansErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type SaveGuardiansError = SaveGuardiansErrors[keyof SaveGuardiansErrors];

export type SaveGuardiansResponses = {
    200: SaveGuardiansResponse;
};

export type SaveGuardiansResponse2 = SaveGuardiansResponses[keyof SaveGuardiansResponses];

export type GetApplicationAddressesData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/g1-applications/{id}/addresses';
};

export type GetApplicationAddressesErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetApplicationAddressesError = GetApplicationAddressesErrors[keyof GetApplicationAddressesErrors];

export type GetApplicationAddressesResponses = {
    200: GetApplicationAddressesResponse;
};

export type GetApplicationAddressesResponse2 = GetApplicationAddressesResponses[keyof GetApplicationAddressesResponses];

export type SaveAddressesData = {
    body: SaveAddressesRequest;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/g1-applications/{id}/addresses';
};

export type SaveAddressesErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type SaveAddressesError = SaveAddressesErrors[keyof SaveAddressesErrors];

export type SaveAddressesResponses = {
    200: SaveAddressesResponse;
};

export type SaveAddressesResponse2 = SaveAddressesResponses[keyof SaveAddressesResponses];

export type GetApplicationSiblingsData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/g1-applications/{id}/siblings';
};

export type GetApplicationSiblingsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetApplicationSiblingsError = GetApplicationSiblingsErrors[keyof GetApplicationSiblingsErrors];

export type GetApplicationSiblingsResponses = {
    200: GetApplicationSiblingsResponse;
};

export type GetApplicationSiblingsResponse2 = GetApplicationSiblingsResponses[keyof GetApplicationSiblingsResponses];

export type SaveSiblingsData = {
    body: SaveSiblingsRequest;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/g1-applications/{id}/siblings';
};

export type SaveSiblingsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type SaveSiblingsError = SaveSiblingsErrors[keyof SaveSiblingsErrors];

export type SaveSiblingsResponses = {
    200: SaveSiblingsResponse;
};

export type SaveSiblingsResponse2 = SaveSiblingsResponses[keyof SaveSiblingsResponses];

export type CreateSiblingData = {
    body: CreateSiblingRequest;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/g1-applications/{id}/create-sibling';
};

export type CreateSiblingErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type CreateSiblingError = CreateSiblingErrors[keyof CreateSiblingErrors];

export type CreateSiblingResponses = {
    200: CreateSiblingResponse;
};

export type CreateSiblingResponse2 = CreateSiblingResponses[keyof CreateSiblingResponses];

export type GetApplicationDocumentsData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/g1-applications/{id}/documents';
};

export type GetApplicationDocumentsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetApplicationDocumentsError = GetApplicationDocumentsErrors[keyof GetApplicationDocumentsErrors];

export type GetApplicationDocumentsResponses = {
    200: GetDocumentsResponse;
};

export type GetApplicationDocumentsResponse = GetApplicationDocumentsResponses[keyof GetApplicationDocumentsResponses];

export type SaveApplicationDocumentsData = {
    body: SaveDocumentsRequest;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/g1-applications/{id}/documents';
};

export type SaveApplicationDocumentsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type SaveApplicationDocumentsError = SaveApplicationDocumentsErrors[keyof SaveApplicationDocumentsErrors];

export type SaveApplicationDocumentsResponses = {
    200: SaveDocumentsResponse;
};

export type SaveApplicationDocumentsResponse = SaveApplicationDocumentsResponses[keyof SaveApplicationDocumentsResponses];

export type ListBatchesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/enrollment-batches';
};

export type ListBatchesErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ListBatchesError = ListBatchesErrors[keyof ListBatchesErrors];

export type ListBatchesResponses = {
    200: Array<EnrollmentBatch>;
};

export type ListBatchesResponse = ListBatchesResponses[keyof ListBatchesResponses];

export type CreateBatchData = {
    body: CreateBatchBody;
    path?: never;
    query?: never;
    url: '/api/enrollment-batches';
};

export type CreateBatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type CreateBatchError = CreateBatchErrors[keyof CreateBatchErrors];

export type CreateBatchResponses = {
    /**
     * EnrollmentBatch
     */
    201: {
        alumni_percentage?: number;
        appeal_deadline_at?: string | null;
        /**
         * Machine-readable code (e.g., "G1-2026")
         */
        batch_code: string;
        /**
         * Human-readable name (e.g., "Grade 1 Admission 2026")
         */
        batch_name: string;
        buddhism_percentage?: number;
        catholicism_percentage?: number;
        closed_at?: string;
        created_at?: string;
        created_by?: string | null;
        enrollment_type: EnrollmentType;
        finalized_at?: string | null;
        govt_percentage?: number;
        hinduism_percentage?: number;
        id?: string;
        islam_percentage?: number;
        list_published_at?: string | null;
        opened_at?: string;
        proximity_percentage?: number;
        sibling_percentage?: number;
        special_percentage?: number;
        staff_percentage?: number;
        status?: BatchStatus;
        student_allocation?: number;
        waiting_list_size?: number;
        year: number;
    };
};

export type CreateBatchResponse = CreateBatchResponses[keyof CreateBatchResponses];

export type DeleteBatchData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/enrollment-batches/{id}';
};

export type DeleteBatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type DeleteBatchError = DeleteBatchErrors[keyof DeleteBatchErrors];

export type DeleteBatchResponses = {
    200: MessageResponse;
};

export type DeleteBatchResponse = DeleteBatchResponses[keyof DeleteBatchResponses];

export type GetBatchData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/enrollment-batches/{id}';
};

export type GetBatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetBatchError = GetBatchErrors[keyof GetBatchErrors];

export type GetBatchResponses = {
    200: EnrollmentBatch;
};

export type GetBatchResponse = GetBatchResponses[keyof GetBatchResponses];

export type UpdateBatchData = {
    body: UpdateBatchBody;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/enrollment-batches/{id}';
};

export type UpdateBatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type UpdateBatchError = UpdateBatchErrors[keyof UpdateBatchErrors];

export type UpdateBatchResponses = {
    200: EnrollmentBatch;
};

export type UpdateBatchResponse = UpdateBatchResponses[keyof UpdateBatchResponses];

export type ListGnDivisionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/gn-divisions';
};

export type ListGnDivisionsResponses = {
    200: Array<GnDivisionEntry>;
};

export type ListGnDivisionsResponse = ListGnDivisionsResponses[keyof ListGnDivisionsResponses];

export type ListPollingDivisionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/polling-divisions';
};

export type ListPollingDivisionsResponses = {
    200: Array<PollingDivisionEntry>;
};

export type ListPollingDivisionsResponse = ListPollingDivisionsResponses[keyof ListPollingDivisionsResponses];

export type ListGuardiansData = {
    body?: never;
    path?: never;
    query?: {
        search?: string | null;
    };
    url: '/api/guardians';
};

export type ListGuardiansErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ListGuardiansError = ListGuardiansErrors[keyof ListGuardiansErrors];

export type ListGuardiansResponses = {
    200: Array<Guardian>;
};

export type ListGuardiansResponse = ListGuardiansResponses[keyof ListGuardiansResponses];

export type CreateGuardianData = {
    body: CreateGuardianBody;
    path?: never;
    query?: never;
    url: '/api/guardians';
};

export type CreateGuardianErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type CreateGuardianError = CreateGuardianErrors[keyof CreateGuardianErrors];

export type CreateGuardianResponses = {
    /**
     * Guardian
     */
    201: {
        address_id?: string | null;
        contact_email?: string | null;
        contact_phone: string;
        created_at?: string;
        full_name: string;
        govt_service_years?: number | null;
        id: string;
        income_level?: IncomeLevel | null;
        is_govt_employee: boolean;
        is_past_pupil: boolean;
        is_school_staff: boolean;
        is_sri_lankan_citizen?: boolean | null;
        nic_number: string;
        occupation?: string | null;
        past_pupil_verified: boolean;
        relationship_type: string;
        workplace_address?: string | null;
        workplace_name?: string | null;
    };
};

export type CreateGuardianResponse = CreateGuardianResponses[keyof CreateGuardianResponses];

export type GetGuardianData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/guardians/{id}';
};

export type GetGuardianErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetGuardianError = GetGuardianErrors[keyof GetGuardianErrors];

export type GetGuardianResponses = {
    200: Guardian;
};

export type GetGuardianResponse = GetGuardianResponses[keyof GetGuardianResponses];

export type UpdateGuardianData = {
    body: UpdateGuardianBody;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/guardians/{id}';
};

export type UpdateGuardianErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type UpdateGuardianError = UpdateGuardianErrors[keyof UpdateGuardianErrors];

export type UpdateGuardianResponses = {
    200: Guardian;
};

export type UpdateGuardianResponse = UpdateGuardianResponses[keyof UpdateGuardianResponses];

export type ListAddressesData = {
    body?: never;
    path?: never;
    query?: {
        search?: string | null;
    };
    url: '/api/addresses';
};

export type ListAddressesErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ListAddressesError = ListAddressesErrors[keyof ListAddressesErrors];

export type ListAddressesResponses = {
    200: Array<Address>;
};

export type ListAddressesResponse = ListAddressesResponses[keyof ListAddressesResponses];

export type CreateAddressData = {
    body: CreateAddressBody;
    path?: never;
    query?: never;
    url: '/api/addresses';
};

export type CreateAddressErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type CreateAddressError = CreateAddressErrors[keyof CreateAddressErrors];

export type CreateAddressResponses = {
    /**
     * Address
     */
    201: {
        address_line_1: string;
        address_line_2?: string | null;
        city: string;
        created_at?: string;
        distance_to_school_km?: string | null;
        district: string;
        gs_division: string;
        id: string;
        latitude?: string | null;
        longitude?: string | null;
        ownership_proof?: string | null;
        postal_code?: string | null;
        province: string;
        residence_type?: ResidenceType | null;
        verified_by_map: boolean;
    };
};

export type CreateAddressResponse = CreateAddressResponses[keyof CreateAddressResponses];

export type GetAddressData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/addresses/{id}';
};

export type GetAddressErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetAddressError = GetAddressErrors[keyof GetAddressErrors];

export type GetAddressResponses = {
    200: Address;
};

export type GetAddressResponse = GetAddressResponses[keyof GetAddressResponses];

export type ListPastPupilDetailsData = {
    body?: never;
    path?: never;
    query?: {
        guardian_id?: string | null;
    };
    url: '/api/past-pupil-details';
};

export type ListPastPupilDetailsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ListPastPupilDetailsError = ListPastPupilDetailsErrors[keyof ListPastPupilDetailsErrors];

export type ListPastPupilDetailsResponses = {
    200: Array<Model>;
};

export type ListPastPupilDetailsResponse = ListPastPupilDetailsResponses[keyof ListPastPupilDetailsResponses];

export type CreatePastPupilDetailData = {
    body: CreatePastPupilDetailBody;
    path?: never;
    query?: never;
    url: '/api/past-pupil-details';
};

export type CreatePastPupilDetailErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type CreatePastPupilDetailError = CreatePastPupilDetailErrors[keyof CreatePastPupilDetailErrors];

export type CreatePastPupilDetailResponses = {
    /**
     * Model
     */
    201: {
        created_at?: string;
        guardian_id: string;
        highest_grade?: string | null;
        id: string;
        left_reason?: string | null;
        school_id: string;
        student_id?: string | null;
        verification_method?: string | null;
        verified: boolean;
        year_left?: number | null;
    };
};

export type CreatePastPupilDetailResponse = CreatePastPupilDetailResponses[keyof CreatePastPupilDetailResponses];

export type ListSchoolsData = {
    body?: never;
    path?: never;
    query?: {
        search?: string | null;
    };
    url: '/api/schools';
};

export type ListSchoolsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ListSchoolsError = ListSchoolsErrors[keyof ListSchoolsErrors];

export type ListSchoolsResponses = {
    200: Array<SchoolSummary>;
};

export type ListSchoolsResponse = ListSchoolsResponses[keyof ListSchoolsResponses];

export type ListStaffDetailsData = {
    body?: never;
    path?: never;
    query?: {
        guardian_id?: string | null;
    };
    url: '/api/staff-details';
};

export type ListStaffDetailsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ListStaffDetailsError = ListStaffDetailsErrors[keyof ListStaffDetailsErrors];

export type ListStaffDetailsResponses = {
    200: Array<StaffDetail>;
};

export type ListStaffDetailsResponse = ListStaffDetailsResponses[keyof ListStaffDetailsResponses];

export type CreateStaffDetailData = {
    body: CreateStaffDetailBody;
    path?: never;
    query?: never;
    url: '/api/staff-details';
};

export type CreateStaffDetailErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type CreateStaffDetailError = CreateStaffDetailErrors[keyof CreateStaffDetailErrors];

export type CreateStaffDetailResponses = {
    /**
     * StaffDetail
     */
    201: {
        created_at?: string;
        designation?: string | null;
        distance_from_residence_km?: string | null;
        employee_id?: string | null;
        employment_type?: StaffEmploymentType | null;
        guardian_id: string;
        id: string;
        is_current: boolean;
        school_id: string;
        service_end_date?: string | null;
        service_start_date?: string | null;
        staff_type?: StaffType | null;
        verification_doc?: string | null;
    };
};

export type CreateStaffDetailResponse = CreateStaffDetailResponses[keyof CreateStaffDetailResponses];

export type ListStudentsData = {
    body?: never;
    path?: never;
    query?: {
        search?: string | null;
    };
    url: '/api/students';
};

export type ListStudentsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ListStudentsError = ListStudentsErrors[keyof ListStudentsErrors];

export type ListStudentsResponses = {
    200: Array<Student>;
};

export type ListStudentsResponse = ListStudentsResponses[keyof ListStudentsResponses];

export type UpdateStudentData = {
    body: UpdateStudentRequest;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/students/{id}';
};

export type UpdateStudentErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type UpdateStudentError = UpdateStudentErrors[keyof UpdateStudentErrors];

export type UpdateStudentResponses = {
    200: Student;
};

export type UpdateStudentResponse = UpdateStudentResponses[keyof UpdateStudentResponses];

export type ListWorkspaceAddressesData = {
    body?: never;
    path?: never;
    query?: {
        search?: string | null;
    };
    url: '/api/workspace-addresses';
};

export type ListWorkspaceAddressesErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ListWorkspaceAddressesError = ListWorkspaceAddressesErrors[keyof ListWorkspaceAddressesErrors];

export type ListWorkspaceAddressesResponses = {
    200: Array<WorkspaceAddress>;
};

export type ListWorkspaceAddressesResponse = ListWorkspaceAddressesResponses[keyof ListWorkspaceAddressesResponses];

export type CreateWorkspaceAddressData = {
    body: CreateWorkspaceAddressBody;
    path?: never;
    query?: never;
    url: '/api/workspace-addresses';
};

export type CreateWorkspaceAddressErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type CreateWorkspaceAddressError = CreateWorkspaceAddressErrors[keyof CreateWorkspaceAddressErrors];

export type CreateWorkspaceAddressResponses = {
    /**
     * WorkspaceAddress
     */
    201: {
        building?: string | null;
        city: string;
        country: string;
        created_at?: string;
        full_address: string;
        id: string;
        name: string;
        postal_code?: string | null;
        state?: string | null;
        street_1: string;
        street_2?: string | null;
    };
};

export type CreateWorkspaceAddressResponse = CreateWorkspaceAddressResponses[keyof CreateWorkspaceAddressResponses];

export type GetWorkspaceAddressData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        id: string;
    };
    query?: never;
    url: '/api/workspace-addresses/{id}';
};

export type GetWorkspaceAddressErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetWorkspaceAddressError = GetWorkspaceAddressErrors[keyof GetWorkspaceAddressErrors];

export type GetWorkspaceAddressResponses = {
    200: WorkspaceAddress;
};

export type GetWorkspaceAddressResponse = GetWorkspaceAddressResponses[keyof GetWorkspaceAddressResponses];

export type PresignedUploadUrlData = {
    body: PresignedUploadRequest;
    path?: never;
    query?: never;
    url: '/api/uploads/presigned';
};

export type PresignedUploadUrlErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PresignedUploadUrlError = PresignedUploadUrlErrors[keyof PresignedUploadUrlErrors];

export type PresignedUploadUrlResponses = {
    200: PresignedUploadResponse;
};

export type PresignedUploadUrlResponse = PresignedUploadUrlResponses[keyof PresignedUploadUrlResponses];

export type UploadFileData = {
    body: UploadForm;
    path?: never;
    query?: never;
    url: '/api/uploads';
};

export type UploadFileErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type UploadFileError = UploadFileErrors[keyof UploadFileErrors];

export type UploadFileResponses = {
    200: UploadResponse;
};

export type UploadFileResponse = UploadFileResponses[keyof UploadFileResponses];

export type DeleteUploadData = {
    body?: never;
    path: {
        /**
         * String
         */
        key: string;
    };
    query?: never;
    url: '/api/uploads/{key}';
};

export type DeleteUploadErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type DeleteUploadError = DeleteUploadErrors[keyof DeleteUploadErrors];

export type DeleteUploadResponses = {
    200: MessageResponse;
};

export type DeleteUploadResponse = DeleteUploadResponses[keyof DeleteUploadResponses];

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * AuthResponse
     */
    201: {
        access_token: string;
        expires_at: bigint;
        refresh_token: string;
    };
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    200: AuthResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type RefreshErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    200: AuthResponse;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type LogoutData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    200: MessageResponse;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type LogoutAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout-all';
};

export type LogoutAllErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type LogoutAllError = LogoutAllErrors[keyof LogoutAllErrors];

export type LogoutAllResponses = {
    200: MessageResponse;
};

export type LogoutAllResponse = LogoutAllResponses[keyof LogoutAllResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type MeErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type MeError = MeErrors[keyof MeErrors];

export type MeResponses = {
    200: UserResponse;
};

export type MeResponse = MeResponses[keyof MeResponses];
