// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:3001" | (string & {})
}

export type AuthResponse = {
  access_token: string
  expires_at: bigint
  refresh_token: string
}

export type CounterResponse = {
  name: string
  value: number
}

export type ErrorResponse = {
  error: string
}

export type LoginRequest = {
  email: string
  password: string
}

export type MessageResponse = {
  message: string
}

export type RefreshRequest = {
  refresh_token: string
}

export type RegisterRequest = {
  email: string
  password: string
}

export type LoginData = {
  body: LoginRequest
  path?: never
  query?: never
  url: "/api/auth/login"
}

export type LoginErrors = {
  /**
   * Invalid credentials
   */
  401: ErrorResponse
  /**
   * Internal server error
   */
  500: ErrorResponse
}

export type LoginError = LoginErrors[keyof LoginErrors]

export type LoginResponses = {
  /**
   * Login successful
   */
  200: AuthResponse
}

export type LoginResponse = LoginResponses[keyof LoginResponses]

export type LogoutData = {
  body: RefreshRequest
  path?: never
  query?: never
  url: "/api/auth/logout"
}

export type LogoutErrors = {
  /**
   * Internal server error
   */
  500: ErrorResponse
}

export type LogoutError = LogoutErrors[keyof LogoutErrors]

export type LogoutResponses = {
  /**
   * Logged out successfully
   */
  200: MessageResponse
}

export type LogoutResponse = LogoutResponses[keyof LogoutResponses]

export type LogoutAllData = {
  body?: never
  path?: never
  query?: never
  url: "/api/auth/logout-all"
}

export type LogoutAllErrors = {
  /**
   * Not authenticated
   */
  401: ErrorResponse
  /**
   * Internal server error
   */
  500: ErrorResponse
}

export type LogoutAllError = LogoutAllErrors[keyof LogoutAllErrors]

export type LogoutAllResponses = {
  /**
   * All sessions revoked
   */
  200: MessageResponse
}

export type LogoutAllResponse = LogoutAllResponses[keyof LogoutAllResponses]

export type RefreshData = {
  body: RefreshRequest
  path?: never
  query?: never
  url: "/api/auth/refresh"
}

export type RefreshErrors = {
  /**
   * Invalid or reused refresh token
   */
  401: ErrorResponse
  /**
   * Internal server error
   */
  500: ErrorResponse
}

export type RefreshError = RefreshErrors[keyof RefreshErrors]

export type RefreshResponses = {
  /**
   * Token refreshed successfully
   */
  200: AuthResponse
}

export type RefreshResponse = RefreshResponses[keyof RefreshResponses]

export type RegisterData = {
  body: RegisterRequest
  path?: never
  query?: never
  url: "/api/auth/register"
}

export type RegisterErrors = {
  /**
   * Validation error
   */
  400: ErrorResponse
  /**
   * Email already registered
   */
  409: ErrorResponse
  /**
   * Internal server error
   */
  500: ErrorResponse
}

export type RegisterError = RegisterErrors[keyof RegisterErrors]

export type RegisterResponses = {
  /**
   * User registered successfully
   */
  201: AuthResponse
}

export type RegisterResponse = RegisterResponses[keyof RegisterResponses]

export type GetSecureCounterData = {
  body?: never
  path: {
    /**
     * Secure counter name
     */
    name: string
  }
  query?: never
  url: "/api/counter/secure/{name}"
}

export type GetSecureCounterErrors = {
  /**
   * Insufficient permissions
   */
  403: ErrorResponse
  /**
   * Internal server error
   */
  500: ErrorResponse
}

export type GetSecureCounterError =
  GetSecureCounterErrors[keyof GetSecureCounterErrors]

export type GetSecureCounterResponses = {
  /**
   * Secure counter value retrieved
   */
  200: CounterResponse
}

export type GetSecureCounterResponse =
  GetSecureCounterResponses[keyof GetSecureCounterResponses]

export type IncrementSecureCounterData = {
  body?: never
  path: {
    /**
     * Secure counter name
     */
    name: string
  }
  query?: never
  url: "/api/counter/secure/{name}/increment"
}

export type IncrementSecureCounterErrors = {
  /**
   * Insufficient permissions
   */
  403: ErrorResponse
  /**
   * Internal server error
   */
  500: ErrorResponse
}

export type IncrementSecureCounterError =
  IncrementSecureCounterErrors[keyof IncrementSecureCounterErrors]

export type IncrementSecureCounterResponses = {
  /**
   * Secure counter incremented
   */
  200: CounterResponse
}

export type IncrementSecureCounterResponse =
  IncrementSecureCounterResponses[keyof IncrementSecureCounterResponses]

export type GetCounterData = {
  body?: never
  path: {
    /**
     * Counter name
     */
    name: string
  }
  query?: never
  url: "/api/counter/{name}"
}

export type GetCounterErrors = {
  /**
   * Insufficient permissions
   */
  403: ErrorResponse
  /**
   * Internal server error
   */
  500: ErrorResponse
}

export type GetCounterError = GetCounterErrors[keyof GetCounterErrors]

export type GetCounterResponses = {
  /**
   * Counter value retrieved
   */
  200: CounterResponse
}

export type GetCounterResponse = GetCounterResponses[keyof GetCounterResponses]

export type IncrementCounterData = {
  body?: never
  path: {
    /**
     * Counter name
     */
    name: string
  }
  query?: never
  url: "/api/counter/{name}/increment"
}

export type IncrementCounterErrors = {
  /**
   * Insufficient permissions
   */
  403: ErrorResponse
  /**
   * Internal server error
   */
  500: ErrorResponse
}

export type IncrementCounterError =
  IncrementCounterErrors[keyof IncrementCounterErrors]

export type IncrementCounterResponses = {
  /**
   * Counter incremented
   */
  200: CounterResponse
}

export type IncrementCounterResponse =
  IncrementCounterResponses[keyof IncrementCounterResponses]
