// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3001' | (string & {});
};

export type AuthResponse = {
    access_token: string;
    expires_at: bigint;
    refresh_token: string;
};

export type BatchStatus = 'Open' | 'Closed' | 'Archived';

export type CounterResponse = {
    name: string;
    value: number;
};

export type CreateBatchBody = {
    enrollment_type: EnrollmentType;
    year: number;
};

export type EnrollmentBatch = {
    /**
     * Machine-readable code (e.g., "G1-2026")
     */
    batch_code: string;
    /**
     * Human-readable name (e.g., "Grade 1 Admission 2026")
     */
    batch_name: string;
    created_at?: string;
    created_by?: string | null;
    enrollment_type: EnrollmentType;
    id?: string;
    status?: BatchStatus;
    year: number;
};

export type EnrollmentStatus = 'Draft' | 'Pending' | 'ProvisionallyApproved' | 'Approved' | 'Rejected' | 'Withdrawn' | 'Removed';

export type EnrollmentType = 'G1';

export type ErrorResponse = {
    error: string;
};

export type G1Category = 'CloseResident' | 'PastPupilChild' | 'Sibling' | 'MOEOrUGCStaffChild' | 'GovernmentTransferOfficerChild' | 'OverseasArrival' | 'ArmedForcesReserved';

export type G1Enrollment = {
    age_eligibility_verified?: boolean;
    alternative_age_certificate?: boolean;
    alternative_age_certificate_ref?: string | null;
    approved_at?: string | null;
    approved_by?: string | null;
    armed_forces_parent_id?: string | null;
    batch_id: string;
    birth_certificate_number?: string | null;
    birth_certificate_verified?: boolean;
    category: G1Category;
    category_score?: number | null;
    category_verified?: boolean;
    created_at?: string;
    created_by?: string | null;
    date_of_birth: string;
    distance_score?: number | null;
    enrollment_status?: EnrollmentStatus;
    full_name: string;
    gender: Gender;
    id?: string;
    interview_completed?: boolean;
    interview_date?: string | null;
    interview_score?: number | null;
    medium_of_instruction: MediumOfInstruction;
    name_with_initials: string;
    nationality: Nationality;
    overseas_arrival_date?: string | null;
    past_pupil_parent_id?: string | null;
    provisionally_approved_at?: string | null;
    provisionally_approved_by?: string | null;
    rank?: number | null;
    rejection_reason?: string | null;
    religion?: null | Religion;
    residence_verified?: boolean;
    sibling_student_id?: string | null;
    staff_parent_id?: string | null;
    student_id?: string | null;
    submission_method?: string | null;
    total_score?: number | null;
    transfer_officer_parent_id?: string | null;
    updated_at?: string;
    updated_by?: string | null;
};

export type Gender = 'Male' | 'Female';

export type LoginRequest = {
    email: string;
    password: string;
};

export type MediumOfInstruction = 'Sinhala' | 'Tamil';

export type MessageResponse = {
    message: string;
};

export type Nationality = 'SriLankan' | 'DualCitizen' | 'Other';

export type RefreshRequest = {
    refresh_token: string;
};

export type RegisterRequest = {
    email: string;
    password: string;
};

export type Religion = 'Buddhism' | 'Hinduism' | 'Islam' | 'Christianity' | 'Catholicism' | 'Other';

export type UpdateBatchBody = {
    status: BatchStatus;
};

export type UpdateG1EnrollmentBody = {
    age_eligibility_verified?: boolean | null;
    alternative_age_certificate?: boolean | null;
    alternative_age_certificate_ref?: string | null;
    batch_id?: string | null;
    birth_certificate_number?: string | null;
    birth_certificate_verified?: boolean | null;
    category?: null | G1Category;
    category_verified?: boolean | null;
    date_of_birth?: string | null;
    enrollment_status?: null | EnrollmentStatus;
    full_name?: string | null;
    gender?: null | Gender;
    interview_completed?: boolean | null;
    interview_date?: string | null;
    medium_of_instruction?: null | MediumOfInstruction;
    name_with_initials?: string | null;
    nationality?: null | Nationality;
    rank?: number | null;
    rejection_reason?: string | null;
    religion?: null | Religion;
    residence_verified?: boolean | null;
    submission_method?: string | null;
};

export type UploadResponse = {
    file_name: string;
    key: string;
    size: number;
    url: string;
};

export type UserResponse = {
    email: string;
    id: number;
};

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Login successful
     */
    200: AuthResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Logged out successfully
     */
    200: MessageResponse;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type LogoutAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout-all';
};

export type LogoutAllErrors = {
    /**
     * Not authenticated
     */
    401: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type LogoutAllError = LogoutAllErrors[keyof LogoutAllErrors];

export type LogoutAllResponses = {
    /**
     * All sessions revoked
     */
    200: MessageResponse;
};

export type LogoutAllResponse = LogoutAllResponses[keyof LogoutAllResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type MeErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * User not found
     */
    404: ErrorResponse;
};

export type MeError = MeErrors[keyof MeErrors];

export type MeResponses = {
    /**
     * Current user
     */
    200: UserResponse;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type RefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type RefreshErrors = {
    /**
     * Invalid or reused refresh token
     */
    401: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    /**
     * Token refreshed successfully
     */
    200: AuthResponse;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterErrors = {
    /**
     * Validation error
     */
    400: ErrorResponse;
    /**
     * Email already registered
     */
    409: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * User registered successfully
     */
    201: AuthResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type GetSecureCounterData = {
    body?: never;
    path: {
        /**
         * Secure counter name
         */
        name: string;
    };
    query?: never;
    url: '/api/counter/secure/{name}';
};

export type GetSecureCounterErrors = {
    /**
     * Insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetSecureCounterError = GetSecureCounterErrors[keyof GetSecureCounterErrors];

export type GetSecureCounterResponses = {
    /**
     * Secure counter value retrieved
     */
    200: CounterResponse;
};

export type GetSecureCounterResponse = GetSecureCounterResponses[keyof GetSecureCounterResponses];

export type IncrementSecureCounterData = {
    body?: never;
    path: {
        /**
         * Secure counter name
         */
        name: string;
    };
    query?: never;
    url: '/api/counter/secure/{name}/increment';
};

export type IncrementSecureCounterErrors = {
    /**
     * Insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type IncrementSecureCounterError = IncrementSecureCounterErrors[keyof IncrementSecureCounterErrors];

export type IncrementSecureCounterResponses = {
    /**
     * Secure counter incremented
     */
    200: CounterResponse;
};

export type IncrementSecureCounterResponse = IncrementSecureCounterResponses[keyof IncrementSecureCounterResponses];

export type GetCounterData = {
    body?: never;
    path: {
        /**
         * Counter name
         */
        name: string;
    };
    query?: never;
    url: '/api/counter/{name}';
};

export type GetCounterErrors = {
    /**
     * Insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetCounterError = GetCounterErrors[keyof GetCounterErrors];

export type GetCounterResponses = {
    /**
     * Counter value retrieved
     */
    200: CounterResponse;
};

export type GetCounterResponse = GetCounterResponses[keyof GetCounterResponses];

export type IncrementCounterData = {
    body?: never;
    path: {
        /**
         * Counter name
         */
        name: string;
    };
    query?: never;
    url: '/api/counter/{name}/increment';
};

export type IncrementCounterErrors = {
    /**
     * Insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type IncrementCounterError = IncrementCounterErrors[keyof IncrementCounterErrors];

export type IncrementCounterResponses = {
    /**
     * Counter incremented
     */
    200: CounterResponse;
};

export type IncrementCounterResponse = IncrementCounterResponses[keyof IncrementCounterResponses];

export type ListBatchesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/enrollment-batches';
};

export type ListBatchesErrors = {
    /**
     * Insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type ListBatchesError = ListBatchesErrors[keyof ListBatchesErrors];

export type ListBatchesResponses = {
    /**
     * List of enrollment batches
     */
    200: Array<EnrollmentBatch>;
};

export type ListBatchesResponse = ListBatchesResponses[keyof ListBatchesResponses];

export type CreateBatchData = {
    body: CreateBatchBody;
    path?: never;
    query?: never;
    url: '/api/enrollment-batches';
};

export type CreateBatchErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type CreateBatchError = CreateBatchErrors[keyof CreateBatchErrors];

export type CreateBatchResponses = {
    /**
     * Batch created
     */
    201: EnrollmentBatch;
};

export type CreateBatchResponse = CreateBatchResponses[keyof CreateBatchResponses];

export type DeleteBatchData = {
    body?: never;
    path: {
        /**
         * Batch ID
         */
        id: string;
    };
    query?: never;
    url: '/api/enrollment-batches/{id}';
};

export type DeleteBatchErrors = {
    /**
     * Insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Batch not found
     */
    404: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type DeleteBatchError = DeleteBatchErrors[keyof DeleteBatchErrors];

export type DeleteBatchResponses = {
    /**
     * Batch deleted
     */
    200: MessageResponse;
};

export type DeleteBatchResponse = DeleteBatchResponses[keyof DeleteBatchResponses];

export type GetBatchData = {
    body?: never;
    path: {
        /**
         * Batch ID
         */
        id: string;
    };
    query?: never;
    url: '/api/enrollment-batches/{id}';
};

export type GetBatchErrors = {
    /**
     * Insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Batch not found
     */
    404: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetBatchError = GetBatchErrors[keyof GetBatchErrors];

export type GetBatchResponses = {
    /**
     * Batch retrieved
     */
    200: EnrollmentBatch;
};

export type GetBatchResponse = GetBatchResponses[keyof GetBatchResponses];

export type UpdateBatchData = {
    body: UpdateBatchBody;
    path: {
        /**
         * Batch ID
         */
        id: string;
    };
    query?: never;
    url: '/api/enrollment-batches/{id}';
};

export type UpdateBatchErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Batch not found
     */
    404: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type UpdateBatchError = UpdateBatchErrors[keyof UpdateBatchErrors];

export type UpdateBatchResponses = {
    /**
     * Batch updated
     */
    200: EnrollmentBatch;
};

export type UpdateBatchResponse = UpdateBatchResponses[keyof UpdateBatchResponses];

export type ListEnrollmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/g1-enrollments';
};

export type ListEnrollmentsErrors = {
    /**
     * Insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type ListEnrollmentsError = ListEnrollmentsErrors[keyof ListEnrollmentsErrors];

export type ListEnrollmentsResponses = {
    /**
     * List of G1 enrollments
     */
    200: Array<G1Enrollment>;
};

export type ListEnrollmentsResponse = ListEnrollmentsResponses[keyof ListEnrollmentsResponses];

export type CreateEnrollmentData = {
    body: G1Enrollment;
    path?: never;
    query?: never;
    url: '/api/g1-enrollments';
};

export type CreateEnrollmentErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type CreateEnrollmentError = CreateEnrollmentErrors[keyof CreateEnrollmentErrors];

export type CreateEnrollmentResponses = {
    /**
     * Enrollment created
     */
    201: G1Enrollment;
};

export type CreateEnrollmentResponse = CreateEnrollmentResponses[keyof CreateEnrollmentResponses];

export type DeleteEnrollmentData = {
    body?: never;
    path: {
        /**
         * Enrollment ID
         */
        id: string;
    };
    query?: never;
    url: '/api/g1-enrollments/{id}';
};

export type DeleteEnrollmentErrors = {
    /**
     * Insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Enrollment not found
     */
    404: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type DeleteEnrollmentError = DeleteEnrollmentErrors[keyof DeleteEnrollmentErrors];

export type DeleteEnrollmentResponses = {
    /**
     * Enrollment deleted
     */
    200: MessageResponse;
};

export type DeleteEnrollmentResponse = DeleteEnrollmentResponses[keyof DeleteEnrollmentResponses];

export type GetEnrollmentData = {
    body?: never;
    path: {
        /**
         * Enrollment ID
         */
        id: string;
    };
    query?: never;
    url: '/api/g1-enrollments/{id}';
};

export type GetEnrollmentErrors = {
    /**
     * Insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Enrollment not found
     */
    404: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetEnrollmentError = GetEnrollmentErrors[keyof GetEnrollmentErrors];

export type GetEnrollmentResponses = {
    /**
     * Enrollment retrieved
     */
    200: G1Enrollment;
};

export type GetEnrollmentResponse = GetEnrollmentResponses[keyof GetEnrollmentResponses];

export type UpdateEnrollmentData = {
    body: UpdateG1EnrollmentBody;
    path: {
        /**
         * Enrollment ID
         */
        id: string;
    };
    query?: never;
    url: '/api/g1-enrollments/{id}';
};

export type UpdateEnrollmentErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Enrollment not found
     */
    404: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type UpdateEnrollmentError = UpdateEnrollmentErrors[keyof UpdateEnrollmentErrors];

export type UpdateEnrollmentResponses = {
    /**
     * Enrollment updated
     */
    200: G1Enrollment;
};

export type UpdateEnrollmentResponse = UpdateEnrollmentResponses[keyof UpdateEnrollmentResponses];

export type UploadFileData = {
    /**
     * multipart/form-data with `file` field
     */
    body: string;
    path?: never;
    query?: never;
    url: '/api/uploads';
};

export type UploadFileErrors = {
    /**
     * Insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Upload failed
     */
    500: ErrorResponse;
};

export type UploadFileError = UploadFileErrors[keyof UploadFileErrors];

export type UploadFileResponses = {
    /**
     * File uploaded
     */
    200: UploadResponse;
};

export type UploadFileResponse = UploadFileResponses[keyof UploadFileResponses];
