// This file is auto-generated by @hey-api/openapi-ts

import * as v from "valibot"

export const vAddressEntry = v.object({
  address_id: v.pipe(v.string(), v.uuid()),
  address_type: v.string(),
  is_primary: v.boolean(),
  residence_type: v.string(),
})

export const vAddressEntryResponse = v.object({
  address_id: v.pipe(v.string(), v.uuid()),
  address_type: v.string(),
  is_primary: v.boolean(),
  residence_type: v.string(),
})

export const vApplicationListCategory = v.picklist([
  "Main",
  "Waiting",
  "NotSelected",
])

/**
 * AuthResponse
 */
export const vAuthResponse = v.object({
  access_token: v.string(),
  expires_at: v.pipe(
    v.union([v.number(), v.string(), v.bigint()]),
    v.transform((x) => BigInt(x)),
    v.minValue(
      BigInt("-9223372036854775808"),
      "Invalid value: Expected int64 to be >= -9223372036854775808"
    ),
    v.maxValue(
      BigInt("9223372036854775807"),
      "Invalid value: Expected int64 to be <= 9223372036854775807"
    )
  ),
  refresh_token: v.string(),
})

export const vBatchStatus = v.picklist([
  "Open",
  "Closed",
  "ListsPublished",
  "AppealsPeriod",
  "Archived",
])

/**
 * Blacklist
 */
export const vBlacklist = v.object({
  application_id: v.nullish(v.pipe(v.string(), v.uuid())),
  blacklisted_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.056090300Z"
  ),
  blacklisted_by: v.nullish(v.pipe(v.string(), v.uuid())),
  evidence_url: v.nullish(v.string()),
  expires_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2029-08-10T08:36:36.056106700Z"
  ),
  guardian_id: v.pipe(v.string(), v.uuid()),
  id: v.optional(
    v.pipe(v.string(), v.uuid()),
    "c13aedd9-e32e-4aaa-b489-2d3642096855"
  ),
  reason: v.string(),
  status: v.optional(v.string(), "Active"),
})

/**
 * CounterResponse
 */
export const vCounterResponse = v.object({
  name: v.string(),
  value: v.pipe(
    v.number(),
    v.integer(),
    v.minValue(
      -2147483648,
      "Invalid value: Expected int32 to be >= -2147483648"
    ),
    v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647")
  ),
})

/**
 * CreateAddressBody
 */
export const vCreateAddressBody = v.object({
  address_line_1: v.string(),
  address_line_2: v.nullish(v.string()),
  city: v.string(),
  distance_to_school_km: v.nullish(v.number()),
  district: v.string(),
  gs_division: v.string(),
  latitude: v.nullish(v.number()),
  longitude: v.nullish(v.number()),
  ownership_proof: v.nullish(v.string()),
  postal_code: v.nullish(v.string()),
  province: v.string(),
  residence_type: v.nullish(v.string()),
  verified_by_map: v.nullish(v.boolean()),
})

/**
 * CreateApplicationBody
 */
export const vCreateApplicationBody = v.object({
  batch_id: v.pipe(v.string(), v.uuid()),
  child_id: v.nullish(v.pipe(v.string(), v.uuid())),
  preferred_school_ids: v.nullish(v.array(v.pipe(v.string(), v.uuid()))),
  school_id: v.nullish(v.pipe(v.string(), v.uuid())),
})

/**
 * CreatePastPupilDetailBody
 */
export const vCreatePastPupilDetailBody = v.object({
  guardian_id: v.pipe(v.string(), v.uuid()),
  highest_grade: v.nullish(v.string()),
  left_reason: v.nullish(v.string()),
  school_id: v.pipe(v.string(), v.uuid()),
  student_id: v.nullish(v.string()),
  verification_method: v.nullish(v.string()),
  year_left: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
})

/**
 * CreateStudentResponse
 */
export const vCreateStudentResponse = v.object({
  child_id: v.pipe(v.string(), v.uuid()),
  student_id: v.pipe(v.string(), v.uuid()),
  used_existing_child: v.boolean(),
})

/**
 * CreateWorkspaceAddressBody
 */
export const vCreateWorkspaceAddressBody = v.object({
  building: v.nullish(v.string()),
  city: v.string(),
  country: v.string(),
  name: v.string(),
  postal_code: v.nullish(v.string()),
  state: v.nullish(v.string()),
  street_1: v.string(),
  street_2: v.nullish(v.string()),
})

/**
 * District
 */
export const vDistrict = v.object({
  id: v.pipe(v.string(), v.uuid()),
  name_en: v.string(),
  name_si: v.string(),
  province: v.string(),
})

export const vDocumentEntry = v.object({
  content_type: v.nullish(v.string()),
  doc_type: v.string(),
  file_key: v.string(),
  file_name: v.nullish(v.string()),
  file_size: v.nullish(
    v.pipe(
      v.union([v.number(), v.string(), v.bigint()]),
      v.transform((x) => BigInt(x)),
      v.minValue(
        BigInt("-9223372036854775808"),
        "Invalid value: Expected int64 to be >= -9223372036854775808"
      ),
      v.maxValue(
        BigInt("9223372036854775807"),
        "Invalid value: Expected int64 to be <= 9223372036854775807"
      )
    )
  ),
  file_url: v.string(),
})

export const vElectoralDistrict = v.picklist([
  "Colombo",
  "Gampaha",
  "Kalutara",
  "Kandy",
  "Matale",
  "NuwaraEliya",
  "Galle",
  "Matara",
  "Hambantota",
  "Jaffna",
  "Vanni",
  "Batticaloa",
  "Ampara",
  "Trincomalee",
  "Kurunegala",
  "Puttalam",
  "Anuradhapura",
  "Polonnaruwa",
  "Badulla",
  "Monaragala",
  "Ratnapura",
  "Kegalle",
])

export const vEnrollmentStatus = v.picklist([
  "Draft",
  "Pending",
  "Completed",
  "PendingApproval",
  "Approved",
  "Admitted",
  "Rejected",
  "Withdrawn",
  "Disqualified",
])

export const vEnrollmentType = v.picklist(["G1"])

/**
 * CreateBatchBody
 */
export const vCreateBatchBody = v.object({
  alumni_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  buddhism_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  catholicism_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  enrollment_type: vEnrollmentType,
  govt_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  hinduism_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  islam_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  proximity_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  sibling_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  special_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  staff_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  student_allocation: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(
        -2147483648,
        "Invalid value: Expected int32 to be >= -2147483648"
      ),
      v.maxValue(
        2147483647,
        "Invalid value: Expected int32 to be <= 2147483647"
      )
    )
  ),
  year: v.pipe(
    v.number(),
    v.integer(),
    v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
    v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
  ),
})

/**
 * EnrollmentBatch
 */
export const vEnrollmentBatch = v.object({
  alumni_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    6
  ),
  appeal_deadline_at: v.nullish(v.pipe(v.string(), v.isoTimestamp()), null),
  batch_code: v.string(),
  batch_name: v.string(),
  buddhism_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    74
  ),
  catholicism_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    12
  ),
  closed_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2027-08-11T08:36:36.088152300Z"
  ),
  created_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.088175600Z"
  ),
  created_by: v.nullish(v.pipe(v.string(), v.uuid()), null),
  enrollment_type: vEnrollmentType,
  finalized_at: v.nullish(v.pipe(v.string(), v.isoTimestamp()), null),
  govt_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    4
  ),
  hinduism_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    0
  ),
  id: v.optional(
    v.pipe(v.string(), v.uuid()),
    "c02beb3d-d6d3-4ff5-bacb-71176b39634c"
  ),
  islam_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    14
  ),
  list_published_at: v.nullish(v.pipe(v.string(), v.isoTimestamp()), null),
  opened_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.088142800Z"
  ),
  proximity_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    50
  ),
  sibling_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    14
  ),
  special_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    1
  ),
  staff_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    25
  ),
  status: v.optional(vBatchStatus),
  student_allocation: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(
        -2147483648,
        "Invalid value: Expected int32 to be >= -2147483648"
      ),
      v.maxValue(
        2147483647,
        "Invalid value: Expected int32 to be <= 2147483647"
      )
    ),
    200
  ),
  waiting_list_size: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(
        -2147483648,
        "Invalid value: Expected int32 to be >= -2147483648"
      ),
      v.maxValue(
        2147483647,
        "Invalid value: Expected int32 to be <= 2147483647"
      )
    ),
    20
  ),
  year: v.pipe(
    v.number(),
    v.integer(),
    v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
    v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
  ),
})

/**
 * ErrorResponse
 */
export const vErrorResponse = v.object({
  error: v.string(),
})

export const vG1Category = v.picklist([
  "CloseResident",
  "PastPupilChild",
  "Sibling",
  "MOEOrUGCStaffChild",
  "GovernmentTransferOfficerChild",
  "OverseasArrival",
  "ArmedForcesReserved",
  "SpecialNeeds",
  "LowIncome",
])

/**
 * G1Application
 */
export const vG1Application = v.object({
  age_eligibility_verified: v.boolean(),
  alternative_age_certificate: v.boolean(),
  alternative_age_certificate_ref: v.nullish(v.string()),
  batch_id: v.pipe(v.string(), v.uuid()),
  birth_certificate_verified: v.boolean(),
  category: v.nullish(vG1Category),
  category_verified: v.boolean(),
  child_id: v.optional(
    v.pipe(v.string(), v.uuid()),
    "00000000-0000-0000-0000-000000000000"
  ),
  closer_school_exists: v.nullish(v.boolean()),
  created_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.076940500Z"
  ),
  created_by: v.nullish(v.pipe(v.string(), v.uuid())),
  declaration_agreed: v.boolean(),
  declaration_signed_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
  deleted_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
  electoral_year: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  enrollment_status: v.optional(vEnrollmentStatus),
  finalized_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
  gn_name: v.nullish(v.string()),
  gn_number: v.nullish(v.string()),
  guardian_id: v.optional(
    v.pipe(v.string(), v.uuid()),
    "00000000-0000-0000-0000-000000000000"
  ),
  household_head_name: v.nullish(v.string()),
  id: v.optional(
    v.pipe(v.string(), v.uuid()),
    "280399da-410a-40ba-a9ab-7541659373f4"
  ),
  interview_completed: v.boolean(),
  interview_date: v.nullish(v.pipe(v.string(), v.isoDate())),
  ip_address: v.nullish(v.string()),
  list_category: v.nullish(vApplicationListCategory),
  overseas_arrival_date: v.nullish(v.pipe(v.string(), v.isoDate())),
  polling_area: v.nullish(v.string()),
  polling_district: v.nullish(vElectoralDistrict),
  polling_division: v.nullish(v.string()),
  preferred_school_ids: v.optional(v.unknown()),
  rank_number: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(
        -2147483648,
        "Invalid value: Expected int32 to be >= -2147483648"
      ),
      v.maxValue(
        2147483647,
        "Invalid value: Expected int32 to be <= 2147483647"
      )
    )
  ),
  reference_no: v.optional(
    v.string(),
    "DRAFT-71ae652b-6d12-4203-8e3f-ac7f618a6026"
  ),
  rejection_reason: v.nullish(v.string()),
  residence_verified: v.boolean(),
  school_id: v.nullish(v.pipe(v.string(), v.uuid()), null),
  submission_method: v.nullish(v.string()),
  submitted_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
  total_marks: v.nullish(v.pipe(v.string(), v.regex(/^-?[0-9]+(\.[0-9]+)?$/))),
  updated_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.076948900Z"
  ),
  updated_by: v.nullish(v.pipe(v.string(), v.uuid())),
  user_agent: v.nullish(v.string()),
  verified_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
  verified_by: v.nullish(v.pipe(v.string(), v.uuid())),
  village_street: v.nullish(v.string()),
  voter_names: v.optional(v.unknown()),
  wizard_step: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
})

export const vGender = v.picklist(["Male", "Female"])

/**
 * GetApplicationAddressesResponse
 */
export const vGetApplicationAddressesResponse = v.object({
  addresses: v.array(vAddressEntryResponse),
})

/**
 * GetApplicationGuardiansResponse
 */
export const vGetApplicationGuardiansResponse = v.object({
  guardian_ids: v.array(v.pipe(v.string(), v.uuid())),
})

/**
 * GetApplicationSiblingsResponse
 */
export const vGetApplicationSiblingsResponse = v.object({
  sibling_ids: v.array(v.pipe(v.string(), v.uuid())),
})

/**
 * GetDocumentsResponse
 */
export const vGetDocumentsResponse = v.object({
  documents: v.array(vDocumentEntry),
})

/**
 * GnDivisionEntry
 */
export const vGnDivisionEntry = v.object({
  id: v.string(),
  lat: v.number(),
  lon: v.number(),
  name_en: v.string(),
  name_local: v.string(),
  parent_id: v.string(),
  parent_name_en: v.string(),
  parent_name_local: v.string(),
  postal_code: v.string(),
  slug: v.string(),
})

export const vGuardianRelationship = v.picklist([
  "Father",
  "Mother",
  "Guardian",
])

export const vIncomeLevel = v.picklist([
  "below_25000",
  "25000_50000",
  "50000_100000",
  "100000_200000",
  "200000_500000",
  "above_500000",
])

/**
 * Guardian
 */
export const vGuardian = v.object({
  address_id: v.nullish(v.pipe(v.string(), v.uuid()), null),
  contact_email: v.nullish(v.string()),
  contact_phone: v.string(),
  created_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.095024200Z"
  ),
  full_name: v.string(),
  govt_service_years: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(
        -2147483648,
        "Invalid value: Expected int32 to be >= -2147483648"
      ),
      v.maxValue(
        2147483647,
        "Invalid value: Expected int32 to be <= 2147483647"
      )
    )
  ),
  id: v.pipe(v.string(), v.uuid()),
  income_level: v.nullish(vIncomeLevel),
  is_govt_employee: v.boolean(),
  is_past_pupil: v.boolean(),
  is_school_staff: v.boolean(),
  is_sri_lankan_citizen: v.nullish(v.boolean()),
  nic_number: v.string(),
  occupation: v.nullish(v.string()),
  past_pupil_verified: v.boolean(),
  relationship_type: vGuardianRelationship,
  student_id: v.nullish(v.pipe(v.string(), v.uuid())),
  workplace_address: v.nullish(v.string()),
  workplace_name: v.nullish(v.string()),
})

/**
 * LoginRequest
 */
export const vLoginRequest = v.object({
  email: v.string(),
  password: v.string(),
})

export const vMediumOfInstruction = v.picklist(["Sinhala", "Tamil"])

/**
 * MessageResponse
 */
export const vMessageResponse = v.object({
  message: v.string(),
})

/**
 * Model
 */
export const vModel = v.object({
  created_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.100979Z"
  ),
  guardian_id: v.pipe(v.string(), v.uuid()),
  highest_grade: v.nullish(v.string()),
  id: v.pipe(v.string(), v.uuid()),
  left_reason: v.nullish(v.string()),
  school_id: v.pipe(v.string(), v.uuid()),
  student_id: v.nullish(v.string()),
  verification_method: v.nullish(v.string()),
  verified: v.boolean(),
  year_left: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
})

export const vNationality = v.picklist(["SriLankan", "DualCitizen", "Other"])

/**
 * PollingDivisionEntry
 */
export const vPollingDivisionEntry = v.object({
  district: v.string(),
  label: v.string(),
  si: v.string(),
  value: v.string(),
})

/**
 * PresignedUploadRequest
 */
export const vPresignedUploadRequest = v.object({
  content_type: v.string(),
  file_name: v.string(),
  file_size: v.pipe(
    v.union([v.number(), v.string(), v.bigint()]),
    v.transform((x) => BigInt(x)),
    v.minValue(
      BigInt("-9223372036854775808"),
      "Invalid value: Expected int64 to be >= -9223372036854775808"
    ),
    v.maxValue(
      BigInt("9223372036854775807"),
      "Invalid value: Expected int64 to be <= 9223372036854775807"
    )
  ),
})

/**
 * PresignedUploadResponse
 */
export const vPresignedUploadResponse = v.object({
  content_type: v.string(),
  file_name: v.string(),
  file_size: v.pipe(
    v.union([v.number(), v.string(), v.bigint()]),
    v.transform((x) => BigInt(x)),
    v.minValue(
      BigInt("-9223372036854775808"),
      "Invalid value: Expected int64 to be >= -9223372036854775808"
    ),
    v.maxValue(
      BigInt("9223372036854775807"),
      "Invalid value: Expected int64 to be <= 9223372036854775807"
    )
  ),
  key: v.string(),
  public_url: v.string(),
  url: v.string(),
})

/**
 * RefreshRequest
 */
export const vRefreshRequest = v.object({
  refresh_token: v.string(),
})

/**
 * RegisterRequest
 */
export const vRegisterRequest = v.object({
  email: v.string(),
  password: v.string(),
})

export const vReligion = v.picklist([
  "Buddhism",
  "Hinduism",
  "Islam",
  "Christianity",
  "Catholicism",
  "Other",
])

export const vApplicationWithChild = v.object({
  age_eligibility_verified: v.boolean(),
  alternative_age_certificate: v.boolean(),
  alternative_age_certificate_ref: v.nullish(v.string()),
  batch_id: v.pipe(v.string(), v.uuid()),
  birth_certificate_verified: v.boolean(),
  category: v.nullish(vG1Category),
  category_verified: v.boolean(),
  child_birth_certificate_number: v.nullish(v.string()),
  child_date_of_birth: v.nullish(v.pipe(v.string(), v.isoDate())),
  child_full_name: v.nullish(v.string()),
  child_gender: v.nullish(vGender),
  child_id: v.pipe(v.string(), v.uuid()),
  child_medium_of_instruction: v.nullish(vMediumOfInstruction),
  child_name_with_initials: v.nullish(v.string()),
  child_nationality: v.nullish(vNationality),
  child_photo_url: v.nullish(v.string()),
  child_religion: v.nullish(vReligion),
  created_at: v.pipe(v.string(), v.isoTimestamp()),
  created_by: v.nullish(v.pipe(v.string(), v.uuid())),
  deleted_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
  enrollment_status: vEnrollmentStatus,
  finalized_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
  guardian_id: v.pipe(v.string(), v.uuid()),
  id: v.pipe(v.string(), v.uuid()),
  interview_completed: v.boolean(),
  interview_date: v.nullish(v.pipe(v.string(), v.isoDate())),
  ip_address: v.nullish(v.string()),
  list_category: v.nullish(vApplicationListCategory),
  overseas_arrival_date: v.nullish(v.pipe(v.string(), v.isoDate())),
  rank_number: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(
        -2147483648,
        "Invalid value: Expected int32 to be >= -2147483648"
      ),
      v.maxValue(
        2147483647,
        "Invalid value: Expected int32 to be <= 2147483647"
      )
    )
  ),
  reference_no: v.string(),
  rejection_reason: v.nullish(v.string()),
  residence_verified: v.boolean(),
  school_id: v.nullish(v.pipe(v.string(), v.uuid())),
  submission_method: v.nullish(v.string()),
  submitted_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
  total_marks: v.nullish(v.string()),
  updated_at: v.pipe(v.string(), v.isoTimestamp()),
  updated_by: v.nullish(v.pipe(v.string(), v.uuid())),
  user_agent: v.nullish(v.string()),
  verified_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
  verified_by: v.nullish(v.pipe(v.string(), v.uuid())),
  wizard_step: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
})

/**
 * CreateChildBody
 */
export const vCreateChildBody = v.object({
  birth_certificate_number: v.nullish(v.string()),
  date_of_birth: v.pipe(v.string(), v.isoDate()),
  disability_status: v.nullish(v.boolean()),
  disability_type: v.nullish(v.string()),
  full_name: v.string(),
  gender: vGender,
  medium_of_instruction: vMediumOfInstruction,
  name_with_initials: v.string(),
  nationality: vNationality,
  nic: v.nullish(v.string()),
  passport_number: v.nullish(v.string()),
  photo_url: v.nullish(v.string()),
  religion: v.nullish(vReligion),
})

/**
 * CreateSiblingRequest
 */
export const vCreateSiblingRequest = v.object({
  birth_certificate_number: v.nullish(v.string()),
  current_grade: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  date_of_birth: v.pipe(v.string(), v.isoDate()),
  email: v.nullish(v.string()),
  full_name: v.string(),
  gender: vGender,
  medium_of_instruction: vMediumOfInstruction,
  name_with_initials: v.string(),
  nationality: vNationality,
  nic: v.nullish(v.string()),
  passport_number: v.nullish(v.string()),
  phone: v.nullish(v.string()),
  religion: v.nullish(vReligion),
  school_id: v.nullish(v.pipe(v.string(), v.uuid())),
})

/**
 * CreateStudentBody
 */
export const vCreateStudentBody = v.object({
  birth_certificate_number: v.nullish(v.string()),
  child_id: v.nullish(v.pipe(v.string(), v.uuid())),
  date_of_birth: v.nullish(v.pipe(v.string(), v.isoDate())),
  full_name: v.nullish(v.string()),
  gender: v.nullish(vGender),
  medium_of_instruction: v.nullish(vMediumOfInstruction),
  name_with_initials: v.nullish(v.string()),
  nationality: v.nullish(vNationality),
  nic: v.nullish(v.string()),
  passport_number: v.nullish(v.string()),
  religion: v.nullish(vReligion),
})

/**
 * PaginatedApplicationsResponse
 */
export const vPaginatedApplicationsResponse = v.object({
  items: v.array(vApplicationWithChild),
  total: v.pipe(
    v.number(),
    v.integer(),
    v.minValue(
      -2147483648,
      "Invalid value: Expected int32 to be >= -2147483648"
    ),
    v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647")
  ),
})

export const vResidenceType = v.picklist([
  "Owned",
  "Rented",
  "Relative",
  "Other",
])

/**
 * Address
 */
export const vAddress = v.object({
  address_line_1: v.string(),
  address_line_2: v.nullish(v.string()),
  city: v.string(),
  created_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.098944Z"
  ),
  distance_to_school_km: v.nullish(
    v.pipe(v.string(), v.regex(/^-?[0-9]+(\.[0-9]+)?$/))
  ),
  district: v.string(),
  gs_division: v.string(),
  id: v.pipe(v.string(), v.uuid()),
  latitude: v.nullish(v.pipe(v.string(), v.regex(/^-?[0-9]+(\.[0-9]+)?$/))),
  longitude: v.nullish(v.pipe(v.string(), v.regex(/^-?[0-9]+(\.[0-9]+)?$/))),
  ownership_proof: v.nullish(v.string()),
  postal_code: v.nullish(v.string()),
  province: v.string(),
  residence_type: v.nullish(vResidenceType),
  verified_by_map: v.boolean(),
})

/**
 * SaveAddressesRequest
 */
export const vSaveAddressesRequest = v.object({
  addresses: v.array(vAddressEntry),
})

/**
 * SaveAddressesResponse
 */
export const vSaveAddressesResponse = v.object({
  count: v.pipe(v.number(), v.integer(), v.minValue(0)),
})

export const vSaveDocumentEntry = v.object({
  content_type: v.nullish(v.string()),
  doc_type: v.string(),
  file_key: v.string(),
  file_size: v.nullish(
    v.pipe(
      v.union([v.number(), v.string(), v.bigint()]),
      v.transform((x) => BigInt(x)),
      v.minValue(
        BigInt("-9223372036854775808"),
        "Invalid value: Expected int64 to be >= -9223372036854775808"
      ),
      v.maxValue(
        BigInt("9223372036854775807"),
        "Invalid value: Expected int64 to be <= 9223372036854775807"
      )
    )
  ),
  file_url: v.string(),
})

/**
 * SaveDocumentsRequest
 */
export const vSaveDocumentsRequest = v.object({
  documents: v.array(vSaveDocumentEntry),
})

/**
 * SaveDocumentsResponse
 */
export const vSaveDocumentsResponse = v.object({
  count: v.pipe(v.number(), v.integer(), v.minValue(0)),
})

/**
 * SaveGuardiansRequest
 */
export const vSaveGuardiansRequest = v.object({
  guardian_ids: v.array(v.pipe(v.string(), v.uuid())),
})

/**
 * SaveGuardiansResponse
 */
export const vSaveGuardiansResponse = v.object({
  count: v.pipe(v.number(), v.integer(), v.minValue(0)),
})

/**
 * SaveSiblingsRequest
 */
export const vSaveSiblingsRequest = v.object({
  student_ids: v.array(v.pipe(v.string(), v.uuid())),
})

/**
 * SaveSiblingsResponse
 */
export const vSaveSiblingsResponse = v.object({
  count: v.pipe(v.number(), v.integer(), v.minValue(0)),
})

/**
 * SaveStepRequest
 */
export const vSaveStepRequest = v.object({
  wizard_step: v.pipe(
    v.number(),
    v.integer(),
    v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
    v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
  ),
})

/**
 * SaveStepResponse
 */
export const vSaveStepResponse = v.object({
  wizard_step: v.pipe(
    v.number(),
    v.integer(),
    v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
    v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
  ),
})

/**
 * SchoolSummary
 */
export const vSchoolSummary = v.object({
  district_id: v.nullish(v.pipe(v.string(), v.uuid())),
  id: v.pipe(v.string(), v.uuid()),
  name_en: v.nullish(v.string()),
  name_si: v.string(),
})

export const vSiblingDuplicate = v.object({
  birth_certificate_number: v.nullish(v.string()),
  current_grade: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  date_of_birth: v.pipe(v.string(), v.isoDate()),
  full_name: v.string(),
  gender: vGender,
  id: v.pipe(v.string(), v.uuid()),
  medium_of_instruction: vMediumOfInstruction,
  name_with_initials: v.string(),
  nationality: vNationality,
  nic: v.nullish(v.string()),
})

/**
 * CreateSiblingResponse
 */
export const vCreateSiblingResponse = v.object({
  created: v.boolean(),
  duplicates: v.array(vSiblingDuplicate),
  student_id: v.nullish(v.pipe(v.string(), v.uuid())),
})

export const vStaffEmploymentType = v.picklist([
  "Permanent",
  "Temporary",
  "Contract",
])

export const vStaffType = v.picklist(["Teacher", "Admin", "Worker"])

/**
 * CreateGuardianBody
 */
export const vCreateGuardianBody = v.object({
  contact_email: v.nullish(v.string()),
  contact_phone: v.string(),
  employee_id: v.nullish(v.string()),
  full_name: v.string(),
  govt_service_years: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(
        -2147483648,
        "Invalid value: Expected int32 to be >= -2147483648"
      ),
      v.maxValue(
        2147483647,
        "Invalid value: Expected int32 to be <= 2147483647"
      )
    )
  ),
  income_level: v.nullish(vIncomeLevel),
  is_govt_employee: v.boolean(),
  is_past_pupil: v.boolean(),
  is_school_staff: v.boolean(),
  nic_number: v.string(),
  occupation: v.nullish(v.string()),
  past_pupil_highest_grade: v.nullish(v.string()),
  past_pupil_left_reason: v.nullish(v.string()),
  past_pupil_school_id: v.nullish(v.pipe(v.string(), v.uuid())),
  past_pupil_student_id: v.nullish(v.string()),
  past_pupil_year_left: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  relationship_type: vGuardianRelationship,
  staff_school_id: v.nullish(v.pipe(v.string(), v.uuid())),
  staff_type: v.nullish(vStaffType),
  student_id: v.nullish(v.pipe(v.string(), v.uuid())),
  workplace_address: v.nullish(v.string()),
  workplace_name: v.nullish(v.string()),
})

/**
 * CreateStaffDetailBody
 */
export const vCreateStaffDetailBody = v.object({
  designation: v.nullish(v.string()),
  employee_id: v.nullish(v.string()),
  guardian_id: v.pipe(v.string(), v.uuid()),
  school_id: v.pipe(v.string(), v.uuid()),
  staff_type: v.nullish(vStaffType),
})

/**
 * StaffDetail
 */
export const vStaffDetail = v.object({
  created_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.104101800Z"
  ),
  designation: v.nullish(v.string()),
  distance_from_residence_km: v.nullish(
    v.pipe(v.string(), v.regex(/^-?[0-9]+(\.[0-9]+)?$/))
  ),
  employee_id: v.nullish(v.string()),
  employment_type: v.nullish(vStaffEmploymentType),
  guardian_id: v.pipe(v.string(), v.uuid()),
  id: v.pipe(v.string(), v.uuid()),
  is_current: v.boolean(),
  school_id: v.pipe(v.string(), v.uuid()),
  service_end_date: v.nullish(v.pipe(v.string(), v.isoDate())),
  service_start_date: v.nullish(v.pipe(v.string(), v.isoDate())),
  staff_type: v.nullish(vStaffType),
  verification_doc: v.nullish(v.string()),
})

export const vStudentStatus = v.picklist(["Active", "Graduated", "Removed"])

/**
 * Child
 */
export const vChild = v.object({
  admission_date: v.nullish(v.pipe(v.string(), v.isoDate())),
  admission_number: v.nullish(v.string()),
  birth_certificate_number: v.nullish(v.string()),
  created_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.108415600Z"
  ),
  created_by: v.nullish(v.pipe(v.string(), v.uuid())),
  current_grade: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  date_of_birth: v.pipe(v.string(), v.isoDate()),
  disability_status: v.optional(v.boolean(), false),
  disability_type: v.nullish(v.string(), null),
  email: v.nullish(v.string()),
  full_name: v.string(),
  gender: vGender,
  id: v.pipe(v.string(), v.uuid()),
  medium_of_instruction: vMediumOfInstruction,
  name_with_initials: v.string(),
  name_with_initials_en: v.nullish(v.string()),
  nationality: vNationality,
  nic: v.nullish(v.string()),
  passport_number: v.nullish(v.string()),
  phone: v.nullish(v.string()),
  photo_url: v.nullish(v.string(), null),
  religion: v.nullish(vReligion),
  status: vStudentStatus,
  student_id: v.nullish(v.pipe(v.string(), v.uuid()), null),
  updated_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.108425200Z"
  ),
  updated_by: v.nullish(v.pipe(v.string(), v.uuid())),
})

export const vChildInfo = v.object({
  current_grade: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  date_of_birth: v.pipe(v.string(), v.isoDate()),
  full_name: v.string(),
  gender: vGender,
  id: v.pipe(v.string(), v.uuid()),
  name_with_initials: v.string(),
  status: vStudentStatus,
  student_id: v.nullish(v.pipe(v.string(), v.uuid())),
})

/**
 * GuardianWithChildren
 */
export const vGuardianWithChildren = v.object({
  children: v.array(vChildInfo),
  contact_email: v.nullish(v.string()),
  contact_phone: v.string(),
  created_at: v.pipe(v.string(), v.isoTimestamp()),
  full_name: v.string(),
  govt_service_years: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(
        -2147483648,
        "Invalid value: Expected int32 to be >= -2147483648"
      ),
      v.maxValue(
        2147483647,
        "Invalid value: Expected int32 to be <= 2147483647"
      )
    )
  ),
  id: v.pipe(v.string(), v.uuid()),
  income_level: v.nullish(vIncomeLevel),
  is_govt_employee: v.boolean(),
  is_past_pupil: v.boolean(),
  is_school_staff: v.boolean(),
  nic_number: v.string(),
  occupation: v.nullish(v.string()),
  past_pupil_verified: v.boolean(),
  relationship_type: vGuardianRelationship,
  student_id: v.nullish(v.pipe(v.string(), v.uuid())),
  workplace_address: v.nullish(v.string()),
  workplace_name: v.nullish(v.string()),
})

/**
 * StudentResponse
 *
 * Response type that combines student record with child data
 */
export const vStudentResponse = v.object({
  admission_date: v.nullish(v.pipe(v.string(), v.isoDate())),
  admission_number: v.nullish(v.string()),
  birth_certificate_number: v.nullish(v.string()),
  child_id: v.pipe(v.string(), v.uuid()),
  created_at: v.pipe(v.string(), v.isoTimestamp()),
  created_by: v.nullish(v.pipe(v.string(), v.uuid())),
  current_grade: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  date_of_birth: v.pipe(v.string(), v.isoDate()),
  disability_status: v.boolean(),
  email: v.nullish(v.string()),
  full_name: v.string(),
  gender: vGender,
  id: v.pipe(v.string(), v.uuid()),
  medium_of_instruction: vMediumOfInstruction,
  name_with_initials: v.string(),
  nationality: vNationality,
  nic: v.nullish(v.string()),
  passport_number: v.nullish(v.string()),
  phone: v.nullish(v.string()),
  photo_url: v.nullish(v.string()),
  religion: v.nullish(vReligion),
  status: vStudentStatus,
  updated_at: v.pipe(v.string(), v.isoTimestamp()),
  updated_by: v.nullish(v.pipe(v.string(), v.uuid())),
})

/**
 * UpdateApplicationBody
 */
export const vUpdateApplicationBody = v.object({
  age_eligibility_verified: v.nullish(v.boolean()),
  alternative_age_certificate: v.nullish(v.boolean()),
  alternative_age_certificate_ref: v.nullish(v.string()),
  birth_certificate_verified: v.nullish(v.boolean()),
  category: v.nullish(vG1Category),
  category_verified: v.nullish(v.boolean()),
  child_id: v.nullish(v.pipe(v.string(), v.uuid())),
  closer_school_exists: v.nullish(v.boolean()),
  declaration_agreed: v.nullish(v.boolean()),
  electoral_year: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  forged_document_type: v.nullish(v.string()),
  fraud_flag: v.nullish(v.boolean()),
  gn_name: v.nullish(v.string()),
  gn_number: v.nullish(v.string()),
  guardian_id: v.nullish(v.pipe(v.string(), v.uuid())),
  household_head_name: v.nullish(v.string()),
  interview_completed: v.nullish(v.boolean()),
  interview_date: v.nullish(v.pipe(v.string(), v.isoDate())),
  overseas_arrival_date: v.nullish(v.pipe(v.string(), v.isoDate())),
  polling_area: v.nullish(v.string()),
  polling_district: v.nullish(vElectoralDistrict),
  polling_division: v.nullish(v.string()),
  preferred_school_ids: v.optional(v.unknown()),
  rejection_reason: v.nullish(v.string()),
  residence_verified: v.nullish(v.boolean()),
  school_id: v.nullish(v.pipe(v.string(), v.uuid())),
  submission_method: v.nullish(v.string()),
  village_street: v.nullish(v.string()),
  voter_names: v.optional(v.unknown()),
  wizard_step: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
})

/**
 * UpdateBatchBody
 */
export const vUpdateBatchBody = v.object({
  alumni_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  buddhism_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  catholicism_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  govt_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  hinduism_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  islam_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  proximity_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  sibling_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  special_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  staff_percentage: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  status: v.nullish(vBatchStatus),
  student_allocation: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(
        -2147483648,
        "Invalid value: Expected int32 to be >= -2147483648"
      ),
      v.maxValue(
        2147483647,
        "Invalid value: Expected int32 to be <= 2147483647"
      )
    )
  ),
})

/**
 * UpdateChildBody
 */
export const vUpdateChildBody = v.object({
  birth_certificate_number: v.nullish(v.string()),
  date_of_birth: v.nullish(v.pipe(v.string(), v.isoDate())),
  disability_status: v.nullish(v.boolean()),
  disability_type: v.nullish(v.string()),
  full_name: v.nullish(v.string()),
  gender: v.nullish(vGender),
  medium_of_instruction: v.nullish(vMediumOfInstruction),
  name_with_initials: v.nullish(v.string()),
  nationality: v.nullish(vNationality),
  nic: v.nullish(v.string()),
  passport_number: v.nullish(v.string()),
  photo_url: v.nullish(v.string()),
  religion: v.nullish(vReligion),
})

/**
 * UpdateGuardianBody
 */
export const vUpdateGuardianBody = v.object({
  address_id: v.nullish(v.pipe(v.string(), v.uuid())),
  contact_email: v.nullish(v.string()),
  contact_phone: v.string(),
  employee_id: v.nullish(v.string()),
  full_name: v.string(),
  govt_service_years: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(
        -2147483648,
        "Invalid value: Expected int32 to be >= -2147483648"
      ),
      v.maxValue(
        2147483647,
        "Invalid value: Expected int32 to be <= 2147483647"
      )
    )
  ),
  income_level: v.nullish(vIncomeLevel),
  is_govt_employee: v.boolean(),
  is_past_pupil: v.boolean(),
  is_school_staff: v.boolean(),
  nic_number: v.string(),
  occupation: v.nullish(v.string()),
  past_pupil_highest_grade: v.nullish(v.string()),
  past_pupil_left_reason: v.nullish(v.string()),
  past_pupil_school_id: v.nullish(v.pipe(v.string(), v.uuid())),
  past_pupil_student_id: v.nullish(v.string()),
  past_pupil_year_left: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  relationship_type: vGuardianRelationship,
  staff_school_id: v.nullish(v.pipe(v.string(), v.uuid())),
  staff_type: v.nullish(vStaffType),
  student_id: v.nullish(v.pipe(v.string(), v.uuid())),
  workplace_address: v.nullish(v.string()),
  workplace_name: v.nullish(v.string()),
})

/**
 * UpdateStudentRequest
 */
export const vUpdateStudentRequest = v.object({
  birth_certificate_number: v.nullish(v.string()),
  current_grade: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  date_of_birth: v.pipe(v.string(), v.isoDate()),
  email: v.nullish(v.string()),
  full_name: v.string(),
  gender: vGender,
  medium_of_instruction: vMediumOfInstruction,
  name_with_initials: v.string(),
  nationality: vNationality,
  nic: v.nullish(v.string()),
  passport_number: v.nullish(v.string()),
  phone: v.nullish(v.string()),
  religion: v.nullish(vReligion),
})

/**
 * UploadForm
 */
export const vUploadForm = v.record(v.string(), v.unknown())

/**
 * UploadResponse
 */
export const vUploadResponse = v.object({
  file_name: v.string(),
  key: v.string(),
  size: v.pipe(v.number(), v.integer(), v.minValue(0)),
  url: v.string(),
})

/**
 * UserResponse
 */
export const vUserResponse = v.object({
  email: v.string(),
  id: v.string(),
  role: v.string(),
})

/**
 * WorkspaceAddress
 */
export const vWorkspaceAddress = v.object({
  building: v.nullish(v.string()),
  city: v.string(),
  country: v.string(),
  created_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.110193300Z"
  ),
  full_address: v.string(),
  id: v.pipe(v.string(), v.uuid()),
  name: v.string(),
  postal_code: v.nullish(v.string()),
  state: v.nullish(v.string()),
  street_1: v.string(),
  street_2: v.nullish(v.string()),
})

export const vListBlacklistQuery = v.object({
  guardian_ids: v.nullish(v.array(v.pipe(v.string(), v.uuid()))),
})

export const vListBlacklistResponse = v.array(vBlacklist)

export const vListChildrenQuery = v.object({
  birth_certificate_number: v.nullish(v.string()),
  full_name: v.nullish(v.string()),
  has_student: v.nullish(v.string()),
  nic: v.nullish(v.string()),
  search: v.nullish(v.string()),
})

export const vListChildrenResponse = v.array(vChild)

export const vCreateChildBody2 = vCreateChildBody

/**
 * Child
 */
export const vCreateChildResponse = v.object({
  admission_date: v.nullish(v.pipe(v.string(), v.isoDate())),
  admission_number: v.nullish(v.string()),
  birth_certificate_number: v.nullish(v.string()),
  created_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.064347800Z"
  ),
  created_by: v.nullish(v.pipe(v.string(), v.uuid())),
  current_grade: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  date_of_birth: v.pipe(v.string(), v.isoDate()),
  disability_status: v.optional(v.boolean(), false),
  disability_type: v.nullish(v.string(), null),
  email: v.nullish(v.string()),
  full_name: v.string(),
  gender: vGender,
  id: v.pipe(v.string(), v.uuid()),
  medium_of_instruction: vMediumOfInstruction,
  name_with_initials: v.string(),
  name_with_initials_en: v.nullish(v.string()),
  nationality: vNationality,
  nic: v.nullish(v.string()),
  passport_number: v.nullish(v.string()),
  phone: v.nullish(v.string()),
  photo_url: v.nullish(v.string(), null),
  religion: v.nullish(vReligion),
  status: vStudentStatus,
  student_id: v.nullish(v.pipe(v.string(), v.uuid()), null),
  updated_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.064357400Z"
  ),
  updated_by: v.nullish(v.pipe(v.string(), v.uuid())),
})

export const vGetChildPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vGetChildResponse = vChild

export const vUpdateChildBody2 = vUpdateChildBody

export const vUpdateChildPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vUpdateChildResponse = vChild

export const vGetCounterPath = v.object({
  name: v.string(),
})

export const vGetCounterResponse = vCounterResponse

export const vIncrementCounterPath = v.object({
  name: v.string(),
})

export const vIncrementCounterResponse = vCounterResponse

export const vGetSecureCounterPath = v.object({
  name: v.string(),
})

export const vGetSecureCounterResponse = vCounterResponse

export const vIncrementSecureCounterPath = v.object({
  name: v.string(),
})

export const vIncrementSecureCounterResponse = vCounterResponse

export const vListDistrictsResponse = v.array(vDistrict)

export const vListApplicationsQuery = v.object({
  batch_id: v.nullish(v.string()),
  category: v.nullish(v.string()),
  enrollment_status: v.nullish(v.string()),
  page: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(
        -2147483648,
        "Invalid value: Expected int32 to be >= -2147483648"
      ),
      v.maxValue(
        2147483647,
        "Invalid value: Expected int32 to be <= 2147483647"
      )
    )
  ),
  page_size: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(
        -2147483648,
        "Invalid value: Expected int32 to be >= -2147483648"
      ),
      v.maxValue(
        2147483647,
        "Invalid value: Expected int32 to be <= 2147483647"
      )
    )
  ),
  sort_by: v.nullish(v.string()),
  sort_order: v.nullish(v.string()),
})

export const vListApplicationsResponse = vPaginatedApplicationsResponse

export const vCreateApplicationBody2 = vCreateApplicationBody

/**
 * G1Application
 */
export const vCreateApplicationResponse = v.object({
  age_eligibility_verified: v.boolean(),
  alternative_age_certificate: v.boolean(),
  alternative_age_certificate_ref: v.nullish(v.string()),
  batch_id: v.pipe(v.string(), v.uuid()),
  birth_certificate_verified: v.boolean(),
  category: v.nullish(vG1Category),
  category_verified: v.boolean(),
  child_id: v.optional(
    v.pipe(v.string(), v.uuid()),
    "00000000-0000-0000-0000-000000000000"
  ),
  closer_school_exists: v.nullish(v.boolean()),
  created_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.072643100Z"
  ),
  created_by: v.nullish(v.pipe(v.string(), v.uuid())),
  declaration_agreed: v.boolean(),
  declaration_signed_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
  deleted_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
  electoral_year: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
  enrollment_status: v.optional(vEnrollmentStatus),
  finalized_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
  gn_name: v.nullish(v.string()),
  gn_number: v.nullish(v.string()),
  guardian_id: v.optional(
    v.pipe(v.string(), v.uuid()),
    "00000000-0000-0000-0000-000000000000"
  ),
  household_head_name: v.nullish(v.string()),
  id: v.optional(
    v.pipe(v.string(), v.uuid()),
    "98ad6629-dea7-4419-bd98-bea496916c53"
  ),
  interview_completed: v.boolean(),
  interview_date: v.nullish(v.pipe(v.string(), v.isoDate())),
  ip_address: v.nullish(v.string()),
  list_category: v.nullish(vApplicationListCategory),
  overseas_arrival_date: v.nullish(v.pipe(v.string(), v.isoDate())),
  polling_area: v.nullish(v.string()),
  polling_district: v.nullish(vElectoralDistrict),
  polling_division: v.nullish(v.string()),
  preferred_school_ids: v.optional(v.unknown()),
  rank_number: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(
        -2147483648,
        "Invalid value: Expected int32 to be >= -2147483648"
      ),
      v.maxValue(
        2147483647,
        "Invalid value: Expected int32 to be <= 2147483647"
      )
    )
  ),
  reference_no: v.optional(
    v.string(),
    "DRAFT-8000012d-8ff4-48fb-aeb8-a3c680be7170"
  ),
  rejection_reason: v.nullish(v.string()),
  residence_verified: v.boolean(),
  school_id: v.nullish(v.pipe(v.string(), v.uuid()), null),
  submission_method: v.nullish(v.string()),
  submitted_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
  total_marks: v.nullish(v.pipe(v.string(), v.regex(/^-?[0-9]+(\.[0-9]+)?$/))),
  updated_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.072652400Z"
  ),
  updated_by: v.nullish(v.pipe(v.string(), v.uuid())),
  user_agent: v.nullish(v.string()),
  verified_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
  verified_by: v.nullish(v.pipe(v.string(), v.uuid())),
  village_street: v.nullish(v.string()),
  voter_names: v.optional(v.unknown()),
  wizard_step: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
})

export const vDeleteApplicationPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vDeleteApplicationResponse = vMessageResponse

export const vGetApplicationPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vGetApplicationResponse = vG1Application

export const vUpdateApplicationBody2 = vUpdateApplicationBody

export const vUpdateApplicationPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vUpdateApplicationResponse = vG1Application

export const vSubmitApplicationPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vSubmitApplicationResponse = vG1Application

export const vSaveWizardStepBody = vSaveStepRequest

export const vSaveWizardStepPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vSaveWizardStepResponse = vSaveStepResponse

export const vGetApplicationGuardiansPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vGetApplicationGuardiansResponse2 =
  vGetApplicationGuardiansResponse

export const vSaveGuardiansBody = vSaveGuardiansRequest

export const vSaveGuardiansPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vSaveGuardiansResponse2 = vSaveGuardiansResponse

export const vGetApplicationAddressesPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vGetApplicationAddressesResponse2 =
  vGetApplicationAddressesResponse

export const vSaveAddressesBody = vSaveAddressesRequest

export const vSaveAddressesPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vSaveAddressesResponse2 = vSaveAddressesResponse

export const vGetApplicationSiblingsPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vGetApplicationSiblingsResponse2 = vGetApplicationSiblingsResponse

export const vSaveSiblingsBody = vSaveSiblingsRequest

export const vSaveSiblingsPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vSaveSiblingsResponse2 = vSaveSiblingsResponse

export const vCreateSiblingBody = vCreateSiblingRequest

export const vCreateSiblingPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vCreateSiblingResponse2 = vCreateSiblingResponse

export const vGetApplicationDocumentsPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vGetApplicationDocumentsResponse = vGetDocumentsResponse

export const vSaveApplicationDocumentsBody = vSaveDocumentsRequest

export const vSaveApplicationDocumentsPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vSaveApplicationDocumentsResponse = vSaveDocumentsResponse

export const vListBatchesResponse = v.array(vEnrollmentBatch)

export const vCreateBatchBody2 = vCreateBatchBody

/**
 * EnrollmentBatch
 */
export const vCreateBatchResponse = v.object({
  alumni_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    6
  ),
  appeal_deadline_at: v.nullish(v.pipe(v.string(), v.isoTimestamp()), null),
  batch_code: v.string(),
  batch_name: v.string(),
  buddhism_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    74
  ),
  catholicism_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    12
  ),
  closed_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2027-08-11T08:36:36.086206900Z"
  ),
  created_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.086227200Z"
  ),
  created_by: v.nullish(v.pipe(v.string(), v.uuid()), null),
  enrollment_type: vEnrollmentType,
  finalized_at: v.nullish(v.pipe(v.string(), v.isoTimestamp()), null),
  govt_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    4
  ),
  hinduism_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    0
  ),
  id: v.optional(
    v.pipe(v.string(), v.uuid()),
    "1d41f1c1-e272-417f-826d-1e8cbebdef31"
  ),
  islam_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    14
  ),
  list_published_at: v.nullish(v.pipe(v.string(), v.isoTimestamp()), null),
  opened_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.086199600Z"
  ),
  proximity_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    50
  ),
  sibling_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    14
  ),
  special_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    1
  ),
  staff_percentage: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    ),
    25
  ),
  status: v.optional(vBatchStatus),
  student_allocation: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(
        -2147483648,
        "Invalid value: Expected int32 to be >= -2147483648"
      ),
      v.maxValue(
        2147483647,
        "Invalid value: Expected int32 to be <= 2147483647"
      )
    ),
    200
  ),
  waiting_list_size: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(
        -2147483648,
        "Invalid value: Expected int32 to be >= -2147483648"
      ),
      v.maxValue(
        2147483647,
        "Invalid value: Expected int32 to be <= 2147483647"
      )
    ),
    20
  ),
  year: v.pipe(
    v.number(),
    v.integer(),
    v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
    v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
  ),
})

export const vDeleteBatchPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vDeleteBatchResponse = vMessageResponse

export const vGetBatchPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vGetBatchResponse = vEnrollmentBatch

export const vUpdateBatchBody2 = vUpdateBatchBody

export const vUpdateBatchPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vUpdateBatchResponse = vEnrollmentBatch

export const vListGnDivisionsResponse = v.array(vGnDivisionEntry)

export const vListPollingDivisionsResponse = v.array(vPollingDivisionEntry)

export const vListGuardiansQuery = v.object({
  is_past_pupil: v.nullish(v.string()),
  search: v.nullish(v.string()),
})

export const vListGuardiansResponse = v.array(vGuardianWithChildren)

export const vCreateGuardianBody2 = vCreateGuardianBody

/**
 * Guardian
 */
export const vCreateGuardianResponse = v.object({
  address_id: v.nullish(v.pipe(v.string(), v.uuid()), null),
  contact_email: v.nullish(v.string()),
  contact_phone: v.string(),
  created_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.092948300Z"
  ),
  full_name: v.string(),
  govt_service_years: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(
        -2147483648,
        "Invalid value: Expected int32 to be >= -2147483648"
      ),
      v.maxValue(
        2147483647,
        "Invalid value: Expected int32 to be <= 2147483647"
      )
    )
  ),
  id: v.pipe(v.string(), v.uuid()),
  income_level: v.nullish(vIncomeLevel),
  is_govt_employee: v.boolean(),
  is_past_pupil: v.boolean(),
  is_school_staff: v.boolean(),
  is_sri_lankan_citizen: v.nullish(v.boolean()),
  nic_number: v.string(),
  occupation: v.nullish(v.string()),
  past_pupil_verified: v.boolean(),
  relationship_type: vGuardianRelationship,
  student_id: v.nullish(v.pipe(v.string(), v.uuid())),
  workplace_address: v.nullish(v.string()),
  workplace_name: v.nullish(v.string()),
})

export const vGetGuardianPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vGetGuardianResponse = vGuardian

export const vUpdateGuardianBody2 = vUpdateGuardianBody

export const vUpdateGuardianPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vUpdateGuardianResponse = vGuardian

export const vListAddressesQuery = v.object({
  search: v.nullish(v.string()),
})

export const vListAddressesResponse = v.array(vAddress)

export const vCreateAddressBody2 = vCreateAddressBody

/**
 * Address
 */
export const vCreateAddressResponse = v.object({
  address_line_1: v.string(),
  address_line_2: v.nullish(v.string()),
  city: v.string(),
  created_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.098623100Z"
  ),
  distance_to_school_km: v.nullish(
    v.pipe(v.string(), v.regex(/^-?[0-9]+(\.[0-9]+)?$/))
  ),
  district: v.string(),
  gs_division: v.string(),
  id: v.pipe(v.string(), v.uuid()),
  latitude: v.nullish(v.pipe(v.string(), v.regex(/^-?[0-9]+(\.[0-9]+)?$/))),
  longitude: v.nullish(v.pipe(v.string(), v.regex(/^-?[0-9]+(\.[0-9]+)?$/))),
  ownership_proof: v.nullish(v.string()),
  postal_code: v.nullish(v.string()),
  province: v.string(),
  residence_type: v.nullish(vResidenceType),
  verified_by_map: v.boolean(),
})

export const vGetAddressPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vGetAddressResponse = vAddress

export const vListPastPupilDetailsQuery = v.object({
  guardian_id: v.nullish(v.pipe(v.string(), v.uuid())),
})

export const vListPastPupilDetailsResponse = v.array(vModel)

export const vCreatePastPupilDetailBody2 = vCreatePastPupilDetailBody

/**
 * Model
 */
export const vCreatePastPupilDetailResponse = v.object({
  created_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.100670600Z"
  ),
  guardian_id: v.pipe(v.string(), v.uuid()),
  highest_grade: v.nullish(v.string()),
  id: v.pipe(v.string(), v.uuid()),
  left_reason: v.nullish(v.string()),
  school_id: v.pipe(v.string(), v.uuid()),
  student_id: v.nullish(v.string()),
  verification_method: v.nullish(v.string()),
  verified: v.boolean(),
  year_left: v.nullish(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-32768, "Invalid value: Expected int16 to be >= -32768"),
      v.maxValue(32767, "Invalid value: Expected int16 to be <= 32767")
    )
  ),
})

export const vListSchoolsQuery = v.object({
  search: v.nullish(v.string()),
})

export const vListSchoolsResponse = v.array(vSchoolSummary)

export const vListStaffDetailsQuery = v.object({
  guardian_id: v.nullish(v.pipe(v.string(), v.uuid())),
})

export const vListStaffDetailsResponse = v.array(vStaffDetail)

export const vCreateStaffDetailBody2 = vCreateStaffDetailBody

/**
 * StaffDetail
 */
export const vCreateStaffDetailResponse = v.object({
  created_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.103812700Z"
  ),
  designation: v.nullish(v.string()),
  distance_from_residence_km: v.nullish(
    v.pipe(v.string(), v.regex(/^-?[0-9]+(\.[0-9]+)?$/))
  ),
  employee_id: v.nullish(v.string()),
  employment_type: v.nullish(vStaffEmploymentType),
  guardian_id: v.pipe(v.string(), v.uuid()),
  id: v.pipe(v.string(), v.uuid()),
  is_current: v.boolean(),
  school_id: v.pipe(v.string(), v.uuid()),
  service_end_date: v.nullish(v.pipe(v.string(), v.isoDate())),
  service_start_date: v.nullish(v.pipe(v.string(), v.isoDate())),
  staff_type: v.nullish(vStaffType),
  verification_doc: v.nullish(v.string()),
})

export const vListStudentsQuery = v.object({
  search: v.nullish(v.string()),
})

export const vListStudentsResponse = v.array(vStudentResponse)

export const vCreateStudentBody2 = vCreateStudentBody

export const vCreateStudentResponse2 = vCreateStudentResponse

export const vUpdateStudentBody = vUpdateStudentRequest

export const vUpdateStudentPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vUpdateStudentResponse = vChild

export const vListWorkspaceAddressesQuery = v.object({
  search: v.nullish(v.string()),
})

export const vListWorkspaceAddressesResponse = v.array(vWorkspaceAddress)

export const vCreateWorkspaceAddressBody2 = vCreateWorkspaceAddressBody

/**
 * WorkspaceAddress
 */
export const vCreateWorkspaceAddressResponse = v.object({
  building: v.nullish(v.string()),
  city: v.string(),
  country: v.string(),
  created_at: v.optional(
    v.pipe(v.string(), v.isoTimestamp()),
    "2026-08-11T08:36:36.110057300Z"
  ),
  full_address: v.string(),
  id: v.pipe(v.string(), v.uuid()),
  name: v.string(),
  postal_code: v.nullish(v.string()),
  state: v.nullish(v.string()),
  street_1: v.string(),
  street_2: v.nullish(v.string()),
})

export const vGetWorkspaceAddressPath = v.object({
  id: v.pipe(v.string(), v.uuid()),
})

export const vGetWorkspaceAddressResponse = vWorkspaceAddress

export const vPresignedUploadUrlBody = vPresignedUploadRequest

export const vPresignedUploadUrlResponse = vPresignedUploadResponse

export const vUploadFileBody = vUploadForm

export const vUploadFileResponse = vUploadResponse

export const vDeleteUploadPath = v.object({
  key: v.string(),
})

export const vDeleteUploadResponse = vMessageResponse

export const vRegisterBody = vRegisterRequest

/**
 * AuthResponse
 */
export const vRegisterResponse = v.object({
  access_token: v.string(),
  expires_at: v.pipe(
    v.union([v.number(), v.string(), v.bigint()]),
    v.transform((x) => BigInt(x)),
    v.minValue(
      BigInt("-9223372036854775808"),
      "Invalid value: Expected int64 to be >= -9223372036854775808"
    ),
    v.maxValue(
      BigInt("9223372036854775807"),
      "Invalid value: Expected int64 to be <= 9223372036854775807"
    )
  ),
  refresh_token: v.string(),
})

export const vLoginBody = vLoginRequest

export const vLoginResponse = vAuthResponse

export const vRefreshBody = vRefreshRequest

export const vRefreshResponse = vAuthResponse

export const vLogoutBody = vRefreshRequest

export const vLogoutResponse = vMessageResponse

export const vLogoutAllResponse = vMessageResponse

export const vMeResponse = vUserResponse
