// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

export const vApplicationStatus = v.picklist([
    'Draft',
    'Submitted',
    'DocsPending',
    'UnderVerification',
    'Verified',
    'Marked',
    'Shortlisted',
    'Appealed',
    'Finalized',
    'Admitted',
    'Rejected',
    'Withdrawn'
]);

/**
 * AuthResponse
 */
export const vAuthResponse = v.object({
    access_token: v.string(),
    expires_at: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    refresh_token: v.string()
});

export const vBatchStatus = v.picklist([
    'Open',
    'Closed',
    'Archived'
]);

/**
 * CounterResponse
 */
export const vCounterResponse = v.object({
    name: v.string(),
    value: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))
});

export const vEnrollmentStatus = v.picklist([
    'Draft',
    'Pending',
    'ProvisionallyApproved',
    'Approved',
    'Rejected',
    'Withdrawn',
    'Removed'
]);

export const vEnrollmentType = v.picklist(['G1']);

/**
 * CreateBatchBody
 */
export const vCreateBatchBody = v.object({
    alumni_weight: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767'))),
    enrollment_type: vEnrollmentType,
    govt_weight: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767'))),
    proximity_weight: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767'))),
    sibling_weight: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767'))),
    special_weight: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767'))),
    staff_weight: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767'))),
    student_allocation: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    year: v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767'))
});

/**
 * EnrollmentBatch
 */
export const vEnrollmentBatch = v.object({
    alumni_weight: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767')), 6),
    batch_code: v.string(),
    batch_name: v.string(),
    created_at: v.optional(v.pipe(v.string(), v.isoTimestamp()), '2026-07-19T10:09:57.302133Z'),
    created_by: v.nullish(v.pipe(v.string(), v.uuid()), null),
    enrollment_type: vEnrollmentType,
    govt_weight: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767')), 4),
    id: v.optional(v.pipe(v.string(), v.uuid()), 'c24f5e81-ef5c-4cb4-a8bd-a62feaf4f8f2'),
    proximity_weight: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767')), 50),
    sibling_weight: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767')), 14),
    special_weight: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767')), 1),
    staff_weight: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767')), 25),
    status: v.optional(vBatchStatus),
    student_allocation: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), 200),
    year: v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767'))
});

export const vG1Category = v.picklist([
    'CloseResident',
    'PastPupilChild',
    'Sibling',
    'MOEOrUGCStaffChild',
    'GovernmentTransferOfficerChild',
    'OverseasArrival',
    'ArmedForcesReserved'
]);

export const vGender = v.picklist(['Male', 'Female']);

/**
 * GenerateListsRequest
 */
export const vGenerateListsRequest = v.object({
    batch_id: v.pipe(v.string(), v.uuid())
});

/**
 * LoginRequest
 */
export const vLoginRequest = v.object({
    email: v.string(),
    password: v.string()
});

export const vMediumOfInstruction = v.picklist(['Sinhala', 'Tamil']);

/**
 * MessageResponse
 */
export const vMessageResponse = v.object({
    message: v.string()
});

export const vNationality = v.picklist([
    'SriLankan',
    'DualCitizen',
    'Other'
]);

/**
 * RefreshRequest
 */
export const vRefreshRequest = v.object({
    refresh_token: v.string()
});

/**
 * RegisterRequest
 */
export const vRegisterRequest = v.object({
    email: v.string(),
    password: v.string()
});

export const vReligion = v.picklist([
    'Buddhism',
    'Hinduism',
    'Islam',
    'Christianity',
    'Catholicism',
    'Other'
]);

/**
 * G1Application
 */
export const vG1Application = v.object({
    age_eligibility_verified: v.optional(v.boolean(), false),
    alternative_age_certificate: v.optional(v.boolean(), false),
    alternative_age_certificate_ref: v.nullish(v.string(), null),
    applied_year: v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767')),
    batch_id: v.pipe(v.string(), v.uuid()),
    birth_certificate_number: v.nullish(v.string(), null),
    birth_certificate_verified: v.optional(v.boolean(), false),
    category: vG1Category,
    category_verified: v.optional(v.boolean(), false),
    child_id: v.pipe(v.string(), v.uuid()),
    created_at: v.optional(v.pipe(v.string(), v.isoTimestamp()), '2026-07-19T10:09:57.297950600Z'),
    created_by: v.nullish(v.pipe(v.string(), v.uuid()), null),
    date_of_birth: v.pipe(v.string(), v.isoDate()),
    enrollment_status: v.optional(vEnrollmentStatus),
    finalized_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
    full_name: v.string(),
    gender: vGender,
    guardian_id: v.pipe(v.string(), v.uuid()),
    id: v.optional(v.pipe(v.string(), v.uuid()), '41511ed2-5029-4d7c-98b1-62d448b152f7'),
    interview_completed: v.optional(v.boolean(), false),
    interview_date: v.nullish(v.pipe(v.string(), v.isoDate()), null),
    ip_address: v.nullish(v.string()),
    list_category: v.nullish(v.string()),
    medium_of_instruction: vMediumOfInstruction,
    name_with_initials: v.string(),
    nationality: vNationality,
    overseas_arrival_date: v.nullish(v.pipe(v.string(), v.isoDate()), null),
    rank_number: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    reference_no: v.string(),
    rejection_reason: v.nullish(v.string(), null),
    religion: v.nullish(vReligion),
    residence_verified: v.optional(v.boolean(), false),
    school_id: v.pipe(v.string(), v.uuid()),
    status: v.optional(vApplicationStatus),
    student_id: v.nullish(v.pipe(v.string(), v.uuid()), null),
    submission_method: v.nullish(v.string(), null),
    submitted_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
    total_marks: v.nullish(v.pipe(v.string(), v.regex(/^-?[0-9]+(\.[0-9]+)?$/))),
    updated_at: v.optional(v.pipe(v.string(), v.isoTimestamp()), '2026-07-19T10:09:57.297961700Z'),
    updated_by: v.nullish(v.pipe(v.string(), v.uuid()), null),
    user_agent: v.nullish(v.string()),
    verified_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
    verified_by: v.nullish(v.pipe(v.string(), v.uuid()))
});

/**
 * PaginatedApplicationsResponse
 */
export const vPaginatedApplicationsResponse = v.object({
    items: v.array(vG1Application),
    total: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))
});

export const vSchoolListSummary = v.object({
    main_list_count: v.pipe(v.number(), v.integer(), v.minValue(0)),
    school_id: v.pipe(v.string(), v.uuid()),
    school_name: v.string(),
    waiting_list_count: v.pipe(v.number(), v.integer(), v.minValue(0))
});

/**
 * GenerateListsResponse
 */
export const vGenerateListsResponse = v.object({
    batch_id: v.pipe(v.string(), v.uuid()),
    schools: v.array(vSchoolListSummary),
    total_generated: v.pipe(v.number(), v.integer(), v.minValue(0))
});

/**
 * UpdateBatchBody
 */
export const vUpdateBatchBody = v.object({
    alumni_weight: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767'))),
    govt_weight: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767'))),
    proximity_weight: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767'))),
    sibling_weight: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767'))),
    special_weight: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767'))),
    staff_weight: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767'))),
    status: v.nullish(vBatchStatus),
    student_allocation: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')))
});

/**
 * UploadForm
 */
export const vUploadForm = v.record(v.string(), v.unknown());

/**
 * UploadResponse
 */
export const vUploadResponse = v.object({
    file_name: v.string(),
    key: v.string(),
    size: v.pipe(v.number(), v.integer(), v.minValue(0)),
    url: v.string()
});

/**
 * UserResponse
 */
export const vUserResponse = v.object({
    email: v.string(),
    id: v.string()
});

export const vGetCounterPath = v.object({
    name: v.string()
});

export const vGetCounterResponse = vCounterResponse;

export const vIncrementCounterPath = v.object({
    name: v.string()
});

export const vIncrementCounterResponse = vCounterResponse;

export const vGetSecureCounterPath = v.object({
    name: v.string()
});

export const vGetSecureCounterResponse = vCounterResponse;

export const vIncrementSecureCounterPath = v.object({
    name: v.string()
});

export const vIncrementSecureCounterResponse = vCounterResponse;

export const vListApplicationsQuery = v.object({
    category: v.nullish(v.string()),
    enrollment_status: v.nullish(v.string()),
    full_name: v.nullish(v.string()),
    gender: v.nullish(v.string()),
    medium_of_instruction: v.nullish(v.string()),
    name_with_initials: v.nullish(v.string()),
    nationality: v.nullish(v.string()),
    page: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    page_size: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    sort_by: v.nullish(v.string()),
    sort_order: v.nullish(v.string())
});

export const vListApplicationsResponse = vPaginatedApplicationsResponse;

export const vCreateApplicationBody = vG1Application;

/**
 * G1Application
 */
export const vCreateApplicationResponse = v.object({
    age_eligibility_verified: v.optional(v.boolean(), false),
    alternative_age_certificate: v.optional(v.boolean(), false),
    alternative_age_certificate_ref: v.nullish(v.string(), null),
    applied_year: v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767')),
    batch_id: v.pipe(v.string(), v.uuid()),
    birth_certificate_number: v.nullish(v.string(), null),
    birth_certificate_verified: v.optional(v.boolean(), false),
    category: vG1Category,
    category_verified: v.optional(v.boolean(), false),
    child_id: v.pipe(v.string(), v.uuid()),
    created_at: v.optional(v.pipe(v.string(), v.isoTimestamp()), '2026-07-19T10:09:57.292786Z'),
    created_by: v.nullish(v.pipe(v.string(), v.uuid()), null),
    date_of_birth: v.pipe(v.string(), v.isoDate()),
    enrollment_status: v.optional(vEnrollmentStatus),
    finalized_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
    full_name: v.string(),
    gender: vGender,
    guardian_id: v.pipe(v.string(), v.uuid()),
    id: v.optional(v.pipe(v.string(), v.uuid()), '8600d82d-73e3-41a8-9c14-dc47baeba3fe'),
    interview_completed: v.optional(v.boolean(), false),
    interview_date: v.nullish(v.pipe(v.string(), v.isoDate()), null),
    ip_address: v.nullish(v.string()),
    list_category: v.nullish(v.string()),
    medium_of_instruction: vMediumOfInstruction,
    name_with_initials: v.string(),
    nationality: vNationality,
    overseas_arrival_date: v.nullish(v.pipe(v.string(), v.isoDate()), null),
    rank_number: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    reference_no: v.string(),
    rejection_reason: v.nullish(v.string(), null),
    religion: v.nullish(vReligion),
    residence_verified: v.optional(v.boolean(), false),
    school_id: v.pipe(v.string(), v.uuid()),
    status: v.optional(vApplicationStatus),
    student_id: v.nullish(v.pipe(v.string(), v.uuid()), null),
    submission_method: v.nullish(v.string(), null),
    submitted_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
    total_marks: v.nullish(v.pipe(v.string(), v.regex(/^-?[0-9]+(\.[0-9]+)?$/))),
    updated_at: v.optional(v.pipe(v.string(), v.isoTimestamp()), '2026-07-19T10:09:57.292798900Z'),
    updated_by: v.nullish(v.pipe(v.string(), v.uuid()), null),
    user_agent: v.nullish(v.string()),
    verified_at: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
    verified_by: v.nullish(v.pipe(v.string(), v.uuid()))
});

export const vDeleteApplicationPath = v.object({
    id: v.pipe(v.string(), v.uuid())
});

export const vDeleteApplicationResponse = vMessageResponse;

export const vGetApplicationPath = v.object({
    id: v.pipe(v.string(), v.uuid())
});

export const vGetApplicationResponse = vG1Application;

export const vUpdateApplicationBody = vG1Application;

export const vUpdateApplicationPath = v.object({
    id: v.pipe(v.string(), v.uuid())
});

export const vUpdateApplicationResponse = vG1Application;

export const vSubmitApplicationPath = v.object({
    id: v.pipe(v.string(), v.uuid())
});

export const vSubmitApplicationResponse = vG1Application;

export const vCalculateMarksPath = v.object({
    id: v.pipe(v.string(), v.uuid())
});

export const vCalculateMarksResponse = vG1Application;

export const vGenerateAdmissionListsBody = vGenerateListsRequest;

export const vGenerateAdmissionListsResponse = vGenerateListsResponse;

export const vListBatchesResponse = v.array(vEnrollmentBatch);

export const vCreateBatchBody2 = vCreateBatchBody;

/**
 * EnrollmentBatch
 */
export const vCreateBatchResponse = v.object({
    alumni_weight: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767')), 6),
    batch_code: v.string(),
    batch_name: v.string(),
    created_at: v.optional(v.pipe(v.string(), v.isoTimestamp()), '2026-07-19T10:09:57.300700600Z'),
    created_by: v.nullish(v.pipe(v.string(), v.uuid()), null),
    enrollment_type: vEnrollmentType,
    govt_weight: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767')), 4),
    id: v.optional(v.pipe(v.string(), v.uuid()), '387110fb-0673-4757-982d-4217406b7c4f'),
    proximity_weight: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767')), 50),
    sibling_weight: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767')), 14),
    special_weight: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767')), 1),
    staff_weight: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767')), 25),
    status: v.optional(vBatchStatus),
    student_allocation: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), 200),
    year: v.pipe(v.number(), v.integer(), v.minValue(-32768, 'Invalid value: Expected int16 to be >= -32768'), v.maxValue(32767, 'Invalid value: Expected int16 to be <= 32767'))
});

export const vDeleteBatchPath = v.object({
    id: v.pipe(v.string(), v.uuid())
});

export const vDeleteBatchResponse = vMessageResponse;

export const vGetBatchPath = v.object({
    id: v.pipe(v.string(), v.uuid())
});

export const vGetBatchResponse = vEnrollmentBatch;

export const vUpdateBatchBody2 = vUpdateBatchBody;

export const vUpdateBatchPath = v.object({
    id: v.pipe(v.string(), v.uuid())
});

export const vUpdateBatchResponse = vEnrollmentBatch;

export const vUploadFileBody = vUploadForm;

export const vUploadFileResponse = vUploadResponse;

export const vRegisterBody = vRegisterRequest;

/**
 * AuthResponse
 */
export const vRegisterResponse = v.object({
    access_token: v.string(),
    expires_at: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    refresh_token: v.string()
});

export const vLoginBody = vLoginRequest;

export const vLoginResponse = vAuthResponse;

export const vRefreshBody = vRefreshRequest;

export const vRefreshResponse = vAuthResponse;

export const vLogoutBody = vRefreshRequest;

export const vLogoutResponse = vMessageResponse;

export const vLogoutAllResponse = vMessageResponse;

export const vMeResponse = vUserResponse;
