[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.45"
log = "0.4"
async-trait = "0.1"
sea-orm = { version = "2.0.0-rc", features = ["sqlx-postgres", "runtime-tokio-native-tls", "macros", "with-json", "with-chrono", "with-uuid"] }
sea-orm-migration = { version = "2.0.0-rc", default-features = false, features = ["sqlx-postgres", "runtime-tokio-native-tls"] }
serde = "1.0.228"
uuid = { version = "1.23.5", features = ["v4"] }
apistos = { version = "0.6" }
schemars = { package = "apistos-schemars", version = "0.8", features = ["chrono", "uuid"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
