[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.45"
log = "0.4"
sea-orm = { version = "2.0.0-rc", features = [ "sqlx-postgres", "runtime-tokio-native-tls", "macros","schema-sync","with-json","with-chrono","with-uuid" ,"entity-registry"] }
serde = "1.0.228"
uuid = "1.23.5"
