// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query"

import { client } from "../client.gen"
import {
  createAddress,
  createApplication,
  createBatch,
  createChild,
  createGuardian,
  createPastPupilDetail,
  createSibling,
  createStaffDetail,
  createStudent,
  createWorkspaceAddress,
  deleteApplication,
  deleteBatch,
  deleteUpload,
  getAddress,
  getApplication,
  getApplicationAddresses,
  getApplicationDocuments,
  getApplicationGuardians,
  getApplicationSiblings,
  getBatch,
  getChild,
  getCounter,
  getGuardian,
  getSecureCounter,
  getWorkspaceAddress,
  incrementCounter,
  incrementSecureCounter,
  listAddresses,
  listApplications,
  listBatches,
  listBlacklist,
  listChildren,
  listDistricts,
  listGnDivisions,
  listGuardians,
  listPastPupilDetails,
  listPollingDivisions,
  listSchools,
  listStaffDetails,
  listStudents,
  listWorkspaceAddresses,
  login,
  logout,
  logoutAll,
  me,
  type Options,
  presignedUploadUrl,
  refresh,
  register,
  saveAddresses,
  saveApplicationDocuments,
  saveGuardians,
  saveSiblings,
  saveWizardStep,
  submitApplication,
  updateApplication,
  updateBatch,
  updateChild,
  updateGuardian,
  updateStudent,
  uploadFile,
} from "../sdk.gen"
import type {
  CreateAddressData,
  CreateAddressError,
  CreateAddressResponse,
  CreateApplicationData,
  CreateApplicationError,
  CreateApplicationResponse,
  CreateBatchData,
  CreateBatchError,
  CreateBatchResponse,
  CreateChildData,
  CreateChildError,
  CreateChildResponse,
  CreateGuardianData,
  CreateGuardianError,
  CreateGuardianResponse,
  CreatePastPupilDetailData,
  CreatePastPupilDetailError,
  CreatePastPupilDetailResponse,
  CreateSiblingData,
  CreateSiblingError,
  CreateSiblingResponse2,
  CreateStaffDetailData,
  CreateStaffDetailError,
  CreateStaffDetailResponse,
  CreateStudentData,
  CreateStudentError,
  CreateStudentResponse2,
  CreateWorkspaceAddressData,
  CreateWorkspaceAddressError,
  CreateWorkspaceAddressResponse,
  DeleteApplicationData,
  DeleteApplicationError,
  DeleteApplicationResponse,
  DeleteBatchData,
  DeleteBatchError,
  DeleteBatchResponse,
  DeleteUploadData,
  DeleteUploadError,
  DeleteUploadResponse,
  GetAddressData,
  GetAddressError,
  GetAddressResponse,
  GetApplicationAddressesData,
  GetApplicationAddressesError,
  GetApplicationAddressesResponse2,
  GetApplicationData,
  GetApplicationDocumentsData,
  GetApplicationDocumentsError,
  GetApplicationDocumentsResponse,
  GetApplicationError,
  GetApplicationGuardiansData,
  GetApplicationGuardiansError,
  GetApplicationGuardiansResponse2,
  GetApplicationResponse,
  GetApplicationSiblingsData,
  GetApplicationSiblingsError,
  GetApplicationSiblingsResponse2,
  GetBatchData,
  GetBatchError,
  GetBatchResponse,
  GetChildData,
  GetChildError,
  GetChildResponse,
  GetCounterData,
  GetCounterError,
  GetCounterResponse,
  GetGuardianData,
  GetGuardianError,
  GetGuardianResponse,
  GetSecureCounterData,
  GetSecureCounterError,
  GetSecureCounterResponse,
  GetWorkspaceAddressData,
  GetWorkspaceAddressError,
  GetWorkspaceAddressResponse,
  IncrementCounterData,
  IncrementCounterError,
  IncrementCounterResponse,
  IncrementSecureCounterData,
  IncrementSecureCounterError,
  IncrementSecureCounterResponse,
  ListAddressesData,
  ListAddressesError,
  ListAddressesResponse,
  ListApplicationsData,
  ListApplicationsError,
  ListApplicationsResponse,
  ListBatchesData,
  ListBatchesError,
  ListBatchesResponse,
  ListBlacklistData,
  ListBlacklistError,
  ListBlacklistResponse,
  ListChildrenData,
  ListChildrenError,
  ListChildrenResponse,
  ListDistrictsData,
  ListDistrictsError,
  ListDistrictsResponse,
  ListGnDivisionsData,
  ListGnDivisionsResponse,
  ListGuardiansData,
  ListGuardiansError,
  ListGuardiansResponse,
  ListPastPupilDetailsData,
  ListPastPupilDetailsError,
  ListPastPupilDetailsResponse,
  ListPollingDivisionsData,
  ListPollingDivisionsResponse,
  ListSchoolsData,
  ListSchoolsError,
  ListSchoolsResponse,
  ListStaffDetailsData,
  ListStaffDetailsError,
  ListStaffDetailsResponse,
  ListStudentsData,
  ListStudentsError,
  ListStudentsResponse,
  ListWorkspaceAddressesData,
  ListWorkspaceAddressesError,
  ListWorkspaceAddressesResponse,
  LoginData,
  LoginError,
  LoginResponse,
  LogoutAllData,
  LogoutAllError,
  LogoutAllResponse,
  LogoutData,
  LogoutError,
  LogoutResponse,
  MeData,
  MeError,
  MeResponse,
  PresignedUploadUrlData,
  PresignedUploadUrlError,
  PresignedUploadUrlResponse,
  RefreshData,
  RefreshError,
  RefreshResponse,
  RegisterData,
  RegisterError,
  RegisterResponse,
  SaveAddressesData,
  SaveAddressesError,
  SaveAddressesResponse2,
  SaveApplicationDocumentsData,
  SaveApplicationDocumentsError,
  SaveApplicationDocumentsResponse,
  SaveGuardiansData,
  SaveGuardiansError,
  SaveGuardiansResponse2,
  SaveSiblingsData,
  SaveSiblingsError,
  SaveSiblingsResponse2,
  SaveWizardStepData,
  SaveWizardStepError,
  SaveWizardStepResponse,
  SubmitApplicationData,
  SubmitApplicationError,
  SubmitApplicationResponse,
  UpdateApplicationData,
  UpdateApplicationError,
  UpdateApplicationResponse,
  UpdateBatchData,
  UpdateBatchError,
  UpdateBatchResponse,
  UpdateChildData,
  UpdateChildError,
  UpdateChildResponse,
  UpdateGuardianData,
  UpdateGuardianError,
  UpdateGuardianResponse,
  UpdateStudentData,
  UpdateStudentError,
  UpdateStudentResponse,
  UploadFileData,
  UploadFileError,
  UploadFileResponse,
} from "../types.gen"

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const listBlacklistQueryKey = (options?: Options<ListBlacklistData>) =>
  createQueryKey("listBlacklist", options)

export const listBlacklistOptions = (options?: Options<ListBlacklistData>) =>
  queryOptions<
    ListBlacklistResponse,
    ListBlacklistError,
    ListBlacklistResponse,
    ReturnType<typeof listBlacklistQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listBlacklist({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listBlacklistQueryKey(options),
  })

export const listChildrenQueryKey = (options?: Options<ListChildrenData>) =>
  createQueryKey("listChildren", options)

export const listChildrenOptions = (options?: Options<ListChildrenData>) =>
  queryOptions<
    ListChildrenResponse,
    ListChildrenError,
    ListChildrenResponse,
    ReturnType<typeof listChildrenQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listChildren({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listChildrenQueryKey(options),
  })

export const createChildMutation = (
  options?: Partial<Options<CreateChildData>>
): UseMutationOptions<
  CreateChildResponse,
  CreateChildError,
  Options<CreateChildData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateChildResponse,
    CreateChildError,
    Options<CreateChildData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createChild({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getChildQueryKey = (options: Options<GetChildData>) =>
  createQueryKey("getChild", options)

export const getChildOptions = (options: Options<GetChildData>) =>
  queryOptions<
    GetChildResponse,
    GetChildError,
    GetChildResponse,
    ReturnType<typeof getChildQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getChild({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getChildQueryKey(options),
  })

export const updateChildMutation = (
  options?: Partial<Options<UpdateChildData>>
): UseMutationOptions<
  UpdateChildResponse,
  UpdateChildError,
  Options<UpdateChildData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateChildResponse,
    UpdateChildError,
    Options<UpdateChildData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateChild({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getCounterQueryKey = (options: Options<GetCounterData>) =>
  createQueryKey("getCounter", options)

export const getCounterOptions = (options: Options<GetCounterData>) =>
  queryOptions<
    GetCounterResponse,
    GetCounterError,
    GetCounterResponse,
    ReturnType<typeof getCounterQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCounter({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getCounterQueryKey(options),
  })

export const incrementCounterMutation = (
  options?: Partial<Options<IncrementCounterData>>
): UseMutationOptions<
  IncrementCounterResponse,
  IncrementCounterError,
  Options<IncrementCounterData>
> => {
  const mutationOptions: UseMutationOptions<
    IncrementCounterResponse,
    IncrementCounterError,
    Options<IncrementCounterData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await incrementCounter({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getSecureCounterQueryKey = (
  options: Options<GetSecureCounterData>
) => createQueryKey("getSecureCounter", options)

export const getSecureCounterOptions = (
  options: Options<GetSecureCounterData>
) =>
  queryOptions<
    GetSecureCounterResponse,
    GetSecureCounterError,
    GetSecureCounterResponse,
    ReturnType<typeof getSecureCounterQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSecureCounter({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getSecureCounterQueryKey(options),
  })

export const incrementSecureCounterMutation = (
  options?: Partial<Options<IncrementSecureCounterData>>
): UseMutationOptions<
  IncrementSecureCounterResponse,
  IncrementSecureCounterError,
  Options<IncrementSecureCounterData>
> => {
  const mutationOptions: UseMutationOptions<
    IncrementSecureCounterResponse,
    IncrementSecureCounterError,
    Options<IncrementSecureCounterData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await incrementSecureCounter({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listDistrictsQueryKey = (options?: Options<ListDistrictsData>) =>
  createQueryKey("listDistricts", options)

export const listDistrictsOptions = (options?: Options<ListDistrictsData>) =>
  queryOptions<
    ListDistrictsResponse,
    ListDistrictsError,
    ListDistrictsResponse,
    ReturnType<typeof listDistrictsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listDistricts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listDistrictsQueryKey(options),
  })

export const listApplicationsQueryKey = (
  options?: Options<ListApplicationsData>
) => createQueryKey("listApplications", options)

export const listApplicationsOptions = (
  options?: Options<ListApplicationsData>
) =>
  queryOptions<
    ListApplicationsResponse,
    ListApplicationsError,
    ListApplicationsResponse,
    ReturnType<typeof listApplicationsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listApplications({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listApplicationsQueryKey(options),
  })

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K
) => {
  const params = { ...queryKey[0] }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const listApplicationsInfiniteQueryKey = (
  options?: Options<ListApplicationsData>
): QueryKey<Options<ListApplicationsData>> =>
  createQueryKey("listApplications", options, true)

export const listApplicationsInfiniteOptions = (
  options?: Options<ListApplicationsData>
) => {
  const opts = infiniteQueryOptions<
    ListApplicationsResponse,
    ListApplicationsError,
    InfiniteData<ListApplicationsResponse>,
    QueryKey<Options<ListApplicationsData>>,
    | number
    | null
    | Pick<
        QueryKey<Options<ListApplicationsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListApplicationsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listApplications({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listApplicationsInfiniteQueryKey(options),
    }
  )
  return opts as Omit<typeof opts, "initialData">
}

export const createApplicationMutation = (
  options?: Partial<Options<CreateApplicationData>>
): UseMutationOptions<
  CreateApplicationResponse,
  CreateApplicationError,
  Options<CreateApplicationData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateApplicationResponse,
    CreateApplicationError,
    Options<CreateApplicationData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createApplication({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const deleteApplicationMutation = (
  options?: Partial<Options<DeleteApplicationData>>
): UseMutationOptions<
  DeleteApplicationResponse,
  DeleteApplicationError,
  Options<DeleteApplicationData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApplicationResponse,
    DeleteApplicationError,
    Options<DeleteApplicationData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApplication({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApplicationQueryKey = (options: Options<GetApplicationData>) =>
  createQueryKey("getApplication", options)

export const getApplicationOptions = (options: Options<GetApplicationData>) =>
  queryOptions<
    GetApplicationResponse,
    GetApplicationError,
    GetApplicationResponse,
    ReturnType<typeof getApplicationQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApplication({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApplicationQueryKey(options),
  })

export const updateApplicationMutation = (
  options?: Partial<Options<UpdateApplicationData>>
): UseMutationOptions<
  UpdateApplicationResponse,
  UpdateApplicationError,
  Options<UpdateApplicationData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateApplicationResponse,
    UpdateApplicationError,
    Options<UpdateApplicationData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateApplication({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const submitApplicationMutation = (
  options?: Partial<Options<SubmitApplicationData>>
): UseMutationOptions<
  SubmitApplicationResponse,
  SubmitApplicationError,
  Options<SubmitApplicationData>
> => {
  const mutationOptions: UseMutationOptions<
    SubmitApplicationResponse,
    SubmitApplicationError,
    Options<SubmitApplicationData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await submitApplication({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const saveWizardStepMutation = (
  options?: Partial<Options<SaveWizardStepData>>
): UseMutationOptions<
  SaveWizardStepResponse,
  SaveWizardStepError,
  Options<SaveWizardStepData>
> => {
  const mutationOptions: UseMutationOptions<
    SaveWizardStepResponse,
    SaveWizardStepError,
    Options<SaveWizardStepData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await saveWizardStep({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApplicationGuardiansQueryKey = (
  options: Options<GetApplicationGuardiansData>
) => createQueryKey("getApplicationGuardians", options)

export const getApplicationGuardiansOptions = (
  options: Options<GetApplicationGuardiansData>
) =>
  queryOptions<
    GetApplicationGuardiansResponse2,
    GetApplicationGuardiansError,
    GetApplicationGuardiansResponse2,
    ReturnType<typeof getApplicationGuardiansQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApplicationGuardians({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApplicationGuardiansQueryKey(options),
  })

export const saveGuardiansMutation = (
  options?: Partial<Options<SaveGuardiansData>>
): UseMutationOptions<
  SaveGuardiansResponse2,
  SaveGuardiansError,
  Options<SaveGuardiansData>
> => {
  const mutationOptions: UseMutationOptions<
    SaveGuardiansResponse2,
    SaveGuardiansError,
    Options<SaveGuardiansData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await saveGuardians({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApplicationAddressesQueryKey = (
  options: Options<GetApplicationAddressesData>
) => createQueryKey("getApplicationAddresses", options)

export const getApplicationAddressesOptions = (
  options: Options<GetApplicationAddressesData>
) =>
  queryOptions<
    GetApplicationAddressesResponse2,
    GetApplicationAddressesError,
    GetApplicationAddressesResponse2,
    ReturnType<typeof getApplicationAddressesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApplicationAddresses({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApplicationAddressesQueryKey(options),
  })

export const saveAddressesMutation = (
  options?: Partial<Options<SaveAddressesData>>
): UseMutationOptions<
  SaveAddressesResponse2,
  SaveAddressesError,
  Options<SaveAddressesData>
> => {
  const mutationOptions: UseMutationOptions<
    SaveAddressesResponse2,
    SaveAddressesError,
    Options<SaveAddressesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await saveAddresses({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApplicationSiblingsQueryKey = (
  options: Options<GetApplicationSiblingsData>
) => createQueryKey("getApplicationSiblings", options)

export const getApplicationSiblingsOptions = (
  options: Options<GetApplicationSiblingsData>
) =>
  queryOptions<
    GetApplicationSiblingsResponse2,
    GetApplicationSiblingsError,
    GetApplicationSiblingsResponse2,
    ReturnType<typeof getApplicationSiblingsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApplicationSiblings({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApplicationSiblingsQueryKey(options),
  })

export const saveSiblingsMutation = (
  options?: Partial<Options<SaveSiblingsData>>
): UseMutationOptions<
  SaveSiblingsResponse2,
  SaveSiblingsError,
  Options<SaveSiblingsData>
> => {
  const mutationOptions: UseMutationOptions<
    SaveSiblingsResponse2,
    SaveSiblingsError,
    Options<SaveSiblingsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await saveSiblings({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const createSiblingMutation = (
  options?: Partial<Options<CreateSiblingData>>
): UseMutationOptions<
  CreateSiblingResponse2,
  CreateSiblingError,
  Options<CreateSiblingData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateSiblingResponse2,
    CreateSiblingError,
    Options<CreateSiblingData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createSibling({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApplicationDocumentsQueryKey = (
  options: Options<GetApplicationDocumentsData>
) => createQueryKey("getApplicationDocuments", options)

export const getApplicationDocumentsOptions = (
  options: Options<GetApplicationDocumentsData>
) =>
  queryOptions<
    GetApplicationDocumentsResponse,
    GetApplicationDocumentsError,
    GetApplicationDocumentsResponse,
    ReturnType<typeof getApplicationDocumentsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApplicationDocuments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApplicationDocumentsQueryKey(options),
  })

export const saveApplicationDocumentsMutation = (
  options?: Partial<Options<SaveApplicationDocumentsData>>
): UseMutationOptions<
  SaveApplicationDocumentsResponse,
  SaveApplicationDocumentsError,
  Options<SaveApplicationDocumentsData>
> => {
  const mutationOptions: UseMutationOptions<
    SaveApplicationDocumentsResponse,
    SaveApplicationDocumentsError,
    Options<SaveApplicationDocumentsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await saveApplicationDocuments({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listBatchesQueryKey = (options?: Options<ListBatchesData>) =>
  createQueryKey("listBatches", options)

export const listBatchesOptions = (options?: Options<ListBatchesData>) =>
  queryOptions<
    ListBatchesResponse,
    ListBatchesError,
    ListBatchesResponse,
    ReturnType<typeof listBatchesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listBatches({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listBatchesQueryKey(options),
  })

export const createBatchMutation = (
  options?: Partial<Options<CreateBatchData>>
): UseMutationOptions<
  CreateBatchResponse,
  CreateBatchError,
  Options<CreateBatchData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateBatchResponse,
    CreateBatchError,
    Options<CreateBatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createBatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const deleteBatchMutation = (
  options?: Partial<Options<DeleteBatchData>>
): UseMutationOptions<
  DeleteBatchResponse,
  DeleteBatchError,
  Options<DeleteBatchData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteBatchResponse,
    DeleteBatchError,
    Options<DeleteBatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteBatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getBatchQueryKey = (options: Options<GetBatchData>) =>
  createQueryKey("getBatch", options)

export const getBatchOptions = (options: Options<GetBatchData>) =>
  queryOptions<
    GetBatchResponse,
    GetBatchError,
    GetBatchResponse,
    ReturnType<typeof getBatchQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBatch({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getBatchQueryKey(options),
  })

export const updateBatchMutation = (
  options?: Partial<Options<UpdateBatchData>>
): UseMutationOptions<
  UpdateBatchResponse,
  UpdateBatchError,
  Options<UpdateBatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateBatchResponse,
    UpdateBatchError,
    Options<UpdateBatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateBatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listGnDivisionsQueryKey = (
  options?: Options<ListGnDivisionsData>
) => createQueryKey("listGnDivisions", options)

export const listGnDivisionsOptions = (
  options?: Options<ListGnDivisionsData>
) =>
  queryOptions<
    ListGnDivisionsResponse,
    DefaultError,
    ListGnDivisionsResponse,
    ReturnType<typeof listGnDivisionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listGnDivisions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listGnDivisionsQueryKey(options),
  })

export const listPollingDivisionsQueryKey = (
  options?: Options<ListPollingDivisionsData>
) => createQueryKey("listPollingDivisions", options)

export const listPollingDivisionsOptions = (
  options?: Options<ListPollingDivisionsData>
) =>
  queryOptions<
    ListPollingDivisionsResponse,
    DefaultError,
    ListPollingDivisionsResponse,
    ReturnType<typeof listPollingDivisionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listPollingDivisions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listPollingDivisionsQueryKey(options),
  })

export const listGuardiansQueryKey = (options?: Options<ListGuardiansData>) =>
  createQueryKey("listGuardians", options)

export const listGuardiansOptions = (options?: Options<ListGuardiansData>) =>
  queryOptions<
    ListGuardiansResponse,
    ListGuardiansError,
    ListGuardiansResponse,
    ReturnType<typeof listGuardiansQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listGuardians({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listGuardiansQueryKey(options),
  })

export const createGuardianMutation = (
  options?: Partial<Options<CreateGuardianData>>
): UseMutationOptions<
  CreateGuardianResponse,
  CreateGuardianError,
  Options<CreateGuardianData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateGuardianResponse,
    CreateGuardianError,
    Options<CreateGuardianData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createGuardian({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getGuardianQueryKey = (options: Options<GetGuardianData>) =>
  createQueryKey("getGuardian", options)

export const getGuardianOptions = (options: Options<GetGuardianData>) =>
  queryOptions<
    GetGuardianResponse,
    GetGuardianError,
    GetGuardianResponse,
    ReturnType<typeof getGuardianQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getGuardian({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getGuardianQueryKey(options),
  })

export const updateGuardianMutation = (
  options?: Partial<Options<UpdateGuardianData>>
): UseMutationOptions<
  UpdateGuardianResponse,
  UpdateGuardianError,
  Options<UpdateGuardianData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateGuardianResponse,
    UpdateGuardianError,
    Options<UpdateGuardianData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateGuardian({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listAddressesQueryKey = (options?: Options<ListAddressesData>) =>
  createQueryKey("listAddresses", options)

export const listAddressesOptions = (options?: Options<ListAddressesData>) =>
  queryOptions<
    ListAddressesResponse,
    ListAddressesError,
    ListAddressesResponse,
    ReturnType<typeof listAddressesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listAddresses({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listAddressesQueryKey(options),
  })

export const createAddressMutation = (
  options?: Partial<Options<CreateAddressData>>
): UseMutationOptions<
  CreateAddressResponse,
  CreateAddressError,
  Options<CreateAddressData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateAddressResponse,
    CreateAddressError,
    Options<CreateAddressData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createAddress({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getAddressQueryKey = (options: Options<GetAddressData>) =>
  createQueryKey("getAddress", options)

export const getAddressOptions = (options: Options<GetAddressData>) =>
  queryOptions<
    GetAddressResponse,
    GetAddressError,
    GetAddressResponse,
    ReturnType<typeof getAddressQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAddress({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getAddressQueryKey(options),
  })

export const listPastPupilDetailsQueryKey = (
  options?: Options<ListPastPupilDetailsData>
) => createQueryKey("listPastPupilDetails", options)

export const listPastPupilDetailsOptions = (
  options?: Options<ListPastPupilDetailsData>
) =>
  queryOptions<
    ListPastPupilDetailsResponse,
    ListPastPupilDetailsError,
    ListPastPupilDetailsResponse,
    ReturnType<typeof listPastPupilDetailsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listPastPupilDetails({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listPastPupilDetailsQueryKey(options),
  })

export const createPastPupilDetailMutation = (
  options?: Partial<Options<CreatePastPupilDetailData>>
): UseMutationOptions<
  CreatePastPupilDetailResponse,
  CreatePastPupilDetailError,
  Options<CreatePastPupilDetailData>
> => {
  const mutationOptions: UseMutationOptions<
    CreatePastPupilDetailResponse,
    CreatePastPupilDetailError,
    Options<CreatePastPupilDetailData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createPastPupilDetail({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listSchoolsQueryKey = (options?: Options<ListSchoolsData>) =>
  createQueryKey("listSchools", options)

export const listSchoolsOptions = (options?: Options<ListSchoolsData>) =>
  queryOptions<
    ListSchoolsResponse,
    ListSchoolsError,
    ListSchoolsResponse,
    ReturnType<typeof listSchoolsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listSchools({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listSchoolsQueryKey(options),
  })

export const listStaffDetailsQueryKey = (
  options?: Options<ListStaffDetailsData>
) => createQueryKey("listStaffDetails", options)

export const listStaffDetailsOptions = (
  options?: Options<ListStaffDetailsData>
) =>
  queryOptions<
    ListStaffDetailsResponse,
    ListStaffDetailsError,
    ListStaffDetailsResponse,
    ReturnType<typeof listStaffDetailsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listStaffDetails({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listStaffDetailsQueryKey(options),
  })

export const createStaffDetailMutation = (
  options?: Partial<Options<CreateStaffDetailData>>
): UseMutationOptions<
  CreateStaffDetailResponse,
  CreateStaffDetailError,
  Options<CreateStaffDetailData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateStaffDetailResponse,
    CreateStaffDetailError,
    Options<CreateStaffDetailData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createStaffDetail({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listStudentsQueryKey = (options?: Options<ListStudentsData>) =>
  createQueryKey("listStudents", options)

export const listStudentsOptions = (options?: Options<ListStudentsData>) =>
  queryOptions<
    ListStudentsResponse,
    ListStudentsError,
    ListStudentsResponse,
    ReturnType<typeof listStudentsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listStudents({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listStudentsQueryKey(options),
  })

export const createStudentMutation = (
  options?: Partial<Options<CreateStudentData>>
): UseMutationOptions<
  CreateStudentResponse2,
  CreateStudentError,
  Options<CreateStudentData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateStudentResponse2,
    CreateStudentError,
    Options<CreateStudentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createStudent({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const updateStudentMutation = (
  options?: Partial<Options<UpdateStudentData>>
): UseMutationOptions<
  UpdateStudentResponse,
  UpdateStudentError,
  Options<UpdateStudentData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateStudentResponse,
    UpdateStudentError,
    Options<UpdateStudentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateStudent({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listWorkspaceAddressesQueryKey = (
  options?: Options<ListWorkspaceAddressesData>
) => createQueryKey("listWorkspaceAddresses", options)

export const listWorkspaceAddressesOptions = (
  options?: Options<ListWorkspaceAddressesData>
) =>
  queryOptions<
    ListWorkspaceAddressesResponse,
    ListWorkspaceAddressesError,
    ListWorkspaceAddressesResponse,
    ReturnType<typeof listWorkspaceAddressesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listWorkspaceAddresses({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listWorkspaceAddressesQueryKey(options),
  })

export const createWorkspaceAddressMutation = (
  options?: Partial<Options<CreateWorkspaceAddressData>>
): UseMutationOptions<
  CreateWorkspaceAddressResponse,
  CreateWorkspaceAddressError,
  Options<CreateWorkspaceAddressData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateWorkspaceAddressResponse,
    CreateWorkspaceAddressError,
    Options<CreateWorkspaceAddressData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createWorkspaceAddress({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getWorkspaceAddressQueryKey = (
  options: Options<GetWorkspaceAddressData>
) => createQueryKey("getWorkspaceAddress", options)

export const getWorkspaceAddressOptions = (
  options: Options<GetWorkspaceAddressData>
) =>
  queryOptions<
    GetWorkspaceAddressResponse,
    GetWorkspaceAddressError,
    GetWorkspaceAddressResponse,
    ReturnType<typeof getWorkspaceAddressQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkspaceAddress({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getWorkspaceAddressQueryKey(options),
  })

export const presignedUploadUrlMutation = (
  options?: Partial<Options<PresignedUploadUrlData>>
): UseMutationOptions<
  PresignedUploadUrlResponse,
  PresignedUploadUrlError,
  Options<PresignedUploadUrlData>
> => {
  const mutationOptions: UseMutationOptions<
    PresignedUploadUrlResponse,
    PresignedUploadUrlError,
    Options<PresignedUploadUrlData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await presignedUploadUrl({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const uploadFileMutation = (
  options?: Partial<Options<UploadFileData>>
): UseMutationOptions<
  UploadFileResponse,
  UploadFileError,
  Options<UploadFileData>
> => {
  const mutationOptions: UseMutationOptions<
    UploadFileResponse,
    UploadFileError,
    Options<UploadFileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await uploadFile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const deleteUploadMutation = (
  options?: Partial<Options<DeleteUploadData>>
): UseMutationOptions<
  DeleteUploadResponse,
  DeleteUploadError,
  Options<DeleteUploadData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteUploadResponse,
    DeleteUploadError,
    Options<DeleteUploadData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteUpload({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const registerMutation = (
  options?: Partial<Options<RegisterData>>
): UseMutationOptions<
  RegisterResponse,
  RegisterError,
  Options<RegisterData>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterResponse,
    RegisterError,
    Options<RegisterData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await register({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const loginMutation = (
  options?: Partial<Options<LoginData>>
): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
  const mutationOptions: UseMutationOptions<
    LoginResponse,
    LoginError,
    Options<LoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await login({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const refreshMutation = (
  options?: Partial<Options<RefreshData>>
): UseMutationOptions<RefreshResponse, RefreshError, Options<RefreshData>> => {
  const mutationOptions: UseMutationOptions<
    RefreshResponse,
    RefreshError,
    Options<RefreshData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await refresh({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const logoutMutation = (
  options?: Partial<Options<LogoutData>>
): UseMutationOptions<LogoutResponse, LogoutError, Options<LogoutData>> => {
  const mutationOptions: UseMutationOptions<
    LogoutResponse,
    LogoutError,
    Options<LogoutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await logout({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const logoutAllMutation = (
  options?: Partial<Options<LogoutAllData>>
): UseMutationOptions<
  LogoutAllResponse,
  LogoutAllError,
  Options<LogoutAllData>
> => {
  const mutationOptions: UseMutationOptions<
    LogoutAllResponse,
    LogoutAllError,
    Options<LogoutAllData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await logoutAll({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const meQueryKey = (options?: Options<MeData>) =>
  createQueryKey("me", options)

export const meOptions = (options?: Options<MeData>) =>
  queryOptions<MeResponse, MeError, MeResponse, ReturnType<typeof meQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await me({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: meQueryKey(options),
  })
