// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createBatch, createEnrollment, deleteBatch, deleteEnrollment, getBatch, getCounter, getEnrollment, getSecureCounter, incrementCounter, incrementSecureCounter, listBatches, listEnrollments, login, logout, logoutAll, me, type Options, refresh, register, updateBatch, updateEnrollment, uploadFile } from '../sdk.gen';
import type { CreateBatchData, CreateBatchResponse, CreateEnrollmentData, CreateEnrollmentResponse, DeleteBatchData, DeleteBatchResponse, DeleteEnrollmentData, DeleteEnrollmentResponse, GetBatchData, GetBatchResponse, GetCounterData, GetCounterResponse, GetEnrollmentData, GetEnrollmentResponse, GetSecureCounterData, GetSecureCounterResponse, IncrementCounterData, IncrementCounterResponse, IncrementSecureCounterData, IncrementSecureCounterResponse, ListBatchesData, ListBatchesResponse, ListEnrollmentsData, ListEnrollmentsResponse, LoginData, LoginResponse, LogoutAllData, LogoutAllResponse, LogoutData, LogoutResponse, MeData, MeResponse, RefreshData, RefreshResponse, RegisterData, RegisterResponse, UpdateBatchData, UpdateBatchResponse, UpdateEnrollmentData, UpdateEnrollmentResponse, UploadFileData, UploadFileResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getCounterQueryKey = (options: Options<GetCounterData>) => createQueryKey('getCounter', options);

export const getCounterOptions = (options: Options<GetCounterData>) => queryOptions<GetCounterResponse, DefaultError, GetCounterResponse, ReturnType<typeof getCounterQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCounter({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCounterQueryKey(options)
});

export const incrementCounterMutation = (options?: Partial<Options<IncrementCounterData>>): UseMutationOptions<IncrementCounterResponse, DefaultError, Options<IncrementCounterData>> => {
    const mutationOptions: UseMutationOptions<IncrementCounterResponse, DefaultError, Options<IncrementCounterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await incrementCounter({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSecureCounterQueryKey = (options: Options<GetSecureCounterData>) => createQueryKey('getSecureCounter', options);

export const getSecureCounterOptions = (options: Options<GetSecureCounterData>) => queryOptions<GetSecureCounterResponse, DefaultError, GetSecureCounterResponse, ReturnType<typeof getSecureCounterQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSecureCounter({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSecureCounterQueryKey(options)
});

export const incrementSecureCounterMutation = (options?: Partial<Options<IncrementSecureCounterData>>): UseMutationOptions<IncrementSecureCounterResponse, DefaultError, Options<IncrementSecureCounterData>> => {
    const mutationOptions: UseMutationOptions<IncrementSecureCounterResponse, DefaultError, Options<IncrementSecureCounterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await incrementSecureCounter({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listEnrollmentsQueryKey = (options?: Options<ListEnrollmentsData>) => createQueryKey('listEnrollments', options);

export const listEnrollmentsOptions = (options?: Options<ListEnrollmentsData>) => queryOptions<ListEnrollmentsResponse, DefaultError, ListEnrollmentsResponse, ReturnType<typeof listEnrollmentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listEnrollments({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listEnrollmentsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listEnrollmentsInfiniteQueryKey = (options?: Options<ListEnrollmentsData>): QueryKey<Options<ListEnrollmentsData>> => createQueryKey('listEnrollments', options, true);

export const listEnrollmentsInfiniteOptions = (options?: Options<ListEnrollmentsData>) => {
    const opts = infiniteQueryOptions<ListEnrollmentsResponse, DefaultError, InfiniteData<ListEnrollmentsResponse>, QueryKey<Options<ListEnrollmentsData>>, number | null | Pick<QueryKey<Options<ListEnrollmentsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListEnrollmentsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await listEnrollments({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listEnrollmentsInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const createEnrollmentMutation = (options?: Partial<Options<CreateEnrollmentData>>): UseMutationOptions<CreateEnrollmentResponse, DefaultError, Options<CreateEnrollmentData>> => {
    const mutationOptions: UseMutationOptions<CreateEnrollmentResponse, DefaultError, Options<CreateEnrollmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createEnrollment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteEnrollmentMutation = (options?: Partial<Options<DeleteEnrollmentData>>): UseMutationOptions<DeleteEnrollmentResponse, DefaultError, Options<DeleteEnrollmentData>> => {
    const mutationOptions: UseMutationOptions<DeleteEnrollmentResponse, DefaultError, Options<DeleteEnrollmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteEnrollment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getEnrollmentQueryKey = (options: Options<GetEnrollmentData>) => createQueryKey('getEnrollment', options);

export const getEnrollmentOptions = (options: Options<GetEnrollmentData>) => queryOptions<GetEnrollmentResponse, DefaultError, GetEnrollmentResponse, ReturnType<typeof getEnrollmentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getEnrollment({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getEnrollmentQueryKey(options)
});

export const updateEnrollmentMutation = (options?: Partial<Options<UpdateEnrollmentData>>): UseMutationOptions<UpdateEnrollmentResponse, DefaultError, Options<UpdateEnrollmentData>> => {
    const mutationOptions: UseMutationOptions<UpdateEnrollmentResponse, DefaultError, Options<UpdateEnrollmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateEnrollment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listBatchesQueryKey = (options?: Options<ListBatchesData>) => createQueryKey('listBatches', options);

export const listBatchesOptions = (options?: Options<ListBatchesData>) => queryOptions<ListBatchesResponse, DefaultError, ListBatchesResponse, ReturnType<typeof listBatchesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listBatches({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listBatchesQueryKey(options)
});

export const createBatchMutation = (options?: Partial<Options<CreateBatchData>>): UseMutationOptions<CreateBatchResponse, DefaultError, Options<CreateBatchData>> => {
    const mutationOptions: UseMutationOptions<CreateBatchResponse, DefaultError, Options<CreateBatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createBatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteBatchMutation = (options?: Partial<Options<DeleteBatchData>>): UseMutationOptions<DeleteBatchResponse, DefaultError, Options<DeleteBatchData>> => {
    const mutationOptions: UseMutationOptions<DeleteBatchResponse, DefaultError, Options<DeleteBatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteBatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getBatchQueryKey = (options: Options<GetBatchData>) => createQueryKey('getBatch', options);

export const getBatchOptions = (options: Options<GetBatchData>) => queryOptions<GetBatchResponse, DefaultError, GetBatchResponse, ReturnType<typeof getBatchQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBatch({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBatchQueryKey(options)
});

export const updateBatchMutation = (options?: Partial<Options<UpdateBatchData>>): UseMutationOptions<UpdateBatchResponse, DefaultError, Options<UpdateBatchData>> => {
    const mutationOptions: UseMutationOptions<UpdateBatchResponse, DefaultError, Options<UpdateBatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateBatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const uploadFileMutation = (options?: Partial<Options<UploadFileData>>): UseMutationOptions<UploadFileResponse, DefaultError, Options<UploadFileData>> => {
    const mutationOptions: UseMutationOptions<UploadFileResponse, DefaultError, Options<UploadFileData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadFile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const registerMutation = (options?: Partial<Options<RegisterData>>): UseMutationOptions<RegisterResponse, DefaultError, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<RegisterResponse, DefaultError, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, DefaultError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, DefaultError, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const refreshMutation = (options?: Partial<Options<RefreshData>>): UseMutationOptions<RefreshResponse, DefaultError, Options<RefreshData>> => {
    const mutationOptions: UseMutationOptions<RefreshResponse, DefaultError, Options<RefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await refresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const logoutAllMutation = (options?: Partial<Options<LogoutAllData>>): UseMutationOptions<LogoutAllResponse, DefaultError, Options<LogoutAllData>> => {
    const mutationOptions: UseMutationOptions<LogoutAllResponse, DefaultError, Options<LogoutAllData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logoutAll({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const meQueryKey = (options?: Options<MeData>) => createQueryKey('me', options);

export const meOptions = (options?: Options<MeData>) => queryOptions<MeResponse, DefaultError, MeResponse, ReturnType<typeof meQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await me({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: meQueryKey(options)
});
