// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getCounter, getSecureCounter, incrementCounter, incrementSecureCounter, login, logout, logoutAll, me, type Options, refresh, register, uploadFile } from '../sdk.gen';
import type { GetCounterData, GetCounterError, GetCounterResponse, GetSecureCounterData, GetSecureCounterError, GetSecureCounterResponse, IncrementCounterData, IncrementCounterError, IncrementCounterResponse, IncrementSecureCounterData, IncrementSecureCounterError, IncrementSecureCounterResponse, LoginData, LoginError, LoginResponse, LogoutAllData, LogoutAllError, LogoutAllResponse, LogoutData, LogoutError, LogoutResponse, MeData, MeError, MeResponse, RefreshData, RefreshError, RefreshResponse, RegisterData, RegisterError, RegisterResponse, UploadFileData, UploadFileError, UploadFileResponse } from '../types.gen';

export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<LogoutResponse, LogoutError, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<LogoutResponse, LogoutError, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const logoutAllMutation = (options?: Partial<Options<LogoutAllData>>): UseMutationOptions<LogoutAllResponse, LogoutAllError, Options<LogoutAllData>> => {
    const mutationOptions: UseMutationOptions<LogoutAllResponse, LogoutAllError, Options<LogoutAllData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logoutAll({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const meQueryKey = (options?: Options<MeData>) => createQueryKey('me', options);

export const meOptions = (options?: Options<MeData>) => queryOptions<MeResponse, MeError, MeResponse, ReturnType<typeof meQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await me({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: meQueryKey(options)
});

export const refreshMutation = (options?: Partial<Options<RefreshData>>): UseMutationOptions<RefreshResponse, RefreshError, Options<RefreshData>> => {
    const mutationOptions: UseMutationOptions<RefreshResponse, RefreshError, Options<RefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await refresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const registerMutation = (options?: Partial<Options<RegisterData>>): UseMutationOptions<RegisterResponse, RegisterError, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<RegisterResponse, RegisterError, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSecureCounterQueryKey = (options: Options<GetSecureCounterData>) => createQueryKey('getSecureCounter', options);

export const getSecureCounterOptions = (options: Options<GetSecureCounterData>) => queryOptions<GetSecureCounterResponse, GetSecureCounterError, GetSecureCounterResponse, ReturnType<typeof getSecureCounterQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSecureCounter({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSecureCounterQueryKey(options)
});

export const incrementSecureCounterMutation = (options?: Partial<Options<IncrementSecureCounterData>>): UseMutationOptions<IncrementSecureCounterResponse, IncrementSecureCounterError, Options<IncrementSecureCounterData>> => {
    const mutationOptions: UseMutationOptions<IncrementSecureCounterResponse, IncrementSecureCounterError, Options<IncrementSecureCounterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await incrementSecureCounter({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCounterQueryKey = (options: Options<GetCounterData>) => createQueryKey('getCounter', options);

export const getCounterOptions = (options: Options<GetCounterData>) => queryOptions<GetCounterResponse, GetCounterError, GetCounterResponse, ReturnType<typeof getCounterQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCounter({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCounterQueryKey(options)
});

export const incrementCounterMutation = (options?: Partial<Options<IncrementCounterData>>): UseMutationOptions<IncrementCounterResponse, IncrementCounterError, Options<IncrementCounterData>> => {
    const mutationOptions: UseMutationOptions<IncrementCounterResponse, IncrementCounterError, Options<IncrementCounterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await incrementCounter({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const uploadFileMutation = (options?: Partial<Options<UploadFileData>>): UseMutationOptions<UploadFileResponse, UploadFileError, Options<UploadFileData>> => {
    const mutationOptions: UseMutationOptions<UploadFileResponse, UploadFileError, Options<UploadFileData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadFile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
