services:
  api:
    build:
      context: ../../../apps/api
      dockerfile: ../../infra/docker/api/Dockerfile.prod
    restart: always
    ports:
      - "3001:3001"
    environment:
      - RUST_LOG=info
    networks:
      - lms-network

  web:
    build:
      context: ../../../apps/web
      dockerfile: ../../infra/docker/web/Dockerfile.prod
    restart: always
    ports:
      - "3000:3000"
    networks:
      - lms-network

networks:
  lms-network:
